force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/FSM_InfraDataCaptureForm2__c.object-meta.xml
<CustomObject>
    <description>Created as a part of SFS-3958</description>
    <label>Infra Data Capture Form 2</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Infra Data Capture Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 2</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_AM__c.field-meta.xml
<CustomField>
    <fullName>FSM_AM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-6005</description>
    <label>AM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_BridlewayFootpath__c.field-meta.xml
<CustomField>
    <fullName>FSM_BridlewayFootpath__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-6005</description>
    <label>Bridleway-Footpath</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Cycleway__c.field-meta.xml
<CustomField>
    <fullName>FSM_Cycleway__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-6005</description>
    <label>Cycleway</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Footway__c.field-meta.xml
<CustomField>
    <fullName>FSM_Footway__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-6005</description>
    <label>Footway</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Friday__c.field-meta.xml
<CustomField>
    <fullName>FSM_Friday__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFS-3010</description>
    <label>Friday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_FWRPlanningInformation__c.field-meta.xml
<CustomField>
    <fullName>FSM_FWRPlanningInformation__c</fullName>
    <description>Created as part of SFS-6005</description>
    <label>Planning information/Customer Comms</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_GridsReferenceX__c.field-meta.xml
<CustomField>
    <fullName>FSM_GridsReferenceX__c</fullName>
    <description>Created as part of SFS-3007</description>
    <label>Grids Reference X</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_GridsReferenceY__c.field-meta.xml
<CustomField>
    <fullName>FSM_GridsReferenceY__c</fullName>
    <description>Created as part of SFS-3007</description>
    <label>Grids Reference Y</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_HouseName__c.field-meta.xml
<CustomField>
    <fullName>FSM_HouseName__c</fullName>
    <description>Created as a part of SFS-4790</description>
    <label>House Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_HouseNo__c.field-meta.xml
<CustomField>
    <fullName>FSM_HouseNo__c</fullName>
    <description>Created as part of SFS-4790</description>
    <label>House No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Location__c.field-meta.xml
<CustomField>
    <fullName>FSM_Location__c</fullName>
    <description>SFS-3010</description>
    <inlineHelpText>This Information is visible to Highways Authority on the notice and must contain the correct address information</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Highway</fullName>
            </value>
            <value>
                <fullName>Private Land</fullName>
            </value>
            <value>
                <fullName>Off Highway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Monday__c.field-meta.xml
<CustomField>
    <fullName>FSM_Monday__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFS-3010</description>
    <label>Monday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Night__c.field-meta.xml
<CustomField>
    <fullName>FSM_Night__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-6005</description>
    <label>Night</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_OccupiersHouseName__c.field-meta.xml
<CustomField>
    <fullName>FSM_OccupiersHouseName__c</fullName>
    <description>SFS-3010</description>
    <label>Occupier&apos;s House Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_OccupiersHouseNo__c.field-meta.xml
<CustomField>
    <fullName>FSM_OccupiersHouseNo__c</fullName>
    <description>SFS-3010</description>
    <inlineHelpText>This Information is visible to Highways Authority on the notice and must contain the correct address information</inlineHelpText>
    <label>Occupier&apos;s House No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_OccupiersName__c.field-meta.xml
<CustomField>
    <fullName>FSM_OccupiersName__c</fullName>
    <description>SFS-3010</description>
    <label>Occupiers Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_OccupiersPostcode__c.field-meta.xml
<CustomField>
    <fullName>FSM_OccupiersPostcode__c</fullName>
    <description>SFS-3010</description>
    <label>Occupier&apos;s Postcode</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_OccupiersStreet__c.field-meta.xml
<CustomField>
    <fullName>FSM_OccupiersStreet__c</fullName>
    <description>SFS-3010</description>
    <label>Occupier&apos;s Street</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_OccupiersTelephoneNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_OccupiersTelephoneNumber__c</fullName>
    <description>SFS-3010
Updated as part of SFS-6577</description>
    <label>Occupier&apos;s Telephone No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_OccupiersTown__c.field-meta.xml
<CustomField>
    <fullName>FSM_OccupiersTown__c</fullName>
    <description>SFS-3010</description>
    <label>Occupier&apos;s Town</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_OwnersHouseName__c.field-meta.xml
<CustomField>
    <fullName>FSM_OwnersHouseName__c</fullName>
    <description>SFS-3010</description>
    <label>Owner&apos;s House Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_OwnersTelephoneNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_OwnersTelephoneNumber__c</fullName>
    <description>SFS-3010
Updated as part of SFS-6577</description>
    <label>Owner&apos;s Telephone No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_PedestrianZone__c.field-meta.xml
<CustomField>
    <fullName>FSM_PedestrianZone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-6005</description>
    <label>Pedestrian Zone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_PM__c.field-meta.xml
<CustomField>
    <fullName>FSM_PM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-6005</description>
    <label>PM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Postcode__c.field-meta.xml
<CustomField>
    <fullName>FSM_Postcode__c</fullName>
    <description>Created as part of SFS-4790</description>
    <label>Postcode</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_PrivateLand__c.field-meta.xml
<CustomField>
    <fullName>FSM_PrivateLand__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-6005</description>
    <label>Private Land</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Saturday__c.field-meta.xml
<CustomField>
    <fullName>FSM_Saturday__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFS-3010</description>
    <label>Saturday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_SFWXcoordinate__c.field-meta.xml
<CustomField>
    <fullName>FSM_SFWXcoordinate__c</fullName>
    <description>Created as a part of SFS-3010</description>
    <inlineHelpText>Grid Ref X needs to be between 240000 and 550000</inlineHelpText>
    <label>X co-ordinate</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_SFWYcoordinate__c.field-meta.xml
<CustomField>
    <fullName>FSM_SFWYcoordinate__c</fullName>
    <description>Created : SFS-3010</description>
    <inlineHelpText>Grid Ref Y needs to be between 170000 and 440000</inlineHelpText>
    <label>Y co-ordinate</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Street__c.field-meta.xml
<CustomField>
    <fullName>FSM_Street__c</fullName>
    <description>Created as a part of SFS-4790</description>
    <label>Street</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Sunday__c.field-meta.xml
<CustomField>
    <fullName>FSM_Sunday__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFS-3010</description>
    <label>Sunday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_TelephoneNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_TelephoneNumber__c</fullName>
    <description>Created as a part of SFS-4790</description>
    <label>Telephone No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Thursday__c.field-meta.xml
<CustomField>
    <fullName>FSM_Thursday__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFS-3010</description>
    <label>Thursday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Town__c.field-meta.xml
<CustomField>
    <fullName>FSM_Town__c</fullName>
    <description>Created as part of SFS-4790</description>
    <label>Town</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Tuesday__c.field-meta.xml
<CustomField>
    <fullName>FSM_Tuesday__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFS-3010</description>
    <label>Tuesday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_UserName__c.field-meta.xml
<CustomField>
    <fullName>FSM_UserName__c</fullName>
    <description>SFS-3010</description>
    <formula>CreatedBy.FirstName +  CreatedBy.LastName</formula>
    <label>User Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Verge__c.field-meta.xml
<CustomField>
    <fullName>FSM_Verge__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-6005</description>
    <label>Verge</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Wednesday__c.field-meta.xml
<CustomField>
    <fullName>FSM_Wednesday__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFS-3010</description>
    <label>Wednesday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as a part of SFS-3958</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Infra Data Capture Form 2</relationshipLabel>
    <relationshipName>FSM_InfraDataCaptureForm2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>SAP Order-Operation Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_Location__c.field-meta.xml
<CustomField>
    <fullName>FSM_Location__c</fullName>
    <description>Created as part of SFS-5350</description>
    <label>Location of Works</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <description>External ID</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/FSM_Phone__c.field-meta.xml
<CustomField>
    <fullName>FSM_Phone__c</fullName>
    <description>SFI-23 &amp; SFI-701</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/FSM_PostCode__c.field-meta.xml
<CustomField>
    <fullName>FSM_PostCode__c</fullName>
    <label>Post Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/FSM_Street__c.field-meta.xml
<CustomField>
    <fullName>FSM_Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <description>SFI-694</description>
    <externalId>true</externalId>
    <label>SAP User ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FSM_SketchPDFCtr_DCF2.cls
/*@author: Alagar 
@Date: 25/06/24
@comments: This creates a PDF of the edit image
@LastModifiedby:Brajesh Kumar
*/
public with sharing class FSM_SketchPDFCtr_DCF2 {
    
    public String dcfRecordId  {get;set;}
    public string bannerImageURL { get; set; }
    //public ServiceAppointment serviceAppointmentObj{get;set;}
    public FSM_InfraDataCaptureForm2__c dcfObj {get;set;}
    
    public String pdfNo{get;set;}
    public String efNo{get;set;}
    public boolean show{get;set;}
    public boolean showpdf{get;set;}
    //public ApexPages.PageReference page2{get;set;}
    public String imageURL{get;set;}
    public String username{get;set;}
    public String phonenumber{get;set;}
    public String contentId{get;set;}
    public List<Id> siteIds {get;set;}
    public List<Id> photoIds {get;set;}
    public List<Id> bannerIds {get;set;}
    public Id cversionId{get;set;}
    public Date currDate{get;set;}
    public string addressFields{get;set;}
    public String dateString{get;set;}
    /*
@method: constructor
@comments: constructor function
*/
    String binVar = '';
    public FSM_SketchPDFCtr_DCF2(){
        binVar = '';
    }
    
    /*
@method: FSM_SketchPDFCtr_DCF2
@comments: constructor function
*/
    public FSM_SketchPDFCtr_DCF2(ApexPages.StandardController controller){
        
        //SFS-5401 - get current date and Address
        currDate = Date.Today();
        Date d = Date.today();
        Datetime dt = Datetime.newInstance(d.year(), d.month(),d.day());
        dateString = dt.format('dd-MM-yyyy');
        
        
        Id userId =UserInfo.getUserId(); 
        User u = [SELECT Name FROM User WHERE Id =: userId];
        List<ServiceResource> sr=[Select FSM_Phone__c,Name from ServiceResource where RelatedRecordId=:userId Limit 1 ];
        if (!sr.isEmpty()) {
            phoneNumber = sr[0].FSM_Phone__c;
             username=sr[0].Name;
        }
        dcfRecordId = ApexPages.currentPage().getParameters().get('id');
        dcfObj = [Select Id,FSM_UserName__c,FSM_TelephoneNumber__c,FSM_GridsReferenceX__c,FSM_GridsReferenceY__c,       
                  FSM_Location__c,      
                  FSM_HouseName__c,
                  FSM_WorkOrder__r.WorkOrderNumber,
                  FSM_WorkOrder__r.FSM_ExternalId__c,
                  FSM_HouseNo__c,       
                  FSM_Street__c,FSM_Town__c,FSM_PostCode__c,FSM_OccupiersHouseName__c,FSM_OccupiersPostcode__c,FSM_OccupiersHouseNo__c,FSM_OccupiersTown__c,FSM_OccupiersStreet__c,FSM_OccupiersName__c,FSM_OccupiersTelephoneNumber__c,
                  FSM_OwnersTelephoneNumber__c,
                  FSM_Verge__c,FSM_BridlewayFootpath__c,FSM_PrivateLand__c,FSM_Footway__c,FSM_Cycleway__c,FSM_PedestrianZone__c,
                  FSM_SFWXcoordinate__c,FSM_SFWYcoordinate__c,
                  FSM_FWRPlanningInformation__c,
                  FSM_Monday__c,FSM_Tuesday__c,
                  FSM_Wednesday__c,FSM_Thursday__c,FSM_Friday__c,FSM_Saturday__c,FSM_Sunday__c,FSM_AM__c,FSM_PM__c,FSM_Night__c,
                  FSM_OwnersHouseName__c,FSM_OwnersHouseNo__c,FSM_OwnersStreet__c,FSM_OwnersTown__c,FSM_OwnersPostcode__c,FSM_Carriageway__c,
                  toLabel(FSM_SWRJobScope__c),toLabel(FSM_SWRTransferredAsset__c),      
                  toLabel(FSM_SWRAsset__c),toLabel(FSM_SWRTask__c),toLabel(FSM_SWRJobRecipient__c),FSM_FWRFootwayWidth__c,FSM_FWRCarriagewayWidth__c,FSM_Speed__c ,     
                  FSM_FWRRoadType__c,FSM_FWRVisibilityToMenAtWork__c,   
                  FSM_SurfaceType__c,FSM_FWRTrafficFlow__c,FSM_FWRPedestrianWalkway__c, 
                  FSM_FWRSpecialFeature__c,FSM_FWRPedestrianLights__c,FSM_TrafficLightRestriction__c,   
                  FSM_FWRTrainOrTram__c,        
                  FSM_FWRBus__c ,       
                  FSM_FWRCycle__c ,             
                  FSM_FWRCommsMethod__c,        
                  FSM_FWRCommsType__c  FROM FSM_InfraDataCaptureForm2__c
                  Where Id =: dcfRecordId ];
        
        addressFields = dcfObj.FSM_WorkOrder__r.FSM_ExternalId__c!=null ? ' '+dcfObj.FSM_WorkOrder__r.FSM_ExternalId__c: '';
        addressFields +=dcfObj.FSM_OccupiersHouseName__c!=null ? ' '+dcfObj.FSM_OccupiersHouseName__c : '';
        addressFields +=dcfObj.FSM_OccupiersHouseNo__c!= null ? ' '+string.valueOf(dcfObj.FSM_OccupiersHouseNo__c) : '';
        addressFields +=dcfObj.FSM_OccupiersStreet__c!=null ? ' '+dcfObj.FSM_OccupiersStreet__c: '';
    }
    
    /*
@method: pdfAction
@comments: creates the PDF
*/
    public void pdfAction()
    {
        siteIds = new List<Id>();
        photoIds = new List<Id>();
        bannerIds=new List<Id>();
        system.debug('inside pdfAction');
        //id cversionId;
        id bannerid;
        dcfRecordId = ApexPages.currentPage().getParameters().get('id');
        
        List<ContentVersion> documentList = new List<ContentVersion>();
        
        List<ContentDocumentLink> contentDocumentLinkList = new List<ContentDocumentLink>();    
        
        ContentDocumentLinkList = [SELECT Id, LinkedEntityId, ContentDocumentId,ContentDocument.LatestPublishedVersionId, Visibility, IsDeleted, ShareType,
                                   ContentDocument.Title, ContentDocument.createdDate, ContentDocument.FileType 
                                   FROM ContentDocumentLink WHERE LinkedEntityId =: dcfRecordId and ContentDocument.Title = 'sketch.jpeg' WITH SECURITY_ENFORCED LIMIT 1];
        
        if(ContentDocumentLinkList.size() > 0)
        {
            documentList=[SELECT id, Title, ContentDocumentId, ContentDocument.id,ContentDocument.LatestPublishedVersionId 
                          FROM ContentVersion WHERE ContentDocumentId =: ContentDocumentLinkList[0].ContentDocumentId WITH SECURITY_ENFORCED LIMIT 1];
            contentId= documentList[0].id;
        }   
        
        //Site Icons
        Set<Id> siteDocId = new Set<Id>();
        List<ContentDocumentLink> siteiconlist=new List<ContentDocumentLink>();
        siteiconlist=[SELECT Id, LinkedEntityId, ContentDocumentId,ContentDocument.LatestPublishedVersionId FROM ContentDocumentLink
                      WHERE LinkedEntityId =: dcfRecordId and ContentDocument.Title like '%Site%' WITH SECURITY_ENFORCED];
        if(siteiconlist.size() > 0){
            
            for(ContentDocumentLink sd:siteiconlist){
                siteDocId.add(sd.ContentDocumentId );                                               
            }
            
            for(ContentVersion cv: [SELECT id, Title, ContentDocumentId, ContentDocument.id,ContentDocument.LatestPublishedVersionId 
                                    FROM ContentVersion WHERE ContentDocumentId IN: siteDocId  WITH SECURITY_ENFORCED]){
                                        siteIds.add(cv.Id);
                                    }
        }
        
        
        //Photo Capture
        Set<Id> photoDocId = new Set<Id>();
        List<ContentDocumentLink> photoiconlist=new List<ContentDocumentLink>();
        photoiconlist=[SELECT Id, LinkedEntityId, ContentDocumentId,ContentDocument.LatestPublishedVersionId,SystemModstamp FROM ContentDocumentLink
                       WHERE LinkedEntityId =: dcfRecordId and ContentDocument.Title like '%Photo%' WITH SECURITY_ENFORCED ORDER BY SystemModstamp DESC limit 3];
        if(photoiconlist.size()>0){
            for(ContentDocumentLink pd: photoiconlist){
                photoDocId.add(pd.ContentDocumentId );                                               
            }
            
            for(ContentVersion cv: [SELECT id, Title, ContentDocumentId, ContentDocument.id,ContentDocument.LatestPublishedVersionId 
                                    FROM ContentVersion WHERE ContentDocumentId IN: photoDocId WITH SECURITY_ENFORCED]){
                                        photoIds.add(cv.Id);
                                    }
        }
        List<ContentDocumentLink> cdlink=new List<ContentDocumentLink>();    
        Set<id> cdocid=new Set<id>();
        //ContentDocumentLink cdlink=new ContentDocumentLink();
        cdlink= [SELECT Id, LinkedEntityId, ContentDocumentId,ContentDocument.LatestPublishedVersionId FROM ContentDocumentLink
                 WHERE LinkedEntityId =: dcfRecordId and ContentDocument.Title like '%Banner%' WITH SECURITY_ENFORCED];
        if(cdlink.size() > 0){
            for(ContentDocumentLink bd: cdlink){
                cdocid.add(bd.ContentDocumentId );                                               
            }  
            for(ContentVersion cv: [SELECT id, Title, ContentDocumentId, ContentDocument.id,ContentDocument.LatestPublishedVersionId 
                                    FROM ContentVersion WHERE ContentDocumentId IN:cdocid  WITH SECURITY_ENFORCED]){
                                        bannerIds.add(cv.Id);
                                        
                                        
                                    }
            cversionId=bannerIds[0];
            system.debug('cversionId id of banner'+cversionId);
        }
        
        
    }
    
}