force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/FSM_InfraDataCaptureForm2__c.object-meta.xml
<CustomObject>
    <description>Created as a part of SFS-3958</description>
    <label>Infra Data Capture Form 2</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Infra Data Capture Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 2</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Generate_PDF__c.field-meta.xml
<CustomField>
    <fullName>FSM_Generate_PDF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-6005</description>
    <label>Generate PDF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Status__c.field-meta.xml
<CustomField>
    <fullName>FSM_Status__c</fullName>
    <description>Created as a part of SFS-3958</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_WorkPlanTemplateMapping__mdt/FSM_WorkPlanTemplateMapping__mdt.object-meta.xml
<CustomObject>
    <description>To store the work plan template Id, SFS-33</description>
    <label>Work Plan Template Mapping</label>
    <pluralLabel>Work Plan Template Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSM_WorkPlanTemplateMapping__mdt/fields/FSM_RecordTypeDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>FSM_RecordTypeDeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>SFS-33</description>
    <label>Record Type Developer Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FSM_WorkPlanTemplateMapping__mdt/fields/FSM_WorkPlanTemplateName__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkPlanTemplateName__c</fullName>
    <description>SFS-33</description>
    <label>Work Plan Template Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSM_DCFInfraTwoTriggerTest.cls
/********************************************************************************************************
@Author      : Brajesh Kumar
@Description : This class is created to cover FSM_DCFInfraTwoTriggerHelper, FSM_DCFInfraTwoTriggerHandler, FSM_DCFInfraTwoTrigger
@Description : Created as part of user story #SFS-5399
@Date        : 28-June-2024
********************************************************************************************************/
@isTest
public class FSM_DCFInfraTwoTriggerTest {
    @testsetup
    static void testSetup(){
        FSM_WorkPlanTemplateMapping__mdt woMdt = [Select MasterLabel,FSM_RecordTypeDeveloperName__c,FSM_WorkPlanTemplateName__c from FSM_WorkPlanTemplateMapping__mdt limit 1];
        
        WorkPlanTemplate woTemp = new FSM_TestDataFactory.WorkPlanTemplateCreator().setName(woMdt.FSM_WorkPlanTemplateName__c).setIsActive(true).create();
        
        WorkStepTemplate woStep = new FSM_TestDataFactory.WorkStepTemplateCreator().setName('Test workStep').setIsActive(true).create();
        
        WorkPlanTemplateEntry woEntry = new FSM_TestDataFactory.WorkPlanTemplateEntryCreator().setWorkPlanTemplateId(woTemp.Id).setWorkStepTemplateId(woStep.Id).create();
        Account acc=new FSM_TestDataFactory.AccountCreator().setName('test acc').create();
        Contact con=new FSM_TestDataFactory.ContactCreator().setFirstName('test').setLastName('testsurname').setAccount(acc.id).setEmail('no-reply@defaultemail.com').create();
        new FSM_TestDataFactory.CaseCreator().setStatus('New').setOrigin('Web').setContactName('Jon Hall').setContactEmail('jon.hall@gmail.com').create();        
        
        WorkOrder wo = new FSM_TestDataFactory.WorkOrderCreator().setExternalId('testId').setStatus('New').setBusinessUnit('Waste Infra').create();
        DateTime earliestdte = datetime.newInstance(2024, 06, 28, 12, 30, 0);
        DateTime duedate = datetime.newInstance(2024, 06, 28, 13, 30, 0);
        boolean pdfgenerate=false;
        //Id recTypeId = Schema.SObjectType.ServiceAppointment.getRecordTypeInfosByDeveloperName().get(FSM_Constants.RECORDTYPE_WASTEINFRA).getRecordTypeId();
        id rectype=Schema.SObjectType.ServiceAppointment.getRecordTypeInfosByDeveloperName().get(FSM_Constants.RECORDTYPE_WASTEINFRA).getRecordTypeId();
        id fwrrectype=Schema.SObjectType.FSM_InfraDataCaptureForm2__c.getRecordTypeInfosByDeveloperName().get(FSM_Constants.RECORDTYPE_SEWERAGEFURTHERWORKREQUEST).getRecordTypeId();
        ServiceAppointment sv= new FSM_TestDataFactory.ServiceAppointmentCreator().setRecordType(rectype).setParentRecordId(wo.id).setStatus('New').setEarliestStartTime(earliestdte).setDueDate(duedate).create();
        FSM_InfraDataCaptureForm2__c dcf=new FSM_TestDataFactory.DataCaptureForm2Creator().setWorkorder(wo.id).setGeneratepdf(pdfgenerate).setRecordTypeId(fwrrectype).create();
        ContentVersion cv1 = new FSM_TestDataFactory.ContentVersionCreator().setPathOnClient('Site1.jpeg').setTitle('Site1').setVersionData(Blob.valueOf( 'Testing content version')).setRelatedrecordId(dcf.id).create();
        ContentVersion cv2 = new FSM_TestDataFactory.ContentVersionCreator().setPathOnClient('Site2.jpeg').setTitle('Site2').setVersionData(Blob.valueOf( 'Testing content version')).setRelatedrecordId(dcf.id).create();
        ContentVersion cv3 = new FSM_TestDataFactory.ContentVersionCreator().setPathOnClient('sketch.jpeg').setTitle('sketch.jpeg').setVersionData(Blob.valueOf( 'Testing content version')).setRelatedrecordId(dcf.id).create();
        ContentVersion cv4 = new FSM_TestDataFactory.ContentVersionCreator().setPathOnClient('Banner.jpeg').setTitle('Banner.jpeg').setVersionData(Blob.valueOf( 'Testing content version')).setRelatedrecordId(dcf.id).create();
        
    }
    
    @isTest
    static void testgeneratepdf(){
        Test.startTest();
        FSM_InfraDataCaptureForm2__c dcfrec=[Select id,FSM_Generate_PDF__c from FSM_InfraDataCaptureForm2__c LIMIT 1];
        String dcfId = dcfrec.id;
        dcfrec.FSM_Generate_PDF__c=true;
        update dcfrec;
        Test.stopTest();
        FSM_InfraDataCaptureForm2__c dcfRecord=[Select id,FSM_Generate_PDF__c,FSM_Status__c from FSM_InfraDataCaptureForm2__c where id =:dcfId ];
		System.assertEquals('Completed', dcfRecord.FSM_Status__c, 'Failed to Generate PDF');   
    }
    
}