force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/FSM_InfraDataCaptureForm2__c.object-meta.xml
<CustomObject>
    <description>Created as a part of SFS-3958</description>
    <label>Infra Data Capture Form 2</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Infra Data Capture Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 2</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Generate_PDF__c.field-meta.xml
<CustomField>
    <fullName>FSM_Generate_PDF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-6005</description>
    <label>Generate PDF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as a part of SFS-3958</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Infra Data Capture Form 2</relationshipLabel>
    <relationshipName>FSM_InfraDataCaptureForm2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_WorkStep__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as a part of SFS-3958</description>
    <label>Work Step</label>
    <referenceTo>WorkStep</referenceTo>
    <relationshipLabel>FSM_InfraDataCaptureForm2</relationshipLabel>
    <relationshipName>FSM_InfraDataCaptureForm2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/recordTypes/FSM_SewerageFurtherWorkRequestSCM.recordType-meta.xml
<RecordType>
    <fullName>FSM_SewerageFurtherWorkRequestSCM</fullName>
    <active>true</active>
    <description>SFS-3010</description>
    <label>Sewerage-Further Work Request (SCM)</label>
</RecordType>

force-app/main/default/classes/FSM_DCFInfraTwoTriggerHelper.cls
/********************************************************************************************************
@Author      : Brajesh Kumar
@Description : This class is used to call vf page for pdf creation of dcf infra form 2.
@Description : Created as part of user story #SFS-5399
@Description : Invoked from FSM_DCFInfraTwoTriggerHandler class
@Test Class  : FSM_DCFInfraTwoTriggerTest
@Date        : 28-June-2024
********************************************************************************************************/
public class FSM_DCFInfraTwoTriggerHelper {
    public void generatePdf(Map<Id,sObject> newMap,Map<Id,sObject> oldMap){
        Map<Id, FSM_InfraDataCaptureForm2__c> allNewDCF=(Map<Id, FSM_InfraDataCaptureForm2__c>)newMap; //collecting all updated Data capture form infra records
        Map<Id, FSM_InfraDataCaptureForm2__c> allOldDCF=(Map<Id, FSM_InfraDataCaptureForm2__c>)oldMap; //collecting all updated Data capture form infra records old value
        List<FSM_InfraDataCaptureForm2__c>dcfinfraUpdtList=new List<FSM_InfraDataCaptureForm2__c>();
        for(FSM_InfraDataCaptureForm2__c cmp : allNewDCF.values()) {
            if((cmp.FSM_Generate_PDF__c!=allOldDCF.get(cmp.Id).FSM_Generate_PDF__c) && (allOldDCF.get(cmp.Id).FSM_Generate_PDF__c==false))
            {	
                system.debug('data capture form id'+cmp);
                String woRecordId = [Select Id,FSM_WorkOrder__c,FSM_WorkStep__r.Id  from FSM_InfraDataCaptureForm2__c where id=:cmp.Id AND RecordType.DeveloperName = 'FSM_SewerageFurtherWorkRequestSCM' Limit 1].FSM_WorkOrder__c;
                ServiceAppointment sa = [Select Id from ServiceAppointment where ParentRecordId=:woRecordId order by createdDate desc Limit 1];
                try{ 
                    FSM_sketchCls_DCF2.pdfCreation(sa.Id,cmp.Id);
                }catch(Exception e){
                    system.debug('error'+e);
                }
            }else{
                system.debug('do nothing');
            }
            
        }
        
    }
    
}