force-app/main/default/objects/Case/fields/FSM_TMAPermit__c.field-meta.xml
<CustomField>
    <fullName>FSM_TMAPermit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SFI-1561</description>
    <label>TMA Permit</label>
    <referenceTo>FSM_TMAPermit__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSL__Time_Dependency__c/FSL__Time_Dependency__c.object-meta.xml
<CustomObject>
    <label>Appointment Dependency</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>Appointment Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment Dependencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/FSM_DataCaptureFormInfra__c.object-meta.xml
<CustomObject>
    <description>Data capture form structure for Infra BU only, SFI-35 and SFS-1950</description>
    <label>Infra Data Capture Form 1</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Data Capture Form Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 1</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DataCaptureFormNonInfra__c/FSM_DataCaptureFormNonInfra__c.object-meta.xml
<CustomObject>
    <description>Data capture form structure for Non-Infra BU only, SFI-35</description>
    <label>Data Capture Form Non Infra</label>
    <nameField>
        <displayFormat>DCFNONINF-{000000}</displayFormat>
        <label>Data Capture Form Non Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Capture Form Non Infras</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_TMAPermit__c/FSM_TMAPermit__c.object-meta.xml
<CustomObject>
    <description>Created as part of user story #SFS-32</description>
    <label>TMA</label>
    <nameField>
        <displayFormat>TMAPER-{000000}</displayFormat>
        <label>TMA Permit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_TMAPermitConditions__c/FSM_TMAPermitConditions__c.object-meta.xml
<CustomObject>
    <description>Created as part of user story #SFS-32</description>
    <label>TMA  Condition</label>
    <nameField>
        <displayFormat>TMAPERCOND-{000000}</displayFormat>
        <label>TMA Permit Conditions Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMA  Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_TMAPermitConditions__c/fields/FSM_TMAPermit__c.field-meta.xml
<CustomField>
    <fullName>FSM_TMAPermit__c</fullName>
    <description>Created as part of user story #SFS-32</description>
    <label>FSM TMA Permit</label>
    <referenceTo>FSM_TMAPermit__c</referenceTo>
    <relationshipName>FSM_TMAPermitConditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_TMAPermit__c.field-meta.xml
<CustomField>
    <fullName>FSM_TMAPermit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TMA Permit</label>
    <referenceTo>FSM_TMAPermit__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FSM_CaseBatchDeletionTest.cls
/********************************************************************************************************
@Author      : Himanshu Dobriyal
@Description : This test class is to test FSM_CaseBatchDeletion and FSM_CaseBatchDeletionScheduler class.
@description : Created as part of user story #SFI-468
@Test Class  : FSM_CaseBatchDeletionTest
@Date        : 25-July-2023
********************************************************************************************************/
@isTest(SeeAllData = False)
public class FSM_CaseBatchDeletionTest {
    @TestSetUp
    static void testDataSetUp(){
        //Get RecordType Id 
        Id recTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName().get(FSM_Constants.RECORDTYPE_DEVELOPERSERVICES).getRecordTypeId();
        // Create a Test permit
        FSM_TMAPermit__c testPermit = new FSM_TestDataFactory.TMAPermitCreator().create();
        // Create a Test permitcondition
        //FSM_TMAPermitConditions__c testPermitCondition = 
        new FSM_TestDataFactory.TMAPermitConditionsCreator().setTMAPermit(testPermit.id).create();
        // Create a Test Case
        List<Case> allcase = new List<Case>();
        allcase.add(new FSM_TestDataFactory.CaseCreator().setTMA(testPermit.Id).setStatus('New').setOrigin('Web').setContactName('Jon Hall').setContactEmail('jon.hall@gmail.com').returnWithoutCreate());
        allcase.add(new FSM_TestDataFactory.CaseCreator().setTMA(testPermit.Id).setStatus('New').setOrigin('Web').setContactName('Jon Hall').setContactEmail('jon.hall@gmail.com').returnWithoutCreate());
        Insert allcase;
        //Create Account
        Account acc = new FSM_TestDataFactory.AccountCreator().setName('Test Account').create();
        //Create Contact
        new FSM_TestDataFactory.ContactCreator().setFirstName('FSM').setLastName('Salesforce Default Contact For Email').setAccount(acc.ID)
                        .setEmail('no-reply@defaultemail.com').create();
        
        //Create workorder associated with case and permit 
        List<WorkOrder> allWO = new List<WorkOrder>();
        allWO.add(new FSM_TestDataFactory.WorkOrderCreator().setBusinessUnit('Developer Services').setRecordType(recTypeId).setPermit(testPermit.Id).setCaseId(allcase[0].Id).returnWithoutCreate());
        allWO.add(new FSM_TestDataFactory.WorkOrderCreator().setBusinessUnit('Developer Services').setRecordType(recTypeId).setPermit(testPermit.Id).setCaseId(allcase[1].Id).returnWithoutCreate());
        Insert allWO;
        
        // Create Test ServiceApointment associated with the workorder
        List<ServiceAppointment> allApp = new List<ServiceAppointment>();
        allApp.add(new FSM_TestDataFactory.ServiceAppointmentCreator().setParentRecordId(allWO[0].Id).setStatus('new').returnWithoutCreate());
        allApp.add(new FSM_TestDataFactory.ServiceAppointmentCreator().setParentRecordId(allWO[0].Id).setStatus('new').returnWithoutCreate());
        allApp.add(new FSM_TestDataFactory.ServiceAppointmentCreator().setParentRecordId(allWO[0].Id).setStatus('new').setIsBundle(true).returnWithoutCreate());
        Insert allApp;
        
        new FSM_TestDataFactory.ServiceAppointmentCreator().setParentRecordId(allWO[1].Id).setStatus('new').setIsBundleMember(true).setRelatedBundleId(allApp[2].id).Create();
        
        //FSL__Time_Dependency__c creation 
        new FSM_TestDataFactory.AppointmentDependencyCreator().setServiceAppointment1(allApp[0].Id).setServiceAppointment2(allApp[1].Id).create();
        //FSM_DataCaptureFormInfra__c creation
        new FSM_TestDataFactory.DataCaptureFormInfraCreator().setWorkorder(allWO[0].Id).create();
        //FSM_DataCaptureFormNonInfra__c creation
        new FSM_TestDataFactory.DataCaptureFormNonInfraCreator().setWorkorder(allWO[0].Id).create();
    }
    @isTest
    static void testBatchDeletion() {
        list<case> casehd = [select id,status from case limit 1];
        // Start the batch process
        Test.startTest();
        casehd[0].status = 'closed';
        update casehd;
        FSM_CaseBatchDeletion batchDeletion = new FSM_CaseBatchDeletion();
        Database.executeBatch(batchDeletion);
        Test.stopTest();
         // list<case> excase = [select id from case];        
        // Verify that the cases have been deleted        
        System.assertEquals(0, [SELECT COUNT() FROM Case WHERE Status = 'Closed'],'all case should be deleted');
        System.assertEquals(0, [SELECT COUNT() FROM FSM_TMAPermitConditions__c],'all related child record should be deleted');
        
       
    }
    // To check scheduler class
    @isTest
    static void testSchedulerBatchDeletion() {
        Test.startTest();
        String jobId = System.schedule('Test FSM_CaseBatchDeletionScheduler', '0 0 0 * * ?', new FSM_CaseBatchDeletionScheduler());
        Test.stopTest();
        
        // Verify that the batch job has been scheduled
        System.assertEquals(1, [SELECT count() FROM CronTrigger WHERE Id = :jobId],'One job should be schedule at midnight daily');
        
    }
}