force-app/main/default/objects/Case/fields/FSM_ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>FSM_ContactEmail__c</fullName>
    <label>Contact Email</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Case/fields/FSM_ContactID__c.field-meta.xml
<CustomField>
    <fullName>FSM_ContactID__c</fullName>
    <description>Customer name</description>
    <label>Contact ID</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Case/fields/FSM_ContactName__c.field-meta.xml
<CustomField>
    <fullName>FSM_ContactName__c</fullName>
    <label>Contact Name</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Case/fields/FSM_ContactPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_ContactPhoneNumber__c</fullName>
    <label>Contact Phone Number</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Case/fields/FSM_isRefreshed__c.field-meta.xml
<CustomField>
    <fullName>FSM_isRefreshed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-4132</description>
    <label>Is Refreshed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/FSM_MSN__c.field-meta.xml
<CustomField>
    <fullName>FSM_MSN__c</fullName>
    <label>Manufacturers Serial Number</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Case/fields/FSM_SpecialCondition__c.field-meta.xml
<CustomField>
    <fullName>FSM_SpecialCondition__c</fullName>
    <label>Special Condition</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>FSM_ContactEmail__c</fullName>
    <label>Contact Email</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_ContactID__c.field-meta.xml
<CustomField>
    <fullName>FSM_ContactID__c</fullName>
    <label>Contact ID</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_ContactName__c.field-meta.xml
<CustomField>
    <fullName>FSM_ContactName__c</fullName>
    <label>Contact name</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_ContactPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_ContactPhoneNumber__c</fullName>
    <label>Contact Phone Number</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_isRefreshed__c.field-meta.xml
<CustomField>
    <fullName>FSM_isRefreshed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-4132</description>
    <label>Is Refreshed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_ManufacturersSerialNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_ManufacturersSerialNumber__c</fullName>
    <label>Manufacturers Serial Number</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_SpecialCondition__c.field-meta.xml
<CustomField>
    <fullName>FSM_SpecialCondition__c</fullName>
    <label>Special Condition</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/FSM_PrepareMySandboxTest.cls
/********************************************************************************************************
@Author      : Brajesh Kumar
@description : This class is used to test batch job to support data masking / anonymization of data 
@description : Created as part of user story #SFS-4144
@Main Class  : FSM_PrepareMySandboxBatchUpdate and FSM_PrepareMySandbox 
@Date        : 07-February-2024
********************************************************************************************************/
@isTest
class FSM_PrepareMySandboxTest {
    /*******************************************************************************************************
@Author      : Brajesh Kumar
@Description : This method is used to create test data setup.
********************************************************************************************************/
    /* Created for test data setup */
    @testsetup 
    static void makeData(){
        Case c = new FSM_TestDataFactory.CaseCreator().setContactId('23424567').setContactName('Alex').setContactEmail('alex@stw.co.uk').setContactPhoneNumber('987654321').setSpecialCondition('Apex Class Test').setMSN('565657').create();
		WorkOrder wo = new FSM_TestDataFactory.WorkOrderCreator().setContactId(c.FSM_ContactID__c).setContactName(c.FSM_ContactName__c).setContactEmail(c.FSM_ContactEmail__c).setContactPhone(c.FSM_ContactPhoneNumber__c).setSpecialCondition(c.FSM_SpecialCondition__c).setMSN(c.FSM_MSN__c).create();
    }
    
    @isTest
    static void testMySandboxPrep() {  
        Test.startTest();
        //Execute test script with RunAsAutoProcUser set to true
        Test.testSandboxPostCopyScript(
            new FSM_PrepareMySandbox(), UserInfo.getOrganizationId(),
            UserInfo.getOrganizationId(), UserInfo.getOrganizationName(), true);
        Test.stopTest();
        // Perform queries to retrieve the updated Case and Work Order
        Case cse = [SELECT id,FSM_ContactID__c,FSM_ContactName__c,FSM_ContactEmail__c,FSM_ContactPhoneNumber__c,FSM_SpecialCondition__c,FSM_MSN__c,FSM_isRefreshed__C FROM Case];
        WorkOrder wos = [SELECT id,FSM_ContactID__c,FSM_ContactName__c,FSM_ContactEmail__c,FSM_ContactPhoneNumber__c,FSM_SpecialCondition__c,
                         FSM_ManufacturersSerialNumber__c,FSM_isRefreshed__c FROM WorkOrder];
        
        // Assert the expected results to verify that the Case Record is Masked and FSM_isRefreshed__c = True
        System.assertEquals(True, cse.FSM_isRefreshed__c, 'Successfully Masked Case Record Data');
        // Assert the expected results to verify that the Work Order Record is Masked and FSM_isRefreshed__c = True
        System.assertEquals(True, wos.FSM_isRefreshed__c, 'Successfully Masked Work Order Record Data');
    }
}