force-app/main/default/objects/Case/fields/FSM_ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>FSM_ContactEmail__c</fullName>
    <label>Contact Email</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Case/fields/FSM_ContactName__c.field-meta.xml
<CustomField>
    <fullName>FSM_ContactName__c</fullName>
    <label>Contact Name</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_CustCoordinatorNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_CustCoordinatorNumber__c</fullName>
    <description>created as part of SFS-5349</description>
    <label>Customer Coordinator - Contact Number</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nottingham – 07890948951</fullName>
            </value>
            <value>
                <fullName>Derby  - 07890948949</fullName>
            </value>
            <value>
                <fullName>Leicester - 07890950118</fullName>
            </value>
            <value>
                <fullName>Warwickshire - 07890948950</fullName>
            </value>
            <value>
                <fullName>Central - 07890948948</fullName>
            </value>
            <value>
                <fullName>Worcester &amp; Gloucester - 07890950121</fullName>
            </value>
            <value>
                <fullName>Staffordshire - 07583100439</fullName>
            </value>
            <value>
                <fullName>Shropshire – 07890948953</fullName>
            </value>
            <value>
                <fullName>Customer Leak Support – 03452 660036</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_FieldworkerVynUrl__c.field-meta.xml
<CustomField>
    <fullName>FSM_FieldworkerVynUrl__c</fullName>
    <description>Created as Part of SFS-5306</description>
    <label>Fieldworker Vyn URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_Flow__c.field-meta.xml
<CustomField>
    <fullName>FSM_Flow__c</fullName>
    <description>created as part of SFS-5352</description>
    <label>Flow (lps)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_FWRole__c.field-meta.xml
<CustomField>
    <fullName>FSM_FWRole__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>R&amp;M/ Reinstatement</fullName>
            </value>
            <value>
                <fullName>Inspector</fullName>
            </value>
            <value>
                <fullName>R&amp;M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_MailJetFieldsToBeBlanked__c.field-meta.xml
<CustomField>
    <fullName>FSM_MailJetFieldsToBeBlanked__c</fullName>
    <description>SFS-8264 and SFS-8263</description>
    <label>MailJet Fields To Be Blanked</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_OperativeContactNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_OperativeContactNumber__c</fullName>
    <description>created as part of SFS-5345
updated as part of SFS-7922</description>
    <label>Operative Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_Pressure__c.field-meta.xml
<CustomField>
    <fullName>FSM_Pressure__c</fullName>
    <description>created as part of SFS-5345</description>
    <label>Pressure (mhd)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_SuspendCategory__c.field-meta.xml
<CustomField>
    <fullName>FSM_SuspendCategory__c</fullName>
    <label>Suspend Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>H&amp;S</fullName>
            </value>
            <value>
                <fullName>Plant/Equipment/Vehicle</fullName>
            </value>
            <value>
                <fullName>Preparation</fullName>
            </value>
            <value>
                <fullName>Asset Data</fullName>
            </value>
            <value>
                <fullName>Asset Care</fullName>
            </value>
            <value>
                <fullName>AUTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_SuspendReason__c.field-meta.xml
<CustomField>
    <fullName>FSM_SuspendReason__c</fullName>
    <label>Suspend Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FSM_SuspendCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ITES</fullName>
                <label>End of shift</label>
            </value>
            <value>
                <fullName>PLER</fullName>
                <label>Emergency/Reactive Work</label>
            </value>
            <value>
                <fullName>ITUA</fullName>
                <label>Unplanned absence</label>
            </value>
            <value>
                <fullName>ITTD</fullName>
                <label>Travel delays</label>
            </value>
            <value>
                <fullName>AVND</fullName>
                <label>No DST available</label>
            </value>
            <value>
                <fullName>CUNH</fullName>
                <label>CUSTOMER Not at home</label>
            </value>
            <value>
                <fullName>PLRC</fullName>
                <label>Requested by Customer</label>
            </value>
            <value>
                <fullName>SINL</fullName>
                <label>No access-Customer/Land owner</label>
            </value>
            <value>
                <fullName>CUNR</fullName>
                <label>Customer site not ready</label>
            </value>
            <value>
                <fullName>OTHS</fullName>
                <label>Health and safety</label>
            </value>
            <value>
                <fullName>OTAW</fullName>
                <label>Adverse weather conditions</label>
            </value>
            <value>
                <fullName>OTFT</fullName>
                <label>Incorrect Skills</label>
            </value>
            <value>
                <fullName>PLOR</fullName>
                <label>Obstruction removal required</label>
            </value>
            <value>
                <fullName>OTAS</fullName>
                <label>Dangerous situation</label>
            </value>
            <value>
                <fullName>HSED</fullName>
                <label>Engineering Difficulties</label>
            </value>
            <value>
                <fullName>HSAR</fullName>
                <label>Additional resource</label>
            </value>
            <value>
                <fullName>VEIN</fullName>
                <label>Incorrect</label>
            </value>
            <value>
                <fullName>JBFN</fullName>
                <label>Part unavailable</label>
            </value>
            <value>
                <fullName>JBTE</fullName>
                <label>Not available</label>
            </value>
            <value>
                <fullName>OTMS</fullName>
                <label>System error</label>
            </value>
            <value>
                <fullName>VEBR</fullName>
                <label>Breakdown</label>
            </value>
            <value>
                <fullName>PLFW</fullName>
                <label>Further visit/work required</label>
            </value>
            <value>
                <fullName>PRNW</fullName>
                <label>No work required</label>
            </value>
            <value>
                <fullName>SINA</fullName>
                <label>No access/Parking</label>
            </value>
            <value>
                <fullName>JBTM</fullName>
                <label>Traffic Mgnt not available</label>
            </value>
            <value>
                <fullName>PRNB</fullName>
                <label>Traffic Mgnt not booked</label>
            </value>
            <value>
                <fullName>JBDO</fullName>
                <label>Duplicate operation</label>
            </value>
            <value>
                <fullName>SIDH</fullName>
                <label>Dry hole</label>
            </value>
            <value>
                <fullName>SIWC</fullName>
                <label>Work conflict</label>
            </value>
            <value>
                <fullName>PLPD</fullName>
                <label>Permission to dig required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>FSM_ContactEmail__c</fullName>
    <label>Contact Email</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_ContactName__c.field-meta.xml
<CustomField>
    <fullName>FSM_ContactName__c</fullName>
    <label>Contact name</label>
    <length>174</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_GeneratePDF__c.field-meta.xml
<CustomField>
    <fullName>FSM_GeneratePDF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of sfs-4083</description>
    <label>FSM_GeneratePDF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_NotificationLongText__c.field-meta.xml
<CustomField>
    <fullName>FSM_NotificationLongText__c</fullName>
    <description>created as part of sfs-8045</description>
    <label>Notification Long Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_SuspendReason__c.field-meta.xml
<CustomField>
    <fullName>FSM_SuspendReason__c</fullName>
    <description>SFI-36
Updated as part of SFI-1737</description>
    <label>Suspend Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ITES</fullName>
                <label>End of shift</label>
            </value>
            <value>
                <fullName>PLER</fullName>
                <label>Emergency/Reactive Work</label>
            </value>
            <value>
                <fullName>ITUA</fullName>
                <label>Unplanned absence</label>
            </value>
            <value>
                <fullName>ITTD</fullName>
                <label>Travel delays</label>
            </value>
            <value>
                <fullName>AVND</fullName>
                <label>No DST available</label>
            </value>
            <value>
                <fullName>CUNH</fullName>
                <label>CUSTOMER Not at home</label>
            </value>
            <value>
                <fullName>PLRC</fullName>
                <label>Requested by Customer</label>
            </value>
            <value>
                <fullName>SINL</fullName>
                <label>No access-Customer/Land owner</label>
            </value>
            <value>
                <fullName>CUNR</fullName>
                <label>Customer site not ready</label>
            </value>
            <value>
                <fullName>OTHS</fullName>
                <label>Health and safety</label>
            </value>
            <value>
                <fullName>OTAW</fullName>
                <label>Adverse weather conditions</label>
            </value>
            <value>
                <fullName>OTFT</fullName>
                <label>Incorrect Skills</label>
            </value>
            <value>
                <fullName>PLOR</fullName>
                <label>Obstruction removal required</label>
            </value>
            <value>
                <fullName>OTAS</fullName>
                <label>Dangerous situation</label>
            </value>
            <value>
                <fullName>HSED</fullName>
                <label>Engineering Difficulties</label>
            </value>
            <value>
                <fullName>HSAR</fullName>
                <label>Additional resource</label>
            </value>
            <value>
                <fullName>VEIN</fullName>
                <label>Incorrect</label>
            </value>
            <value>
                <fullName>JBFN</fullName>
                <label>Part unavailable</label>
            </value>
            <value>
                <fullName>JBTE</fullName>
                <label>Not available</label>
            </value>
            <value>
                <fullName>OTMS</fullName>
                <label>System error</label>
            </value>
            <value>
                <fullName>VEBR</fullName>
                <label>Breakdown</label>
            </value>
            <value>
                <fullName>PLFW</fullName>
                <label>Further visit/work required</label>
            </value>
            <value>
                <fullName>PRNW</fullName>
                <label>No work required</label>
            </value>
            <value>
                <fullName>SINA</fullName>
                <label>No access/Parking</label>
            </value>
            <value>
                <fullName>JBTM</fullName>
                <label>Traffic Mgnt not available</label>
            </value>
            <value>
                <fullName>PRNB</fullName>
                <label>Traffic Mgnt not booked</label>
            </value>
            <value>
                <fullName>JBDO</fullName>
                <label>Duplicate operation</label>
            </value>
            <value>
                <fullName>SIDH</fullName>
                <label>Dry hole</label>
            </value>
            <value>
                <fullName>SIWC</fullName>
                <label>Work conflict</label>
            </value>
            <value>
                <fullName>PLPD</fullName>
                <label>Permission to dig required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FSM_WorkOrderTriggerHandlerTest.cls
/********************************************************************************************************
@Author 	 : Arnob Dey
@Description : This class is used to check Case update when WorkOrder is created.
@description : Created as part of user story #SFS-318
@Main Class  : FSM_WorkOrderTriggerHandler and FSM_WorkOrderTriggerHelper
@Date        : 07-July-2023
               03-12-2024 Rijita Bose Updated as part of SFL-137
********************************************************************************************************/
@IsTest(SeeAllData=false)
public class FSM_WorkOrderTriggerHandlerTest {
/********************************************************************************************************
@Author      : Arnob Dey
@description : This method is used to create test data setup.
********************************************************************************************************/
	@TestSetup
    static void testDataSetup(){
        // Create a Test Case
        new FSM_TestDataFactory.CaseCreator().setStatus('New').setOrigin('Web').setContactName('Jon Hall').setContactEmail('jon.hall@gmail.com').create(); 
        List<OperatingHours> listOp = new List<OperatingHours>();
        OperatingHours op = new FSM_TestDataFactory.OperatingHoursCreator().setName('AM/Pm Operating Hours').setSlotType(FSM_Constants.DURATION).setBusinessUnit('Developer Services').returnWithoutCreate();
        listOp.add(op);
        op = new FSM_TestDataFactory.OperatingHoursCreator().setName('2 hours Operating Hours').setSlotType('2HRS').setBusinessUnit('Developer Services').returnWithoutCreate();
        listOp.add(op);
        insert listOp;
        
        //Create Account
        Account acc = new FSM_TestDataFactory.AccountCreator().setName('Test Account').create();
        //Create Contact
        new FSM_TestDataFactory.ContactCreator().setFirstName('FSM').setLastName('Salesforce Default Contact For Email').setAccount(acc.ID)
                        .setEmail('no-reply@defaultemail.com').create();
        
        FSL__Scheduling_Policy__c schedulingPolicy = new FSM_TestDataFactory.SchedulingPolicyCreator().setName('Test Policy').create();
        ServiceTerritory st = new FSM_TestDataFactory.ServiceTerritoryCreator().setName('Testing Territory').setIsActive(true).setExtenalId('4105WP3').setOpreratingHours2HourSlot(listOp[1].Id).setOpreratingHours(listOp[0].Id).setSchedulingPolicy(schedulingPolicy.Id).setGISLayerId('nw1').setWorkingSubAreaRequired(true).create();
        
        Case testCase = new FSM_TestDataFactory.CaseCreator().setStatus('New').setOrigin('Web').setContactName('Jon Hall').setContactEmail('jon.hall@gmail.com').setDescription('Long text info').create();        
        
        Id recTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName()
            .get(FSM_Constants.RECORDTYPE_DEVELOPERSERVICES).getRecordTypeId();
        
        // Create a test WorkOrder data
        WorkOrder wo = new FSM_TestDataFactory.WorkOrderCreator().setRecordType(recTypeId).setServiceTerritory(st.Id).
            setEsating(40.0).setNorthing(50.4).standardTextKey('83773848743').setCaseId(testCase.ID).setBusinessUnit('Developer Services').create();
            
        ID saRecordTypeID= Schema.SObjectType.ServiceAppointment.getRecordTypeInfosByDeveloperName()
            .get(FSM_Constants.RECORDTYPE_DEVELOPERSERVICES).getRecordTypeId();
        
        //ServiceAppointment sa = 
        new FSM_TestDataFactory.ServiceAppointmentCreator().setParentRecordId(wo.Id).setStatus('NEW').setRecordType(saRecordTypeID)
                .setEarliestStartTime(DateTime.Now().AddDays(-2)).setDueDate(DateTime.Now().AddDays(18)).
                setServiceTerritory(st.ID).create();
    }
    
    /********************************************************************************************************
    @Author      : Arnob Dey
    @description : This method is used to test whether Customer Information is copied from Case to WorkOrder 
                   when WorkOrder is created.
    ********************************************************************************************************/
    @IsTest
    static void testCustomerInformationUpdate(){                                        
        Case caseRec = [SELECT Id, FSM_ContactName__c, FSM_ContactEmail__c,Description FROM Case LIMIT 1]; 
        
        Test.startTest();
        //Get RecordType Id
        Id recTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName().get(FSM_Constants.RECORDTYPE_DEVELOPERSERVICES).getRecordTypeId();
        // Create a Test WorkOrder associated with the Case
        new FSM_TestDataFactory.WorkOrderCreator().setRecordType(recTypeId).setBusinessUnit('Water Infra').setCaseId(caseRec.Id).create();
        WorkOrder woRec = [SELECT Id, FSM_ContactName__c, FSM_ContactEmail__c,FSM_NotificationLongText__c FROM WorkOrder LIMIT 1];        
        Test.stopTest();
        
        // Assert the custom field value on the WorkOrder
        System.assertEquals(caseRec.FSM_ContactName__c, woRec.FSM_ContactName__c, 'ContactName information copied successfully');
        System.assertEquals(caseRec.FSM_ContactEmail__c, woRec.FSM_ContactEmail__c, 'ContactEmail information copied successfully');
        System.assertEquals(woRec.FSM_NotificationLongText__c,'Long text info', 'Description information copied successfully');
        
    }
    
    //This method is to test WorkOrder reason fields Update, Added as part of SFI-36, Srikanth palla, 17th Aug 2023
    @istest
    static void testReasonWOUpdate(){
       // WorkOrder wo = [Select id,FSM_SuspendReason__c from WorkOrder limit 1];
        ServiceAppointment sa = [Select id, FSM_SuspendReason__c from ServiceAppointment limit 1];
        test.StartTest();
            sa.FSM_SuspendCategory__c = 'Availability';
            sa.FSM_SuspendReason__c='ITES';
            update sa;
        test.StopTest();
        
        WorkOrder wo1 = [Select id,FSM_SuspendReason__c from WorkOrder];
        ServiceAppointment updatedsa = [Select id, FSM_SuspendReason__c from ServiceAppointment];
        System.assertEquals(updatedsa.FSM_SuspendReason__c,wo1.FSM_SuspendReason__c,'SA And WO reason fields should be same');
    }
     @istest
    static void testgeneratepdf(){
            Test.startTest();
        //Get RecordType Id
        Id recTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName().get(FSM_Constants.RECORDTYPE_DEVELOPERSERVICES).getRecordTypeId();
        // Create a Test WorkOrder associated with the Case
        new FSM_TestDataFactory.WorkOrderCreator().setRecordType(recTypeId).setBusinessUnit('Water Infra').setgeneratepdf(false).setpdfFilename('testpdffile').setdeviceType('Desktop').create();
        WorkOrder woRec = [SELECT Id, FSM_GeneratePDF__c FROM WorkOrder LIMIT 1]; 
        woRec.FSM_GeneratePDF__c=true;
        update woRec;
        Test.stopTest();
        
    }
    //This method is to test case updated in parend bundle WO, Added as part of SFL-132, 11th Dec 2024
    @IsTest
    static void testCasePopulationForParentBundle() {
        // Fetch WO
        WorkOrder wo = [SELECT Id, CaseId  FROM WorkOrder LIMIT 1];
        
        // Create ServiceAppointment records
        ServiceAppointment sa1 = new FSM_TestDataFactory.ServiceAppointmentCreator().setParentRecordId(wo.Id).setStatus('New').setEarliestStartTime(DateTime.Now().AddDays(-12)).setDueDate(DateTime.Now().AddDays(-5)).create();
        ServiceAppointment sa2 = new FSM_TestDataFactory.ServiceAppointmentCreator().setParentRecordId(wo.Id).setStatus('New').setEarliestStartTime(DateTime.Now().AddDays(-12)).setDueDate(DateTime.Now().AddDays(-5)).create();
        ServiceAppointment sa3 = new FSM_TestDataFactory.ServiceAppointmentCreator().setParentRecordId(wo.Id).setStatus('New').setIsBundle(true).create();
        
        Test.startTest();
    
        // Link sa1 and sa2 to sa3 (bundle)
        sa1.RelatedBundleId = sa3.Id;
        sa1.IsBundleMember = true;
        update sa1;
    
        sa2.RelatedBundleId = sa3.Id;
        sa2.IsBundleMember = true;
        update sa2;

        Test.stopTest();
        
        // Retrieve the WorkOrder record to check if the CaseId is updated as expected
        WorkOrder updatedWO = [SELECT Id, CaseId FROM WorkOrder WHERE Id = :wo.Id];
        // Assert: Check if the WorkOrder's CaseId remains unchanged
        System.assertEquals(updatedWo.CaseId, wo.CaseId, 'CaseId should remain the same');
    }
    
    @istest
    static void testmailJetFieldsReset(){
        ServiceAppointment sa = [Select id, FSM_SuspendReason__c from ServiceAppointment limit 1];
        test.StartTest();
            sa.FSM_MailJetFieldsToBeBlanked__c='FSM_FWRole__c//FSM_CustCoordinatorNumber__c//FSM_OperativeContactNumber__c//FSM_FieldworkerVynUrl__c//FSM_CustCoordinatorNumber__c//FSM_Flow__c//FSM_Pressure__c//';
            sa.FSM_MailjetFieldUpdateDateAndTime__c  = System.now().addMinutes(5);
            update sa;
        test.StopTest();
        
        
        ServiceAppointment updatedsa = [Select id, FSM_CustCoordinatorNumber__c from ServiceAppointment];
        System.assertEquals(updatedsa.FSM_CustCoordinatorNumber__c,null);
    }
}