force-app/main/default/objects/FSM_BatchClassQueries__mdt/FSM_BatchClassQueries__mdt.object-meta.xml
<CustomObject>
    <description>SFI-193</description>
    <label>Batch Class Queries</label>
    <pluralLabel>Batch Class Queries</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSM_BatchClassQueries__mdt/fields/FSM_Active__c.field-meta.xml
<CustomField>
    <fullName>FSM_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_BatchClassQueries__mdt/fields/FSM_Query__c.field-meta.xml
<CustomField>
    <fullName>FSM_Query__c</fullName>
    <label>Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FSM_IntegrationLog__c/FSM_IntegrationLog__c.object-meta.xml
<CustomObject>
    <description>Created as part of #SFS-32</description>
    <label>FSM Integration Log</label>
    <nameField>
        <displayFormat>Int-{000000}</displayFormat>
        <label>FSM Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSM Integration Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_IntegrationLog__c/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <description>External ID</description>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_IntegrationLog__c/fields/FSM_ServiceName__c.field-meta.xml
<CustomField>
    <fullName>FSM_ServiceName__c</fullName>
    <label>Service Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSM_DeleteBatchLog_Test.cls
/*------------------------------------------------------------
* @description:  A test class for FSM_DeleteBatchLog.               
* @group:        Capgemini
* ver    Date                Author             Modification
1.0    23th June 2023       Srikanth           Created class-SFI-193
------------------------------------------------------------*/
@isTest
public class FSM_DeleteBatchLog_Test {
 @isTest
    private static void execute() {
        FSM_DeleteBatchLog eraser = new FSM_DeleteBatchLog();
        eraser.listQueries = new List<FSM_BatchClassQueries__mdt>{
            new FSM_BatchClassQueries__mdt(
                FSM_Active__c = true,
                FSM_Query__c = 'SELECT Id FROM FSM_IntegrationLog__c'
            )
        };
        Test.startTest();
        Database.executeBatch(eraser);
        String schTime = '0 0 12 * * ?';
        FSM_DeleteBatchLog schedulableEraser = new FSM_DeleteBatchLog();
        system.schedule('DataEraser', schTime, schedulableEraser);
        Test.stopTest();

        System.assertEquals(0, [SELECT Id FROM FSM_IntegrationLog__c].size(),'records size will be zero');
    }

    @TestSetup
    private static void testSetup() {
        FSM_IntegrationLog__c testLog = new FSM_IntegrationLog__c(FSM_ServiceName__c='Integration Log',FSM_ExternalId__c='3323'
        );
        insert testLog;
        System.assertEquals('Integration Log',testLog.FSM_ServiceName__c,'Log name');
    }

}