force-app/main/default/objects/FSM_BatchClassQueries__mdt/FSM_BatchClassQueries__mdt.object-meta.xml
<CustomObject>
    <description>SFI-193</description>
    <label>Batch Class Queries</label>
    <pluralLabel>Batch Class Queries</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSM_BatchClassQueries__mdt/fields/FSM_Active__c.field-meta.xml
<CustomField>
    <fullName>FSM_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_BatchClassQueries__mdt/fields/FSM_Query__c.field-meta.xml
<CustomField>
    <fullName>FSM_Query__c</fullName>
    <label>Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FSM_BatchClassQueries__mdt/fields/FSM_SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_BatchClassQueries__mdt/fields/FSM_Type__c.field-meta.xml
<CustomField>
    <fullName>FSM_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delete</fullName>
                <default>true</default>
                <label>Delete</label>
            </value>
            <value>
                <fullName>Insert</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FSM_DeleteBatchLog.cls
/*------------------------------------------------------------
* @description:  A test class created to delete Integration and Error log records.               
* @group      :  Capgemini
* Test Class  :  FSM_DeleteBatchLog_Test
* ver    Date                Author             Modification
1.0    23th June 2023       Srikanth           Created-SFI-193
------------------------------------------------------------*/
global class FSM_DeleteBatchLog implements Database.Batchable<sObject>,System.Schedulable{
private integer queryIndex;
@TestVisible
/**
 * @description to get queries listQueries
 */
    public List<FSM_BatchClassQueries__mdt> listQueries {
        get {
            if (listQueries == null) {
                this.listQueries = [
                    SELECT FSM_Query__c
                    FROM FSM_BatchClassQueries__mdt
                    WHERE FSM_Active__c = true AND FSM_Type__c='Delete'  WITH SECURITY_ENFORCED ORDER BY FSM_SequenceNumber__c];
            }

            return listQueries;
        }
        private set;
    }
    
/**
 * @description FSM_DeleteBatchLog 
 */
    global FSM_DeleteBatchLog(){
        this.queryIndex = 0;
    }
/**
 * @description runBatch method
 */
    global void runBatch(){
        if(this.queryIndex < this.listQueries.size()){
            Database.executeBatch(this, 200);
        }
    }
/**
 * @description execute method
 * @param sc
 */
    global void execute(SchedulableContext sc){
        runBatch();
    }
/**
 * @description Start method
 * @param bc
 * @return Database.QueryLocator
 */
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(listQueries[queryIndex].FSM_Query__c);
    }
/**
 * @description execute method
 * @param bc
 * @param lst
 */
    global void execute(Database.BatchableContext bc, List<sObject> lst){

           delete lst;

    }
/**
 * @description finish method
 * @param bc
 */
    global void finish(Database.BatchableContext bc){
        this.queryIndex++;
        runBatch();
    }

}