force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/FSM_DCFConfigurationWorkStep__mdt.object-meta.xml
<CustomObject>
    <description>Created as a part of SFS-1298.

Metadata holds the configurations necessary for auto-creating work steps in Field Service Lightning (FSL). When a work order (WO) is created, these configurations are matched against several criteria, including Service Territory, Standard Text Key, Minimum Crew Size, Suitability, and Business Units. If the criteria match, the corresponding metadata records are used to generate the work steps for the WO.

Note: A Standard Text Key value of * indicates that the metadata record should be considered for any standard text key on the WO.

Updated for SFS-1298</description>
    <label>DCF Configuration - Work Step</label>
    <pluralLabel>DCF Configuration - Work Steps</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <description>Business Unit</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waste Infra</fullName>
                <default>true</default>
                <label>Waste Infra</label>
            </value>
            <value>
                <fullName>Waste Non Infra</fullName>
            </value>
            <value>
                <fullName>Water Infra</fullName>
            </value>
            <value>
                <fullName>Water Non Infra</fullName>
            </value>
            <value>
                <fullName>Bio Resource</fullName>
            </value>
            <value>
                <fullName>Developer Services</fullName>
            </value>
            <value>
                <fullName>Metering</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_MaxInstance__c.field-meta.xml
<CustomField>
    <fullName>FSM_MaxInstance__c</fullName>
    <description>SFS-6573. Maximum number of completed forms permitted Work Step. When DCF flow is launched it first checks for completed forms against this number.</description>
    <inlineHelpText>Maximum number of completed forms permitted under a Work Step.</inlineHelpText>
    <label>Max Instance</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_Suitability__c.field-meta.xml
<CustomField>
    <fullName>FSM_Suitability__c</fullName>
    <description>This Field is used for storing configuration details of Suitability for E-Forms Creation. Created as a part of SFS-1298.</description>
    <label>Suitability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <default>true</default>
                <label>E</label>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>*</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_WorkStepName__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkStepName__c</fullName>
    <description>Created for SFS-4072.</description>
    <label>Work Step Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <description>SFS-110</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waste Infra</fullName>
            </value>
            <value>
                <fullName>Water Infra</fullName>
            </value>
            <value>
                <fullName>Water Non Infra</fullName>
            </value>
            <value>
                <fullName>Waste Non Infra</fullName>
            </value>
            <value>
                <fullName>Bio Resource</fullName>
            </value>
            <value>
                <fullName>Developer Services</fullName>
            </value>
            <value>
                <fullName>Metering</fullName>
            </value>
            <value>
                <fullName>Green Recovery</fullName>
            </value>
            <value>
                <fullName>WasteNon Infra</fullName>
                <isActive>false</isActive>
                <label>WasteNon Infra</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_StandardTextKey__c.field-meta.xml
<CustomField>
    <fullName>FSM_StandardTextKey__c</fullName>
    <label>Standard Text Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_Suitability__c.field-meta.xml
<CustomField>
    <fullName>FSM_Suitability__c</fullName>
    <description>Created as a part of SFS-1298.(E = Excavation ,C = Covers ,R = Reinstatement ,D = Defect)
Updated as part of SFI-1616</description>
    <label>Suitability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>Excavation</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cover</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Reinstatement</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Defective Reinstatement Repair</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No notice required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkStep/fields/FSM_MaxInstance__c.field-meta.xml
<CustomField>
    <fullName>FSM_MaxInstance__c</fullName>
    <description>Created as part of SFS-6573. Maximum number of completed forms permitted Work Step. When DCF flow is launched it first checks for completed forms against this number.</description>
    <inlineHelpText>Maximum number of completed forms permitted under this workstep.</inlineHelpText>
    <label>Max Instance</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Waste Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Waste Non Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Water Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Water Non Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Bio Resource</fullName>
    </customValue>
    <customValue>
        <fullName>Developer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Metering</fullName>
    </customValue>
    <customValue>
        <fullName>Green Recovery</fullName>
        <isActive>false</isActive>
        <label>Green Recovery</label>
    </customValue>
    <description>STW Business Unit</description>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSM_InvocableDcfConfiguration_Test.cls
/****************************************************************************************************************************
@Author : Leena Bheemarasetty
@Date   : 8th August 2023
@Description : This class is used to test the if Forms names are available ot not according to the WorkStep Configurations 
               of Main Class which will be called from a sub Flow
@Description : Created as part of user story #SFS-1298
@Main Class : FSM_InvocableDcfConfiguration  
==============================================================================================================================
*/
@isTest (SeeAlldata = false)
public class FSM_InvocableDcfConfiguration_Test {

/*--------------------------------------------------------------
@Author      : Leena Bheemarasetty
@Description : This method is used to create test data setup.
-----------------------------------------------------------------*/
    @TestSetup
    static void testDataSetup(){
        List<OperatingHours> listOp = new List<OperatingHours>();
        OperatingHours op = new FSM_TestDataFactory.OperatingHoursCreator().setName('AM/Pm Operating Hours').setSlotType(FSM_Constants.DURATION).setBusinessUnit('Metering').create();
     
        ServiceTerritory se = new FSM_TestDataFactory.ServiceTerritoryCreator().setName('6302M03 Central').setBusinessUnit('Metering').setIsActive(true).setExtenalId('888999')
            .setOpreratingHours(op.Id).create();
        
        ServiceTerritory stWaste = new FSM_TestDataFactory.ServiceTerritoryCreator().setName('4106WP3 Derby-Res-Bstrs').setBusinessUnit('Waste Non Infra').setIsActive(true).setExtenalId('8889991')
            .setOpreratingHours(op.Id).create();
        
    }
    
/*-----------------------------------------------------------------------------------------------------------------
@Author      : Leena Bheemarasetty
@Description : This method is used to test whether FormNames are present or not for the WorkOrder According to the 
               configurations set in MetaData.
-------------------------------------------------------------------------------------------------------------------*/
    @IsTest
    static void testGetFormNames(){  
        test.startTest();
        ServiceTerritory st=[Select Id,Name from ServiceTerritory where FSM_BusinessUnit__c = 'Metering'];
        Id rtId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName()
                             .get(FSM_Constants.RECORDTYPE_METERING).getRecordTypeId();
        // Create a test WorkOrder data
        WorkOrder wo = new FSM_TestDataFactory.WorkOrderCreator().setRecordType(rtId).setBusinessUnit('Metering').setServiceTerritory(st.Id).standardTextKey('SVO').returnWithoutCreate(); 
        INSERT wo;
        //Fetching  the created record
        WorkOrder wo1=[Select Id,ServiceTerritoryId,FSM_StandardTextKey__c,FSM_Suitability__c,MinimumCrewSize, FSM_BusinessUnit__c from WorkOrder];
        //Creating parameters for Invocable Method
        FSM_InvocableDcfConfiguration.InputParams conditions = new FSM_InvocableDcfConfiguration.InputParams();
        conditions.minimumCrewSize=wo1.MinimumCrewSize;
        conditions.serviceTerritory=st.Name;
        conditions.standardTextKey=wo1.FSM_StandardTextKey__c;
        conditions.suitability=wo1.FSM_Suitability__c;
        conditions.workorderId=wo1.Id;
        conditions.businessUnit=wo1.FSM_BusinessUnit__c;
        
        //Calling the Invocable Method
        List<List<FSM_DCFConfigurationWorkStep__mdt>> formList= FSM_InvocableDcfConfiguration.getFormNames(new List<FSM_InvocableDcfConfiguration.InputParams> {conditions});
        test.stopTest();
        
        List<FSM_DCFConfigurationWorkStep__mdt> configs = formList[0];
        System.assert(configs.isEmpty() == false, 'No forms returned.');
        
    }
    
    @IsTest
    static void dedupeCheck(){  
        
        OperatingHours op = [SELECT Id FROM OperatingHours WHERE Name = 'AM/Pm Operating Hours'];
        
        ServiceTerritory st = new FSM_TestDataFactory.ServiceTerritoryCreator()
            .setName('1301WD2 Leak Warwickshire')
            .setBusinessUnit('Water Infra')
            .setIsActive(true).setExtenalId('889999')
            .setOpreratingHours(op.Id)
            .create();
        
        test.startTest();
        
        Id rtId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName()
                             .get(FSM_Constants.RECORDTYPE_METERING).getRecordTypeId();
        // Create a test WorkOrder data
        WorkOrder wo = new FSM_TestDataFactory.WorkOrderCreator().setRecordType(rtId).setBusinessUnit('Water Infra').setServiceTerritory(st.Id).standardTextKey('SVOF').create(); 
        //Fetching  the created record
        WorkOrder wo1=[Select Id,ServiceTerritoryId,FSM_StandardTextKey__c,FSM_Suitability__c,MinimumCrewSize, FSM_BusinessUnit__c from WorkOrder];
        //Creating parameters for Invocable Method
        FSM_InvocableDcfConfiguration.InputParams conditions = new FSM_InvocableDcfConfiguration.InputParams();
        conditions.minimumCrewSize=wo1.MinimumCrewSize;
        conditions.serviceTerritory=st.Name;
        conditions.standardTextKey=wo1.FSM_StandardTextKey__c;
        conditions.suitability=wo1.FSM_Suitability__c;
        conditions.workorderId=wo1.Id;
        conditions.businessUnit=wo1.FSM_BusinessUnit__c;
        
        //Calling the Invocable Method
        List<List<FSM_DCFConfigurationWorkStep__mdt>> formList= FSM_InvocableDcfConfiguration.getFormNames(new List<FSM_InvocableDcfConfiguration.InputParams> {conditions});
        test.stopTest();
        
        //asserting there are no duplicates returned.
        Boolean hasDuplicate = false;
        Set<String> uniqueWorkSteps = new Set<String>();
        
        for(FSM_DCFConfigurationWorkStep__mdt  config: formList[0]){
            String workstepName = config.FSM_WorkStepName__c;
            if(!uniqueWorkSteps.contains(workstepName)){
                uniqueWorkSteps.add(workstepName);
            } else{
                hasDuplicate = true;
            }
        }
        
        
        WorkPlan wp=new FSM_TestDataFactory.WorkPlanCreator().setName('Developer Services').setparent(wo.Id).setWorkorder(wo.Id).create();
        
        Workstep workstep = new FSM_TestDataFactory.WorkStepCreator().setName('Boards & Barriers').setActionDef('WorkStep.FSM_BoardsAndBarriers').setWorkPlan(wp.Id).setStatus('New').returnWithoutCreate();
        workstep.FSM_MaxInstance__c = 2;
        INSERT workstep;
        
        
        Boolean hasWorkStepReached = FSM_InvocableDcfConfiguration.hasDCFLimitReached(workstep.Id);
        
        System.assertEquals(false, hasWorkStepReached, 'Max Instance Check failed.');
        
    }

    @IsTest
    static void testNonInfraBU(){  
        test.startTest();
        ServiceTerritory st=[Select Id,Name from ServiceTerritory where FSM_BusinessUnit__c = 'Waste Non Infra'];
        Id rtId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName()
                             .get(FSM_Constants.RECORDTYPE_WASTENONINFRA).getRecordTypeId();
        // Create a test WorkOrder data
        WorkOrder wo = new FSM_TestDataFactory.WorkOrderCreator().setRecordType(rtId).setBusinessUnit('Waste Non Infra').setServiceTerritory(st.Id).standardTextKey('WPASC1').returnWithoutCreate(); 
        INSERT wo;
        //Fetching  the created record
        WorkOrder wo1=[Select Id,ServiceTerritoryId,FSM_StandardTextKey__c,FSM_Suitability__c,MinimumCrewSize, FSM_BusinessUnit__c from WorkOrder];
        //Creating parameters for Invocable Method
        FSM_InvocableDcfConfiguration.InputParams conditions = new FSM_InvocableDcfConfiguration.InputParams();
        conditions.minimumCrewSize=wo1.MinimumCrewSize;
        conditions.serviceTerritory=st.Name;
        conditions.standardTextKey=wo1.FSM_StandardTextKey__c;
        conditions.suitability=wo1.FSM_Suitability__c;
        conditions.workorderId=wo1.Id;
        conditions.businessUnit=wo1.FSM_BusinessUnit__c;
        
        //Calling the Invocable Method
        List<List<FSM_DCFConfigurationWorkStep__mdt>> formList= FSM_InvocableDcfConfiguration.getFormNames(new List<FSM_InvocableDcfConfiguration.InputParams> {conditions});
        test.stopTest();
        List<FSM_DCFConfigurationWorkStep__mdt> configs=new List<FSM_DCFConfigurationWorkStep__mdt>();
        if(formList!=null && !formList.isEmpty()){
        	configs = formList[0];
        }
        System.assert(configs.isEmpty() == true, 'Forms returned.');
        
    }
}