force-app/main/default/objects/FSM_ErrorLog__c/FSM_ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Created as part of #SFS-32</description>
    <label>FSM Error Log</label>
    <nameField>
        <displayFormat>Err-{000000}</displayFormat>
        <label>FSM Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSM Error Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_TMAPermit__c/FSM_TMAPermit__c.object-meta.xml
<CustomObject>
    <description>Created as part of user story #SFS-32</description>
    <label>TMA</label>
    <nameField>
        <displayFormat>TMAPER-{000000}</displayFormat>
        <label>TMA Permit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_TMAPermit__c/fields/FSM_EventType__c.field-meta.xml
<CustomField>
    <fullName>FSM_EventType__c</fullName>
    <description>sfi-1614</description>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0200</fullName>
                <label>Initial Notice</label>
            </value>
            <value>
                <fullName>0210</fullName>
                <label>PAA / Permit</label>
            </value>
            <value>
                <fullName>0300</fullName>
                <label>Activity Confirmation Notice</label>
            </value>
            <value>
                <fullName>0310</fullName>
                <label>Permit Application</label>
            </value>
            <value>
                <fullName>0400</fullName>
                <label>Actual Start Notice</label>
            </value>
            <value>
                <fullName>0600</fullName>
                <label>Work Stop Notice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_TMAPermit__c/fields/FSM_HighwayAuthority__c.field-meta.xml
<CustomField>
    <fullName>FSM_HighwayAuthority__c</fullName>
    <label>Highway Authority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Highway_authority</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_TMAPermit__c/fields/FSM_InitialNoticesenttoSAP__c.field-meta.xml
<CustomField>
    <fullName>FSM_InitialNoticesenttoSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Initial Notice sent to SAP?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_TMAPermit__c/fields/FSM_NoticeDate__c.field-meta.xml
<CustomField>
    <fullName>FSM_NoticeDate__c</fullName>
    <description>Field type changed as a part of SFS-4133
Label updated as a part of SFS-4792
Date the TMAtrigger is due to be sent to the middleware (INT-008)</description>
    <label>Noticeable Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FSM_TMAPermit__c/fields/FSM_NoticeType__c.field-meta.xml
<CustomField>
    <fullName>FSM_NoticeType__c</fullName>
    <description>Type of a notice that is related to the operation
Created as part of user story #SFS-32
Category of the permit/notice required (ie. Minor, Major, etc.) based on legislation.</description>
    <label>Works Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Works_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_TMAPermit__c/fields/FSM_ScheduledStartDate__c.field-meta.xml
<CustomField>
    <fullName>FSM_ScheduledStartDate__c</fullName>
    <description>sfi-1807</description>
    <label>Scheduled Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FSM_TMAPermit__c/fields/FSM_WorkOrderRefID__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkOrderRefID__c</fullName>
    <description>sfi-1807</description>
    <label>WorkOrderRefID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_TMAPermitNoticePeriods__c/FSM_TMAPermitNoticePeriods__c.object-meta.xml
<CustomObject>
    <label>TMA Permit Notice Period</label>
    <nameField>
        <displayFormat>NP-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMA Permit Notice Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_TMAPermitNoticePeriods__c/fields/FSM_HighwayAuthority__c.field-meta.xml
<CustomField>
    <fullName>FSM_HighwayAuthority__c</fullName>
    <description>created as part of sfs-4791</description>
    <label>Highway Authority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Highway_authority</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_TMAPermitNoticePeriods__c/fields/FSM_NoticePeriod__c.field-meta.xml
<CustomField>
    <fullName>FSM_NoticePeriod__c</fullName>
    <label>Notice Period</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_TMAPermitNoticePeriods__c/fields/FSM_WorksCategory__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorksCategory__c</fullName>
    <description>created as part of sfs-4791</description>
    <label>Works Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Works_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_CoreTMAJob__c.field-meta.xml
<CustomField>
    <fullName>FSM_CoreTMAJob__c</fullName>
    <description>Indicates if job is  a Core TMA Job . Created as part of SFS-8678</description>
    <formula>FSSK__FSK_Work_Order__r.FSM_CoreTMAJob__c</formula>
    <label>Core TMA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_ScheduledStartDate__c.field-meta.xml
<CustomField>
    <fullName>FSM_ScheduledStartDate__c</fullName>
    <description>SFS-6638</description>
    <formula>DATEVALUE(SchedStartTime)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scheduled Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSSK__FSK_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>FSSK__FSK_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>FSK_Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_CoreTMAJob__c.field-meta.xml
<CustomField>
    <fullName>FSM_CoreTMAJob__c</fullName>
    <description>SFS-6658</description>
    <formula>AND(
  NOT(ISBLANK(FSM_TMAPermit__c)),
  OR(
    NOT(ISBLANK(TEXT(FSM_NoticeState__c))),  
    ISPICKVAL(FSM_Suitability__c, &quot;E&quot;)      
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Core TMA Job</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_TMAPermit__c.field-meta.xml
<CustomField>
    <fullName>FSM_TMAPermit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TMA Permit</label>
    <referenceTo>FSM_TMAPermit__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Works_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Major</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Minor</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Immediate - Emergency</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Immediate - Urgent</label>
    </customValue>
    <customValue>
        <fullName>00</fullName>
        <label>No Notice Required</label>
    </customValue>
    <customValue>
        <fullName>Immediate</fullName>
        <isActive>false</isActive>
        <label>Immediate</label>
    </customValue>
    <customValue>
        <fullName>Emergency -TBU</fullName>
        <isActive>false</isActive>
        <label>Emergency -TBU</label>
    </customValue>
    <masterLabel>Works_Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSM_updatenoticedate.cls
/*===========================================================================================================================
@Author      : Aishwarya Bhosale
@Description : This Class is used to calculate Notice Date on TMA Permit.
@Description : Created as part of user story #SFS-1833
@Test Class  : FSM_updatenoticedateTest
@Date        : 10th August 2023
==============================================================================================================================*/
public with sharing class FSM_updatenoticedate{
    //invocable method to calculate notice date considering all holidays and weekends
    @InvocableMethod(label='Calculate Notice Date')
    public static void calculateNoticeDateonPermit(List<Serviceappoitments> sAid){
        
        List<List<FSM_TMAPermit__c>> outputList = new List<List<FSM_TMAPermit__c>>();
        List<FSM_TMAPermit__c> tempList = new List<FSM_TMAPermit__c>();
        DateTime scheduledstartdatetoupdate;
        List<Id> saIds = new List<Id>();
        Map<Id, String> permitWithEventMap = new Map<Id, String>();
        try{
        for(Integer i=0;i<sAid.size();i++){
            saIds.add(sAid.get(i).serviceapptid);
            //map to update event type on tma permit
            permitWithEventMap.put( sAid.get(i).tmaid , sAid.get(i).eventtype);
        }
        
        //Get master notice periods
        Map<String, Decimal> noticePeriodMap = new Map<String, Decimal>();
        for(FSM_TMAPermitNoticePeriods__c tmaNp: [Select Id, FSM_HighwayAuthority__c, FSM_WorksCategory__c, FSM_NoticePeriod__c from FSM_TMAPermitNoticePeriods__c with security_enforced Limit 200]){
            noticePeriodMap.put( tmaNp.FSM_HighwayAuthority__c + tmaNp.FSM_WorksCategory__c,  tmaNp.FSM_NoticePeriod__c);
            
        }
        
        //TMA and its notice period
        Map<Id, Decimal> tmaNoticeMap = new Map<Id, Decimal>();
        Map<Id, Datetime> tmaNoticeDateMap = new Map<Id, Datetime>();
        Set<Id> permitIds = new Set<Id>();
        Map<Id, String> permitWithWOMap = new Map<Id, String>();
        for(ServiceAppointment sa: [Select Id, FSSK__FSK_Work_Order__r.FSM_TMAPermit__c, FSSK__FSK_Work_Order__r.FSM_TMAPermit__r.FSM_HighwayAuthority__c,
                                           FSSK__FSK_Work_Order__r.FSM_TMAPermit__r.FSM_NoticeType__c from ServiceAppointment where Id IN:saIds with security_enforced]){
                                           
            String authCode = sa.FSSK__FSK_Work_Order__r.FSM_TMAPermit__r.FSM_HighwayAuthority__c;
            system.debug('authCode---------------->'+authCode);
            String workCat = sa.FSSK__FSK_Work_Order__r.FSM_TMAPermit__r.FSM_NoticeType__c;
              system.debug('workCat---------------->'+workCat);
            if(noticePeriodMap.containsKey( authCode + workCat)){
                tmaNoticeMap.put(sa.FSSK__FSK_Work_Order__r.FSM_TMAPermit__c, noticePeriodMap.get( authCode + workCat ) );
                
            }
            system.debug('tmaNoticeMap--------------->'+tmaNoticeMap);
            permitIds.add(sa.FSSK__FSK_Work_Order__r.FSM_TMAPermit__c);
            permitWithWOMap.put(sa.FSSK__FSK_Work_Order__r.FSM_TMAPermit__c, sa.FSSK__FSK_Work_Order__c);
        }
        //find SA having same permit
        List<AggregateResult> aggrRes = [Select FSSK__FSK_Work_Order__r.FSM_TMAPermit__c permitId, MIN(SchedStartTime) schedTime from ServiceAppointment 
                                                 where Status NOT IN ('New','Rejected','Cancelled') AND FSSK__FSK_Work_Order__r.FSM_TMAPermit__c <> Null 
                                                 AND FSSK__FSK_Work_Order__r.FSM_TMAPermit__c IN: permitIds AND SchedStartTime <> Null 
                                                 AND FSSK__FSK_Work_Order__r.FSM_TMAPermit__r.FSM_InitialNoticesenttoSAP__c = false  
                                         		 AND FSSK__FSK_Work_Order__r.FSM_CoreTMAJob__c=true with Security_Enforced 
                                                 group by FSSK__FSK_Work_Order__r.FSM_TMAPermit__c ];
        system.debug('aggr----------->'+aggrRes.size());
        BusinessHours bh = [SELECT Id From BusinessHours WHERE IsDefault=true with Security_Enforced];
        Map<String, DateTime> permitWithDates = new Map<String, DateTime>();
        Set<String> permitCheck = new Set<String>();
        for(AggregateResult aggr: aggrRes ){
            system.debug('inside aggr');
            String permitRecId = (String) aggr.get('permitId');
            system.debug('permitRecId------------------>'+permitRecId);
            permitCheck.add(permitRecId);
            DateTime scheduledstartdate = (DateTime) aggr.get('schedTime');
            scheduledstartdatetoupdate=scheduledstartdate;
            if(tmaNoticeMap.containsKey(permitRecId) ){
                
                Date noticeDateToUpdate = null;
                Decimal noticeperiodtosub = tmaNoticeMap.get(permitRecId);
                Integer elapsed = 0;
                Integer cnt = 0;
                while (elapsed < noticeperiodtosub)
                {
                    system.debug('4444444444444444444');
                    cnt ++;
                    scheduledstartdate = scheduledstartdate.addDays(-1);
                    if (BusinessHours.isWithin(bh.Id, scheduledstartdate)) 
                    {
                        system.debug('5555555555555');
                        elapsed++;
                    }else {
                        continue;
                        system.debug('do nothing');
                    }
                    
                }
                
                if(cnt > 0){
                    system.debug('11111111111111111111111');
                    noticeDateToUpdate = scheduledstartdate.date(); 
                     FSM_TMAPermit__c outputPermit = new FSM_TMAPermit__c();
                     outputPermit.Id = permitRecId;
                     outputPermit.FSM_NoticeDate__c = noticeDateToUpdate;
                     outputPermit.FSM_ScheduledStartDate__c = scheduledstartdatetoupdate; 
                     outputPermit.FSM_EventType__c = permitWithEventMap.get(permitRecId);
                     outputPermit.FSM_WorkOrderRefID__c = permitWithWOMap.get(permitRecId);
                    system.debug('outputPermit---------------------->'+outputPermit);
                     tempList.add(outputPermit); 
                }
            }
        }
        
        for(String pmt: permitIds ){
            system.debug('inside emptys');
            if(!permitCheck.contains(pmt)){
                system.debug('permitCheck------------>');
             FSM_TMAPermit__c outputPermit = new FSM_TMAPermit__c();
             outputPermit.Id = pmt;
             outputPermit.FSM_NoticeDate__c = null;
             outputPermit.FSM_ScheduledStartDate__c = null;
             outputPermit.FSM_EventType__c = null;
             outputPermit.FSM_WorkOrderRefID__c = null;
             tempList.add(outputPermit); 
           }
        }
        
        if(tempList.size() > 0){
            system.debug('333333333333333');
                if (Schema.sObjectType.FSM_TMAPermit__c.isUpdateable()){
                database.update(tempList);
                }
               outputList.add(tempList); 
            }
	  }catch(Exception ex){
          system.debug('666666666666666666');
            //Creating an error log if exception occoured
            FSM_ErrorLog__c testerrorlog = new FSM_Utility.ErrorLogCreator().setClassName('FSM_updatenoticedate').setErrorMessage(ex.getMessage()).setLineNumber(string.valueof(ex.getLineNumber())).setMethodName('calculateNoticeDateonPermit').setStackTrace(ex.getStackTraceString()).create();  
      }      
    }
    public class Serviceappoitments{
        @InvocableVariable
        public DateTime schedulestart;
        @InvocableVariable
        public Decimal noticeperiod;
        @InvocableVariable
        public String tmaid;
        @InvocableVariable
        public String serviceapptid;
        @InvocableVariable
        public String eventtype;
        
    }
    
    
}