force-app/main/default/objects/FSM_ErrorLog__c/FSM_ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Created as part of #SFS-32</description>
    <label>FSM Error Log</label>
    <nameField>
        <displayFormat>Err-{000000}</displayFormat>
        <label>FSM Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSM Error Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceAppointment/fields/FSM_Backlog__c.field-meta.xml
<CustomField>
    <fullName>FSM_Backlog__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as a part of SFS-3043</description>
    <label>Backlog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_BacklogScore__c.field-meta.xml
<CustomField>
    <fullName>FSM_BacklogScore__c</fullName>
    <formula>IF((  FSM_DueDateApplyCounterZPM1__c   * 2)&lt;=6,FSM_DueDateApplyCounterZPM1__c * 2,6)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Backlog Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <description>SFS-155</description>
    <formula>TEXT(FSSK__FSK_Work_Order__r.FSM_BusinessUnit__c)</formula>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_DueDateApplyCounter__c.field-meta.xml
<CustomField>
    <fullName>FSM_DueDateApplyCounter__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Created as a part of SFS-3043</description>
    <label>Due Date Apply Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_DueDateApplyCounterZPM1__c.field-meta.xml
<CustomField>
    <fullName>FSM_DueDateApplyCounterZPM1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SFS-3028</description>
    <label>Due Date Apply Counter ZPM1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_HoursUntilDueDate__c.field-meta.xml
<CustomField>
    <fullName>FSM_HoursUntilDueDate__c</fullName>
    <formula>(DueDate-NOW())*24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hours Until Due Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_InternalSLA__c.field-meta.xml
<CustomField>
    <fullName>FSM_InternalSLA__c</fullName>
    <description>SFS-3043</description>
    <formula>(DATEVALUE(DueDate)- DATEVALUE(EarliestStartTime))</formula>
    <label>Internal SLA (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_SAPJobPriority__c.field-meta.xml
<CustomField>
    <fullName>FSM_SAPJobPriority__c</fullName>
    <description>SFS-238</description>
    <formula>IF(
    AND(
        OR(
            FSM_BusinessUnit__c  = &quot;Waste Non Infra&quot;,
            FSM_BusinessUnit__c  = &quot;Water Non Infra&quot;
        ),
        NOT(ISBLANK(FSM_Polygon__c )),VALUE(TEXT( FSSK__FSK_Work_Order__r.Priority))&gt;=3
    ),3,VALUE(TEXT( FSSK__FSK_Work_Order__r.Priority))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Job Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_ServiceOrderType__c.field-meta.xml
<CustomField>
    <fullName>FSM_ServiceOrderType__c</fullName>
    <description>Created as a part of SFS-292</description>
    <formula>FSSK__FSK_Work_Order__r.FSM_ServiceOrderType__c</formula>
    <label>Service Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waste Infra</fullName>
            </value>
            <value>
                <fullName>Water Infra</fullName>
            </value>
            <value>
                <fullName>Water Non Infra</fullName>
            </value>
            <value>
                <fullName>Waste Non Infra</fullName>
            </value>
            <value>
                <fullName>Bio Resource</fullName>
            </value>
            <value>
                <fullName>Developer Services</fullName>
            </value>
            <value>
                <fullName>Metering</fullName>
            </value>
            <value>
                <fullName>Green Recovery</fullName>
            </value>
            <value>
                <fullName>WasteNon Infra</fullName>
                <isActive>false</isActive>
                <label>WasteNon Infra</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FSM_BacklogMaintenanceBatch.cls
/********************************************************************************************************
@Author      : Manish Jagnani and Kaustav Chanda
@description : This class contains actual logic of a batch job to perform Backlog service appointment
@description : Created as part of user story #SFS-3028 & SFS-3043
@description : Updated as part of SFL-347 to move the query logic to Apex 18th March 2025 by Subir Maji
@description : Invoked from FSM_BacklogMaintenanceNonInfraScheduleJob scheduled trigger flow
@Test Class  : FSM_BacklogMaintenanceBatchTest
@Date        : 27-December-2023
********************************************************************************************************/
public with sharing class FSM_BacklogMaintenanceBatch implements Database.Batchable<sObject>,Schedulable{
    private String jobRunQuery;
    
    /**
    * @description constructor
    * @param saUpdatedList
    */
    public FSM_BacklogMaintenanceBatch(){} //Updated as part of SFL-347 18th March 2025 by Subir Maji
    
     /***
    * @description saListInput to invoke from Flow
    * @param void
    * Updated as part of SFL-347 18th March 2025 by Subir Maji
    */
    @InvocableMethod(label = 'BacklogMaintenance')
    public static void saListInput(){
        Id jobId = Database.executeBatch(new FSM_BacklogMaintenanceBatch());
    }
    
    /**
    *@description start
    * @param bc
    * @return Database.QueryLocator
    */
    public Database.QueryLocator start(Database.BatchableContext bc){
        List<String> saStatus = new List<String>{'New'}; //Added as part of SFL-347 18th March 2025 by Subir Maji
		List<String> servOrderType = new List<String>{'ZPM1','ZPM2'}; //added as part of SFL-347 18th March 2025 by Subir Maji
		List<String> businessUnit = new List<String>{'Waste Non Infra','Water Non Infra', 'Bio Resource'}; //Added as part of SFL-347 18th March 2025 by Subir Maji
		
		if(jobRunQuery == null){
            //Updated as part of SFL-347 18th March 2025 by Subir Maji
            jobRunQuery = 'SELECT Id, Status, FSM_ServiceOrderType__c, FSM_Backlog__c, FSM_HoursUntilDueDate__c,'+ 
                'FSM_DueDateApplyCounter__c, FSM_DueDateApplyCounterZPM1__c, FSM_SAPJobPriority__c, FSM_BacklogScore__c,'+
                ' FSM_InternalSLA__c, DueDate, EarliestStartTime '+
                'FROM ServiceAppointment '+
                'WHERE Status IN: saStatus AND '+
                'FSM_ServiceOrderType__c IN : servOrderType AND '+
                'FSM_Backlog__c = false AND '+
                'FSM_BusinessUnit__c IN : businessUnit WITH SECURITY_ENFORCED';
        }
        return Database.getQueryLocator(jobRunQuery);
    }
    
    /**
    *@description execute
    * @param bc, saList
    * @return void
    */
    public void execute(Database.BatchableContext bc, List<ServiceAppointment> saList){
        
        //declaring an empty SA List
        List<ServiceAppointment> saNewList = new List<ServiceAppointment>();
        ServiceAppointment saReturn;
        for(ServiceAppointment sa: saList){
            //ZPM2
            if(sa.FSM_ServiceOrderType__c == 'ZPM2'){
                saReturn=zpm2(sa);
            }
            //ZPM1 
            else if(sa.FSM_ServiceOrderType__c == 'ZPM1'){
                saReturn=zpm1(sa);
            }
            saNewList.add(saReturn);
        }
        if(saNewList.Size() > 0){
            databaseSaveResult(saNewList);
        }
    }
    
    /**
    * @description finish 
    * @param context
    */
    public void finish(Database.BatchableContext context) {}
    
    /**
    * @description zpm2
    * @param sa
    * @return ServiceAppointment
    */
    Private static ServiceAppointment zpm2(ServiceAppointment sa){
        //criteria-1
        if(sa.FSM_InternalSLA__c >= 28 && sa.FSM_HoursUntilDueDate__c <= 23){
            sa.FSM_Backlog__c = TRUE;
        }
        //criteria-2 & 2.1
        if(sa.FSM_InternalSLA__c >= 5 && sa.FSM_InternalSLA__c < 28 && 
           sa.FSM_HoursUntilDueDate__c <= 23){
               if(sa.FSM_DueDateApplyCounter__c == 1){
                   sa.FSM_Backlog__c = TRUE;
               }else{
                   sa.DueDate=sa.DueDate+7;
                   sa.FSM_DueDateApplyCounter__c = sa.FSM_DueDateApplyCounter__c + 1;
               }
           }
        //criteria-3 & criteria-3.1
        if(sa.FSM_InternalSLA__c >= 3 && sa.FSM_InternalSLA__c <= 4 && 
           sa.FSM_HoursUntilDueDate__c <= 23){
               if(sa.FSM_DueDateApplyCounter__c == 1){
                   sa.FSM_Backlog__c = TRUE;
               }else{
                   sa.DueDate=sa.DueDate+7;
                   sa.FSM_DueDateApplyCounter__c = sa.FSM_DueDateApplyCounter__c + 1;
               } 
           }
        //criteria-4
        if(sa.FSM_InternalSLA__c == 1 && sa.FSM_HoursUntilDueDate__c <= 23){
            sa.FSM_Backlog__c = TRUE;
        }
        return sa;
    }
    
    /**
    * @description zpm1
    * @param sa
    * @return ServiceAppointment
    */ 
    Private static ServiceAppointment zpm1(ServiceAppointment sa){
        //Scenario 1
        scenarioOne(sa);
        
        //Scenario 2
        if((sa.FSM_SAPJobPriority__c==5||sa.FSM_SAPJobPriority__c==6||
            sa.FSM_SAPJobPriority__c==7 || sa.FSM_SAPJobPriority__c==8) && (sa.FSM_HoursUntilDueDate__c <=23))
        {
            
            if(sa.FSM_DueDateApplyCounterZPM1__c == 2){
                sa.FSM_Backlog__c = TRUE;
            }
            else{
                sa.DueDate=sa.DueDate+7;
                sa.FSM_DueDateApplyCounterZPM1__c =sa.FSM_DueDateApplyCounterZPM1__c + 1;   
            }
            
        }
        // Scenario 3 
        if((sa.FSM_SAPJobPriority__c==9||sa.FSM_SAPJobPriority__c==10) && (sa.FSM_HoursUntilDueDate__c <=23)){
            sa.FSM_Backlog__c = TRUE;  
        }
        
        return sa;
    }
    
    /**
    * @description databaseSaveResult
    * @param saList
    */
    private static void databaseSaveResult(List<ServiceAppointment> saList){
        try{
            Database.SaveResult[] updateResult = Database.update(saList,false);
            List<FSM_ErrorLog__c> errLogs= new List<FSM_ErrorLog__C>();
            for (Database.SaveResult result : updateResult){
                if (!result.isSuccess()) {
                    //Error ecountered              
                    for(Database.Error error : result.getErrors()){
                        //Handle error                           
                        FSM_ErrorLog__c errorLog = new FSM_Utility.ErrorLogCreator().setClassName('FSM_BacklogMaintenanceBatch').setErrorMessage(error.getMessage()+' Failed record id: '+result.getId()).setMethodName('execute').setType('Field Service').returnWithoutCreate();                                                       
                        errLogs.add(errorLog );
                    }
                }
                if(errLogs.Size()>0 && SObjectType.FSM_ErrorLog__c.isCreateable()) {
                Upsert errLogs;
               }
            }
        }catch (Exception e) {
            FSM_ErrorLog__c errorLog = new FSM_Utility.ErrorLogCreator().setClassName('FSM_BacklogMaintenanceBatch').setErrorMessage(e.getMessage()).setLineNumber(String.ValueOF(e.getLineNumber())).setMethodName('execute').setStackTrace(e.getStackTraceString()).setType('Field Service').create();
        }
    }
    
    /**
    * @description scenarioOne
    * @param sa
    */
    private static void scenarioOne(ServiceAppointment sa){
        if((sa.FSM_SAPJobPriority__c==1||sa.FSM_SAPJobPriority__c==2||
            sa.FSM_SAPJobPriority__c==3 || sa.FSM_SAPJobPriority__c==4) && (sa.FSM_HoursUntilDueDate__c <=23))
        { 
            if(sa.FSM_DueDateApplyCounterZPM1__c == 3){
                sa.FSM_Backlog__c = TRUE;
            }
            else{
                sa.DueDate=sa.DueDate+2;
                sa.FSM_DueDateApplyCounterZPM1__c = sa.FSM_DueDateApplyCounterZPM1__c + 1;
            }  
        }

        
    } 
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new FSM_BacklogMaintenanceBatch(),200);
    }  
}