force-app/main/default/objects/FSM_ErrorLog__c/FSM_ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Created as part of #SFS-32</description>
    <label>FSM Error Log</label>
    <nameField>
        <displayFormat>Err-{000000}</displayFormat>
        <label>FSM Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSM Error Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_ErrorLog__c/fields/FSM_ExceptionLineNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExceptionLineNumber__c</fullName>
    <label>Exception Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_ErrorLog__c/fields/FSM_Interface__c.field-meta.xml
<CustomField>
    <fullName>FSM_Interface__c</fullName>
    <description>SFI-1260</description>
    <label>Interface</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INT-001</fullName>
            </value>
            <value>
                <fullName>INT-002</fullName>
            </value>
            <value>
                <fullName>INT-003</fullName>
            </value>
            <value>
                <fullName>INT-004</fullName>
            </value>
            <value>
                <fullName>INT-005</fullName>
            </value>
            <value>
                <fullName>INT-006</fullName>
            </value>
            <value>
                <fullName>INT-008</fullName>
            </value>
            <value>
                <fullName>INT009</fullName>
            </value>
            <value>
                <fullName>INT-010</fullName>
            </value>
            <value>
                <fullName>INT-011</fullName>
            </value>
            <value>
                <fullName>INT-014</fullName>
            </value>
            <value>
                <fullName>INT-015</fullName>
            </value>
            <value>
                <fullName>INT-017</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_ErrorLog__c/fields/FSM_RetryFlag__c.field-meta.xml
<CustomField>
    <fullName>FSM_RetryFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFI-2208</description>
    <label>Retry Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FSM_RetryRequestForInterface14.cls
/********************************************************************************************************
@Author      : Asutosh Singh
@description : This class is created to schedule a Retry Mechanism to send attachments to SAP
@description : Created as part of user story #SFI-2208
@description : Used to invoke FSM_ContentDocumentLinkTriggerHelper class where the actual logic is written
@Test Class  : FSM_ContentDocLinkTriggerTest
@Date        : 24-June-2024
********************************************************************************************************/
public with sharing class FSM_RetryRequestForInterface14 implements Schedulable{
    
    /********************************************************************************************************
    @Author      : Asutosh Singh
    @description : Created as part of user story #SFI-2208
    @description : This method is the execute method for Schedulable class.
    @param 		 : sc
    @Date        : 01-April-2024
    ********************************************************************************************************/
    public void execute(SchedulableContext sc){
        Boolean retryFlag = true; // to set the Retry Flag as true for new errorlog record in case attachment upload fails again 
        List<Id> contentDocumentLinkIds = new List<Id>(); // stores the Content Document Link Id's from the error log
        List<FSM_ErrorLog__c> updatedErrorLog = new List<FSM_ErrorLog__C>(); // to update the retry flag once retry is done
        try{
            // fetch error log records with retry flag = true
            Map<Id, FSM_ErrorLog__c> errorLogMap = new Map<Id, FSM_ErrorLog__c>([
                SELECT Id, FSM_ExceptionLineNumber__c, FSM_RetryFlag__c FROM FSM_ErrorLog__c 
                WHERE FSM_RetryFlag__c = true AND FSM_Interface__c = 'INT-014'
                WITH SECURITY_ENFORCED LIMIT 1000
            ]);
            // get the contentDocumentLinkIds from the error log records and update ErrorLog with retry flag = false
            for(FSM_ErrorLog__c item: errorLogMap.values()){
                contentDocumentLinkIds.add(item.FSM_ExceptionLineNumber__c);
                item.FSM_RetryFlag__c=false; // Update the Retry Flag to false
                updatedErrorLog.add(item);
            }
            if(!contentDocumentLinkIds.isEmpty() && contentDocumentLinkIds!=null){
                Map<Id,ContentDocumentLink> contentDocumentLinkMap = new Map<Id,ContentDocumentLink>([
                    SELECT Id, ContentDocumentId, linkedEntityId FROM ContentDocumentLink 
                    WHERE Id IN :contentDocumentLinkIds WITH SECURITY_ENFORCED
                ]);
                FSM_ContentDocumentLinkTriggerHelper.sendContentVersionToggleCheck(contentDocumentLinkMap, retryFlag);
            }
            if (!updatedErrorLog.isEmpty() && updatedErrorLog!=null && Schema.sObjectType.FSM_ErrorLog__c.isUpdateable()) {
                update updatedErrorLog;
            }
        } catch (Exception e) {
            new FSM_Utility.ErrorLogCreator().setClassName('FSM_RetryRequestForInterface14').setMethodName('execute')
                .setErrorMessage(e.getMessage()).setLineNumber(String.valueOf(e.getLineNumber())).setStackTrace(e.getStackTraceString())
                .setType('Integration').create();
        }
    }
}