force-app/main/default/objects/FSM_AutoScheduleding__e/FSM_AutoScheduleding__e.object-meta.xml
<CustomObject>
    <description>This will run as Integration user through cofig metadat file</description>
    <label>Auto Scheduleding</label>
    <pluralLabel>Auto Scheduleding</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSM_AutoScheduleding__e/fields/FSM_SchedulingPolicyId__c.field-meta.xml
<CustomField>
    <fullName>FSM_SchedulingPolicyId__c</fullName>
    <label>Scheduling Policy Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_AutoScheduleding__e/fields/FSM_ServiceAppointmentId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ServiceAppointmentId__c</fullName>
    <label>Service Appointment Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSL__Auto_Schedule__c.field-meta.xml
<CustomField>
    <fullName>FSL__Auto_Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FSM_AutoScheduling.cls
public without sharing class FSM_AutoScheduling {
    
    public static void updateSAAutoScheduling(List<FSM_AutoScheduleding__e> newMap) {
        List<ServiceAppointment> updateList = new List<ServiceAppointment>();
        for(FSM_AutoScheduleding__e autoSch :newMap){
            
            ServiceAppointment sa = new ServiceAppointment();
            sa.Id = autoSch.FSM_ServiceAppointmentId__c;
            sa.FSL__Auto_Schedule__c = TRUE;
            sa.FSL__Scheduling_Policy_Used__c = autoSch.FSM_SchedulingPolicyId__c;
            updateList.add(sa);
        }
        
        if(updateList.size() >0){
            Update updateList;
        }
    }

}