force-app/main/default/objects/FSM_CMDTLevel2__mdt/FSM_CMDTLevel2__mdt.object-meta.xml
<CustomObject>
    <label>CMDT Level 2</label>
    <pluralLabel>CMDT Level 2s</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSM_CMDTLevel2__mdt/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <description>.</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Water Infra</fullName>
                <default>true</default>
                <label>Water Infra</label>
            </value>
            <value>
                <fullName>Waste Infra</fullName>
            </value>
            <value>
                <fullName>Green Recovery</fullName>
            </value>
            <value>
                <fullName>Developer Services</fullName>
            </value>
            <value>
                <fullName>Water Non Infra</fullName>
            </value>
            <value>
                <fullName>Waste Non Infra</fullName>
            </value>
            <value>
                <fullName>Metering</fullName>
            </value>
            <value>
                <fullName>Bio Resource</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_CMDTLevel2__mdt/fields/FSM_RejectionCategory__c.field-meta.xml
<CustomField>
    <fullName>FSM_RejectionCategory__c</fullName>
    <label>Rejection Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Availability</fullName>
                <default>true</default>
                <label>Availability</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>H&amp;S</fullName>
            </value>
            <value>
                <fullName>Plant/Equipment/Vehicle</fullName>
            </value>
            <value>
                <fullName>Preparation</fullName>
            </value>
            <value>
                <fullName>Asset Data</fullName>
            </value>
            <value>
                <fullName>Asset Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_CMDTLevel2__mdt/fields/FSM_RejectionReason__c.field-meta.xml
<CustomField>
    <fullName>FSM_RejectionReason__c</fullName>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End of shift</fullName>
                <default>true</default>
                <label>End of shift</label>
            </value>
            <value>
                <fullName>Emergency/Reactive Work</fullName>
            </value>
            <value>
                <fullName>Unplanned absence</fullName>
            </value>
            <value>
                <fullName>Travel delays</fullName>
            </value>
            <value>
                <fullName>CUSTOMER Not at home</fullName>
            </value>
            <value>
                <fullName>Requested by Customer</fullName>
            </value>
            <value>
                <fullName>No access-Customer/Land owner</fullName>
            </value>
            <value>
                <fullName>Customer site not ready</fullName>
            </value>
            <value>
                <fullName>Adverse weather conditions</fullName>
            </value>
            <value>
                <fullName>Incorrect Skills</fullName>
            </value>
            <value>
                <fullName>Obstruction removal required</fullName>
            </value>
            <value>
                <fullName>Dangerous situation</fullName>
            </value>
            <value>
                <fullName>Engineering Difficulties</fullName>
            </value>
            <value>
                <fullName>Additional resource</fullName>
            </value>
            <value>
                <fullName>Incorrect</fullName>
            </value>
            <value>
                <fullName>Part unavailable</fullName>
            </value>
            <value>
                <fullName>Not available</fullName>
            </value>
            <value>
                <fullName>System error</fullName>
            </value>
            <value>
                <fullName>Breakdown</fullName>
            </value>
            <value>
                <fullName>Further visit/work required</fullName>
            </value>
            <value>
                <fullName>No work required</fullName>
            </value>
            <value>
                <fullName>No access/Parking</fullName>
            </value>
            <value>
                <fullName>Traffic Mgnt not available</fullName>
            </value>
            <value>
                <fullName>Traffic Mgnt not booked</fullName>
            </value>
            <value>
                <fullName>Duplicate operation</fullName>
            </value>
            <value>
                <fullName>Work conflict</fullName>
            </value>
            <value>
                <fullName>Permission to dig required</fullName>
            </value>
            <value>
                <fullName>Traffic Management Incorrect</fullName>
            </value>
            <value>
                <fullName>Time constraints (Day/Time)</fullName>
            </value>
            <value>
                <fullName>Same Day Rein needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_CMDTLevel2__mdt/fields/FSM_Workmate__c.field-meta.xml
<CustomField>
    <fullName>FSM_Workmate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFS-2987</description>
    <label>Workmate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_StatusTransition__mdt/FSM_StatusTransition__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to hold the status transitions for each profile.
Created as part of User Story #SFS-167</description>
    <label>FSM Status Transition</label>
    <pluralLabel>FSM Status Transitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSM_StatusTransition__mdt/fields/FSM_CurrentStatus__c.field-meta.xml
<CustomField>
    <fullName>FSM_CurrentStatus__c</fullName>
    <description>Created as part of User Story #SFS-167</description>
    <label>Status From (Current Status)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>En-Route</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Not Attended</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Partially Complete</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Unattended</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Return to Site</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_StatusTransition__mdt/fields/FSM_ProfileName__c.field-meta.xml
<CustomField>
    <fullName>FSM_ProfileName__c</fullName>
    <description>Created as part of User Story #SFS-167</description>
    <label>Profile Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSM Customer Community Plus User</fullName>
            </value>
            <value>
                <fullName>FSM Field Service Admin</fullName>
            </value>
            <value>
                <fullName>FSM Integration</fullName>
            </value>
            <value>
                <fullName>FSM Metering Field Worker</fullName>
            </value>
            <value>
                <fullName>FSM Non Infra Field Worker</fullName>
            </value>
            <value>
                <fullName>FSM Partner Community User</fullName>
            </value>
            <value>
                <fullName>FSM Standard Desktop User</fullName>
            </value>
            <value>
                <fullName>FSM System Administrator</fullName>
            </value>
            <value>
                <fullName>FSM Virtual User</fullName>
            </value>
            <value>
                <fullName>FSM Waste Network Field Worker</fullName>
            </value>
            <value>
                <fullName>FSM Water Networks &amp; DevServ Field Worker</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>FSM Site Worker</fullName>
            </value>
            <value>
                <fullName>FSM Virtual Metering</fullName>
            </value>
            <value>
                <fullName>FSM Virtual Infra</fullName>
            </value>
            <value>
                <fullName>FSM Waste Customer Community Plus User</fullName>
            </value>
            <value>
                <fullName>FSM Water &amp; DevServ Customer Community Plus User</fullName>
            </value>
            <value>
                <fullName>FSM Dev Services Field Worker</fullName>
                <isActive>false</isActive>
                <label>FSM Dev Services Field Worker</label>
            </value>
            <value>
                <fullName>FSM Non Infra Site Worker</fullName>
                <isActive>false</isActive>
                <label>FSM Non Infra Site Worker</label>
            </value>
            <value>
                <fullName>FSM Water Network Field Worker</fullName>
                <isActive>false</isActive>
                <label>FSM Water Network Field Worker</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_StatusTransition__mdt/fields/FSM_StatusToUpdate__c.field-meta.xml
<CustomField>
    <fullName>FSM_StatusToUpdate__c</fullName>
    <description>Created as part of User Story #SFS-167</description>
    <label>Status To Update</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>En-Route</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Unattended</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Partially Complete</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Return to Site</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waste Infra</fullName>
            </value>
            <value>
                <fullName>Water Infra</fullName>
            </value>
            <value>
                <fullName>Water Non Infra</fullName>
            </value>
            <value>
                <fullName>Waste Non Infra</fullName>
            </value>
            <value>
                <fullName>Bio Resource</fullName>
            </value>
            <value>
                <fullName>Developer Services</fullName>
            </value>
            <value>
                <fullName>Metering</fullName>
            </value>
            <value>
                <fullName>Green Recovery</fullName>
            </value>
            <value>
                <fullName>WasteNon Infra</fullName>
                <isActive>false</isActive>
                <label>WasteNon Infra</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/FSM_ProfileName__c.field-meta.xml
<CustomField>
    <fullName>FSM_ProfileName__c</fullName>
    <description>Added this field to  fix issues of Profile.Name field access, this is a back end field. SFS-1428</description>
    <formula>$Profile.Name</formula>
    <label>Profile Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSM_BulkStatusUpdateSAController.cls
/** ************************************************************************************
@Author : Brajesh Kumar
@Description  : Created for for Bulk Status Update Action
@Created Date : 16th June 2024
@Test Class : FSM_SelectAndScheduleTest
@description : Created as part of user story SFS-6634
**************************************************************************************** **/
public with sharing class FSM_BulkStatusUpdateSAController {
    // Get Status from FSM_StatusTransition CMDT Object
    @AuraEnabled(cacheable=true)
    public static List<FSM_StatusTransition__mdt> getStatusTransition() {
        // Query the custom metadata
        List<FSM_StatusTransition__mdt> metadataList = [SELECT FSM_CurrentStatus__c , FSM_StatusToUpdate__c FROM FSM_StatusTransition__mdt where FSM_ProfileName__c = 'FSM Site Worker' WITH SECURITY_ENFORCED];
        return metadataList;
    }
    
    
    // Get Reject Category & Reject Reason from FSM_CMDTLevel2__mdt Object
    @AuraEnabled(cacheable=true)
    public static List<FSM_CMDTLevel2__mdt> getRejectionDetails() {
        return [SELECT FSM_RejectionCategory__c, FSM_RejectionReason__c,FSM_SAPName__c,FSM_BusinessUnit__c FROM FSM_CMDTLevel2__mdt WHERE FSM_Workmate__c = true WITH SECURITY_ENFORCED];
    }
    
    
}