force-app/main/default/objects/ContentVersion/fields/FSM_Do_not_send_to_SAP__c.field-meta.xml
<CustomField>
    <fullName>FSM_Do_not_send_to_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>created as part of SFS-4061 to indicate that the additional files created while creating pdf in gold sketchand simple sketch should not be sent</description>
    <label>Do not send to SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/FSM_InfraDataCaptureForm2__c.object-meta.xml
<CustomObject>
    <description>Created as a part of SFS-3958</description>
    <label>Infra Data Capture Form 2</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Infra Data Capture Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 2</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_DeviceType__c.field-meta.xml
<CustomField>
    <fullName>FSM_DeviceType__c</fullName>
    <description>sfs-6005</description>
    <label>DeviceType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Generate_PDF__c.field-meta.xml
<CustomField>
    <fullName>FSM_Generate_PDF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFS-6005</description>
    <label>Generate PDF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_OperationNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_OperationNumber__c</fullName>
    <description>SFS-3010</description>
    <formula>FSM_WorkOrder__r.FSM_OperationNumber__c</formula>
    <label>Operation Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_ServiceTerritory__c.field-meta.xml
<CustomField>
    <fullName>FSM_ServiceTerritory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as a part of SFS-3958</description>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>FSM_InfraDataCaptureForm2</relationshipLabel>
    <relationshipName>FSM_InfraDataCaptureForm2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as a part of SFS-3958</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Infra Data Capture Form 2</relationshipLabel>
    <relationshipName>FSM_InfraDataCaptureForm2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_DeviceType__c.field-meta.xml
<CustomField>
    <fullName>FSM_DeviceType__c</fullName>
    <description>Created as part of sfs-4083</description>
    <label>FSM_DeviceType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_OperationNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_OperationNumber__c</fullName>
    <description>Placeholder field to support DCF build</description>
    <label>Operation Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_OrderNumber__c</fullName>
    <description>Created to support DCF build</description>
    <label>Order Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSM_sketchCls_DCF2.cls
/*@author: Alagar
@Date: 02/07/24
@comments: This creates a PDF of the edit image
@LastModifiedby:Brajesh for SFS-5399
*/
public with sharing class FSM_sketchCls_DCF2 {
    /*
@methiodname: pdfCreation
@comments: calls vf page for PDF creation
*/
    @Future(callout=true)
    public static void pdfCreation(Id saID,string recId){ 
        
        FSM_InfraDataCaptureForm2__c dcfupdate=new FSM_InfraDataCaptureForm2__c();
        
        
        Pagereference pg;
        List<FSM_InfraDataCaptureForm2__c> fetchDcf = new List<FSM_InfraDataCaptureForm2__c>();
        fetchDcf = [select id, FSM_DeviceType__c,FSM_WorkOrder__r.FSM_OrderNumber__c,FSM_WorkOrder__r.FSM_OperationNumber__c from FSM_InfraDataCaptureForm2__c where id=: recId LIMIT 1];
        
        String getDateTime= getFormattedDateTime();
        String pdfFileName = fetchDcf[0].FSM_WorkOrder__r.FSM_OrderNumber__c+'_'+fetchDcf[0].FSM_WorkOrder__r.FSM_OperationNumber__c+'_FWR_'+getDateTime+'.pdf';
        string device=fetchDcf[0].FSM_DeviceType__c;
        if(device=='Mobile'){
            pg = Page.FSM_Sewerage_Mobile;
        }
        else{
            pg = Page.FSM_Sewerage_Desktop;
        } 
        pg.getParameters().put('id', recId);
        Blob pdfFileData ;
        if(Test.isRunningTest()) { 
            pdfFileData = blob.valueOf('Unit.Test');
        } else {
            pdfFileData = pg.getContentaspdf();
        } 
        dcfupdate=[Select id,FSM_Generate_PDF__c,FSM_ServiceTerritory__c,FSM_WorkOrder__c,FSM_WorkOrder__r.CaseId from FSM_InfraDataCaptureForm2__c where id=:recId];
        //PDF generation
        ContentVersion cv = createContentVersion(pdfFileData , null, pdfFileName );
        ContentDocumentLink cdl = createContentLink(cv.Id, recId);
        ContentDocumentLink cd2 = createContentLink(cv.Id, dcfupdate.FSM_WorkOrder__c);  //commented as queueable error is thrown
        ContentDocumentLink cd3 = createContentLink(cv.Id, dcfupdate.FSM_WorkOrder__r.CaseId); // added a part of SFL-1110
        //Added as part of SFS-4516
        
        List<WorkOrder> wo=[Select id,ServiceTerritoryId from WorkOrder where id=:dcfupdate.FSM_WorkOrder__c WITH SECURITY_ENFORCED];
        if(wo.size() > 0){
            if (Schema.sObjectType.FSM_InfraDataCaptureForm2__c.fields.FSM_ServiceTerritory__c.isUpdateable()) {
                dcfupdate.FSM_ServiceTerritory__c=wo[0].ServiceTerritoryId;
                update dcfupdate;
            }
        }
        
    }
    //@return String - The formatted date and time as a string in the format YYYY-MM-DD_HHMMSS.
    public static String getFormattedDateTime() {
        // Get the current datetime
        Datetime now = Datetime.now();
        // Extract and format year, month, day, hours, minutes, and seconds
        String formattedDateTime = String.format(
            '{0}{1}{2}{3}{4}{5}',
            new List<Object>{
                String.valueOf(now.year()),
                    now.month() < 10 ? '0' + String.valueOf(now.month()) : String.valueOf(now.month()),
                        now.day() < 10 ? '0' + String.valueOf(now.day()) : String.valueOf(now.day()),
                            now.hour() < 10 ? '0' + String.valueOf(now.hour()) : String.valueOf(now.hour()),
                                now.minute() < 10 ? '0' + String.valueOf(now.minute()) : String.valueOf(now.minute()),
                                    now.second() < 10 ? '0' + String.valueOf(now.second()) : String.valueOf(now.second())
                                        }
        );
        return formattedDateTime;
    }
    /*
@methiodname: createContentVersion
@comments: content document creation
*/
    public static ContentVersion createContentVersion(Blob bData, String base64, String filename) {
        system.debug('inside createContentVersion');
        String userId = UserInfo.getUserId();
        Id profileId = UserInfo.getProfileId();
        String profileName =[Select Id, Name from Profile where Id=:profileId].Name;
        ContentVersion cv = new ContentVersion();
        cv.VersionData = ( bData <> Null ? bData : EncodingUtil.base64Decode(base64));
        cv.Title = filename;
        cv.PathOnClient = filename;
        cv.FSM_Do_not_send_to_SAP__c=false; //added as part of SFS-4061  
        try {
            if(Schema.sObjectType.ContentVersion.isCreateable()){
                insert cv;
                system.debug('pdf cv'+cv);
            }
            return cv;
        } catch(DMLException e) {System.debug('error'+e);return null;
                                }
    }
    
    /*
@methiodname: ContentDocumentLink
@comments: link the document with the record
*/
    public static ContentDocumentLink createContentLink(String contentVersionId, String recordId) {
        system.debug('inside createContentLink');
        if (contentVersionId == null || recordId == null) { return null; }
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [
            SELECT ContentDocumentId 
            FROM ContentVersion 
            WHERE Id =: contentVersionId
        ].ContentDocumentId;
        cdl.LinkedEntityId = recordId;
        // ShareType is either 'V', 'C', or 'I'
        // V = Viewer, C = Collaborator, I = Inferred
        cdl.ShareType = 'V';
        try {
            if(Schema.sObjectType.ContentDocumentLink.isCreateable()){
                insert cdl;
                system.debug('inside after insert');
            }
            //added as part of sfs-4061
            Id recid=recordId;
            String sObjName = recid.getSObjectType().getDescribe().getName();
            if(sObjName == 'FSM_InfraDataCaptureForm2__c')
            {
                FSM_sketchImageDeletionDCF2.deleteimagesafterpdfcreation(recordId);
            }
            
            return cdl;
            
        }catch(DMLException e) { return null;
                               }
        
    }
}