force-app/main/default/objects/ContentVersion/fields/FSM_Do_not_send_to_SAP__c.field-meta.xml
<CustomField>
    <fullName>FSM_Do_not_send_to_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>created as part of SFS-4061 to indicate that the additional files created while creating pdf in gold sketchand simple sketch should not be sent</description>
    <label>Do not send to SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/FSM_DataCaptureFormInfra__c.object-meta.xml
<CustomObject>
    <description>Data capture form structure for Infra BU only, SFI-35 and SFS-1950</description>
    <label>Infra Data Capture Form 1</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Data Capture Form Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 1</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_Asset__c.field-meta.xml
<CustomField>
    <fullName>FSM_Asset__c</fullName>
    <inlineHelpText>The asset is the piece of Equipment you will be working on e.g. Main</inlineHelpText>
    <label>Asset</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D 2</fullName>
                <label>MAIN</label>
            </value>
            <value>
                <fullName>D 3</fullName>
                <label>SERVICE</label>
            </value>
            <value>
                <fullName>D 4</fullName>
                <label>BOUNDARY BOX AND METER</label>
            </value>
            <value>
                <fullName>D 5</fullName>
                <label>LONG COMM PIPE</label>
            </value>
            <value>
                <fullName>D 6</fullName>
                <label>SHORT COMM PIPE</label>
            </value>
            <value>
                <fullName>D 7</fullName>
                <label>SLUICE VALVE</label>
            </value>
            <value>
                <fullName>D 8</fullName>
                <label>HYDRANT</label>
            </value>
            <value>
                <fullName>D 9</fullName>
                <label>WASHOUT</label>
            </value>
            <value>
                <fullName>D 10</fullName>
                <label>STOP TAP</label>
            </value>
            <value>
                <fullName>D 11</fullName>
                <label>BOUNDARY BOX</label>
            </value>
            <value>
                <fullName>D 12</fullName>
                <label>METER</label>
            </value>
            <value>
                <fullName>D 13</fullName>
                <label>PSV</label>
            </value>
            <value>
                <fullName>D 14</fullName>
                <label>PRV</label>
            </value>
            <value>
                <fullName>D 15</fullName>
                <label>AIR VALVE</label>
            </value>
            <value>
                <fullName>D 16</fullName>
                <label>MARKER POST</label>
            </value>
            <value>
                <fullName>D 17</fullName>
                <label>LOGGER</label>
            </value>
            <value>
                <fullName>D 18</fullName>
                <label>RRU</label>
            </value>
            <value>
                <fullName>D 19</fullName>
                <label>TANKER</label>
            </value>
            <value>
                <fullName>D 20</fullName>
                <label>BOWSER</label>
            </value>
            <value>
                <fullName>D 21</fullName>
                <label>FILTER</label>
            </value>
            <value>
                <fullName>D 22</fullName>
                <label>CUSTOMER TAP</label>
            </value>
            <value>
                <fullName>D 23</fullName>
                <label>RESERVOIR</label>
            </value>
            <value>
                <fullName>D 24</fullName>
                <label>OVERLANDER</label>
            </value>
            <value>
                <fullName>D 25</fullName>
                <label>AQUEDUCT</label>
            </value>
            <value>
                <fullName>D 26</fullName>
                <label>REINSTATEMENT</label>
            </value>
            <value>
                <fullName>D 27</fullName>
                <label>SYSTEM</label>
            </value>
            <value>
                <fullName>D 28</fullName>
                <label>HOUSEHOLD PROPERTY</label>
            </value>
            <value>
                <fullName>D 29</fullName>
                <label>NON HOUSEHOLD PROPERTY</label>
            </value>
            <value>
                <fullName>D 30</fullName>
                <label>HOUSEHOLD SUPPLY PIPE</label>
            </value>
            <value>
                <fullName>D 31</fullName>
                <label>NON HOUSEHOLD SUPPLY PIPE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_DeviceType__c.field-meta.xml
<CustomField>
    <fullName>FSM_DeviceType__c</fullName>
    <label>DeviceType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_FileName__c.field-meta.xml
<CustomField>
    <fullName>FSM_FileName__c</fullName>
    <description>created as a part of FSM-5400</description>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_Generate_PDF__c.field-meta.xml
<CustomField>
    <fullName>FSM_Generate_PDF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate PDF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_Location__c.field-meta.xml
<CustomField>
    <fullName>FSM_Location__c</fullName>
    <inlineHelpText>This Information is visible to Highways Authority on the notice and must contain the correct address information -  If the job is on the public highway AND private land then select &apos;public highway&apos; in the dropdown menu above and complete the permission to dig details below</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Find and Fix location</fullName>
            </value>
            <value>
                <fullName>Private Land</fullName>
            </value>
            <value>
                <fullName>Public Highway</fullName>
            </value>
            <value>
                <fullName>Restricted Land</fullName>
            </value>
            <value>
                <fullName>Boards and Barriers Replenishment</fullName>
                <label>Boards and barriers</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_OrderNumber__c</fullName>
    <description>SFS-3010</description>
    <formula>FSM_WorkOrder__r.FSM_OrderNumber__c</formula>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_ServiceTerritory__c.field-meta.xml
<CustomField>
    <fullName>FSM_ServiceTerritory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created As part of SFI-35 for Record sharing based on Territory and for future purpose as well.</description>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipName>Data_Capture_Form_Infras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as part of SFS-1950</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>FSM_DataCaptureFormInfras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_DeviceType__c.field-meta.xml
<CustomField>
    <fullName>FSM_DeviceType__c</fullName>
    <description>Created as part of sfs-4083</description>
    <label>FSM_DeviceType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_FileName__c.field-meta.xml
<CustomField>
    <fullName>FSM_FileName__c</fullName>
    <description>Created as part of sfs-4083</description>
    <label>FSM_FileName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_OperationNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_OperationNumber__c</fullName>
    <description>Placeholder field to support DCF build</description>
    <label>Operation Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_OrderNumber__c</fullName>
    <description>Created to support DCF build</description>
    <label>Order Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSM_sketchCls.cls
/*@author: Alagar
@Date: 12/07/23
@comments: This creates a PDF of the edit image
@LastModifiedby:Brajesh Kumar
*/

public with sharing class FSM_sketchCls {
  /*
@methiodname: pdfCreation
@comments: calls vf page for PDF creation
*/
    @Future(callout=true)
    //public static void pdfCreation(Id saID, string recId, string docId){ ash  commented as part of 3841
     public static void pdfCreation(Id saID,string recId){ 
            
        FSM_DataCaptureFormInfra__c dcfupdate=new FSM_DataCaptureFormInfra__c();
     
        Set<String> BOPPS_ASSET_TYPES = new Set<String>{
          'D 28',// HOUSEHOLD PROPERTY
          'D 29',// NON HOUSEHOLD PROPERTY
          'D 30',// HOUSEHOLD SUPPLY PIPE
          'D 31' // NON HOUSEHOLD PROPERTY
        };
        Pagereference pg;
        List<FSM_DataCaptureFormInfra__c> fetchDcf = new List<FSM_DataCaptureFormInfra__c>();
        try{
         fetchDcf = [select id,FSM_WorkOrder__r.FSM_OrderNumber__c,FSM_WorkOrder__r.FSM_OperationNumber__c,FSM_WorkOrder__r.FSM_ExternalId__c, FSM_DeviceType__c, FSM_Location__c, FSM_Asset__c,FSM_FileName__c from FSM_DataCaptureFormInfra__c where id=: recId LIMIT 1];
        // String pdfFileName = 'FWR_'+System.now()+'.pdf';
        // Updated as part of SFL-562
		 String getDateTime= getFormattedDateTime();
         String pdfFileName = fetchDcf[0].FSM_WorkOrder__r.FSM_OrderNumber__c+'_'+fetchDcf[0].FSM_WorkOrder__r.FSM_OperationNumber__c+'_FWR_'+getDateTime+'.pdf';
        if(detectPageToLoad(fetchDcf) == 'FSM_Water_Mobile')
        {
            pg = Page.FSM_Water_Mobile;
        }
        else if(detectPageToLoad(fetchDcf) == 'FSM_Water_Desktop')
        {pg = Page.FSM_Water_Desktop;}
        else if (detectPageToLoad(fetchDcf) == 'FSM_BOPPS_Mobile')
        {pg = Page.FSM_BOPPS_Mobile;}
        else if (detectPageToLoad(fetchDcf) == 'FSM_BOPPS_Desktop')
        {
            pg = Page.FSM_BOPPS_Desktop;
        }else {string device=fetchDcf[0].FSM_DeviceType__c;if(device=='Mobile'){ pg = Page.FSM_Water_Mobile;}else{pg = Page.FSM_Water_Desktop;}  }
            
        
        pg.getParameters().put('id', recId);
        Blob pdfFileData ;
        if(Test.isRunningTest()) { 
            pdfFileData = blob.valueOf('Unit.Test');
        } else {pdfFileData = pg.getContentaspdf();
        } 
        system.debug('----- pdfFileData'+pdfFileData);
        
        //PDF generation
        ContentVersion cv = createContentVersion(pdfFileData , null, pdfFileName );
        ContentDocumentLink cdl = createContentLink(cv.Id, recId);
       // ContentDocumentLink cd2 = createContentLink(cv.Id, saID);commented as queueable error is thrown
         //Added as part of SFS-4516
         dcfupdate=[Select id,FSM_Generate_PDF__c,FSM_ServiceTerritory__c,FSM_WorkOrder__c from FSM_DataCaptureFormInfra__c where id=:recId with Security_enforced];
         List<WorkOrder> wo=[Select id,ServiceTerritoryId from WorkOrder where id=:dcfupdate.FSM_WorkOrder__c with Security_enforced];
         if(wo.size() > 0){
            if (Schema.sObjectType.FSM_DataCaptureFormInfra__c.fields.FSM_ServiceTerritory__c.isUpdateable()) {
                dcfupdate.FSM_ServiceTerritory__c=wo[0].ServiceTerritoryId;
                update dcfupdate;
             }
            }
        }
        catch (VisualforceException vfe){
        	system.debug('------ VF exception'+ vfe);
        }
        catch (Exception e){
           system.debug('------  exception'+ e);
        }
         }
    
    

    //@return String - The formatted date and time as a string in the format YYYY-MM-DD_HHMMSS.
    public static String getFormattedDateTime() {
        // Get the current datetime
        Datetime now = Datetime.now();
        // Extract and format year, month, day, hours, minutes, and seconds
        String formattedDateTime = String.format(
            '{0}{1}{2}{3}{4}{5}',
            new List<Object>{
                String.valueOf(now.year()),
                now.month() < 10 ? '0' + String.valueOf(now.month()) : String.valueOf(now.month()),
                now.day() < 10 ? '0' + String.valueOf(now.day()) : String.valueOf(now.day()),
                now.hour() < 10 ? '0' + String.valueOf(now.hour()) : String.valueOf(now.hour()),
                now.minute() < 10 ? '0' + String.valueOf(now.minute()) : String.valueOf(now.minute()),
                now.second() < 10 ? '0' + String.valueOf(now.second()) : String.valueOf(now.second())
            }
        );
        return formattedDateTime;
    }



    
    public static string detectPageToLoad(List<FSM_DataCaptureFormInfra__c> fetchDcf)
    {
        Set<String> BOPPS_ASSET_TYPES = new Set<String>{
          'D 28',// HOUSEHOLD PROPERTY
          'D 29',// NON HOUSEHOLD PROPERTY
          'D 30',// HOUSEHOLD SUPPLY PIPE
          'D 31' // NON HOUSEHOLD PROPERTY
        };
        if((fetchDcf[0].FSM_Location__c!=null && fetchDcf[0].FSM_Location__c == 'Private Land') && (fetchDcf[0].FSM_Asset__c!=null && BOPPS_ASSET_TYPES.contains(fetchDcf[0].FSM_Asset__c)))
        {
            string device=fetchDcf[0].FSM_DeviceType__c;
            if(device=='Mobile'){ return 'FSM_BOPPS_Mobile';
            }
            else{ return 'FSM_BOPPS_Desktop';
            }
        }else{string device=fetchDcf[0].FSM_DeviceType__c;if(device=='Mobile'){ return 'FSM_Water_Mobile';}else{return 'FSM_Water_Desktop';}}
       // return null;
    }
    /*
@methiodname: createContentVersion
@comments: content document creation
*/
    public static ContentVersion createContentVersion(Blob bData, String base64, String filename) {
         system.debug('inside createContentVersion');
        String userId = UserInfo.getUserId();
        Id profileId = UserInfo.getProfileId();
        String profileName =[Select Id, Name from Profile where Id=:profileId].Name;
        ContentVersion cv = new ContentVersion();  
            cv.VersionData = ( bData <> Null ? bData : EncodingUtil.base64Decode(base64));
            cv.Title = filename;
            cv.PathOnClient = filename;
            cv.FSM_Do_not_send_to_SAP__c=false; //added as part of SFS-4061
     /** Communities are no longer in use, so commenting out the codes related to it.
        if(profileName.contains('Customer Community'))
        {
            Id networkId = [SELECT NetworkId, MemberId FROM NetworkMember WHERE MemberId =:userId].NetworkId;
           
            cv.VersionData = ( bData <> Null ? bData : EncodingUtil.base64Decode(base64));
            cv.Title = filename;
            cv.PathOnClient = filename;
            cv.NetworkId= networkId;
            cv.FSM_Do_not_send_to_SAP__c=false; //added as part of SFS-4061
        }else{
           
            cv.VersionData = ( bData <> Null ? bData : EncodingUtil.base64Decode(base64));
            cv.Title = filename;
            cv.PathOnClient = filename;
            cv.FSM_Do_not_send_to_SAP__c=false; //added as part of SFS-4061
        }
**/

        try {
            if(Schema.sObjectType.ContentVersion.isCreateable()){
                insert cv;
                system.debug('pdf cv'+cv);
            }
            return cv;
        } catch(DMLException e) {System.debug('error'+e); return null;
        }
    }
    
    /*
@methiodname: ContentDocumentLink
@comments: link the document with the record
*/
    public static ContentDocumentLink createContentLink(String contentVersionId, String recordId) {
        system.debug('inside createContentLink');
        if (contentVersionId == null || recordId == null) { return null; }
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [
            SELECT ContentDocumentId 
            FROM ContentVersion 
            WHERE Id =: contentVersionId
        ].ContentDocumentId;
        cdl.LinkedEntityId = recordId;
        // ShareType is either 'V', 'C', or 'I'
        // V = Viewer, C = Collaborator, I = Inferred
        cdl.ShareType = 'V';
        try {
            if(Schema.sObjectType.ContentDocumentLink.isCreateable()){
                insert cdl;
                system.debug('inside after insert');
            }
            //added as part of sfs-4061
            Id recid=recordId;
            String sObjName = recid.getSObjectType().getDescribe().getName();
            if(sObjName == 'FSM_DataCaptureFormInfra__c')
            {
                 FSM_sketchImageDeletionDCF1.deleteimagesafterpdfcreation(recordId);
            }
            
            return cdl;
           
        }catch(DMLException e) { return null;
        }
        
    }
}