force-app/main/default/objects/ServiceResource/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/FSM_WorkCentreExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkCentreExternalId__c</fullName>
    <description>SFI-701</description>
    <label>Work Centre External Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waste Infra</fullName>
            </value>
            <value>
                <fullName>Water Infra</fullName>
            </value>
            <value>
                <fullName>Water Non Infra</fullName>
            </value>
            <value>
                <fullName>Waste Non Infra</fullName>
            </value>
            <value>
                <fullName>Bio Resource</fullName>
            </value>
            <value>
                <fullName>Developer Services</fullName>
            </value>
            <value>
                <fullName>Metering</fullName>
            </value>
            <value>
                <fullName>Green Recovery</fullName>
            </value>
            <value>
                <fullName>WasteNon Infra</fullName>
                <isActive>false</isActive>
                <label>WasteNon Infra</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Waste Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Waste Non Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Water Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Water Non Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Bio Resource</fullName>
    </customValue>
    <customValue>
        <fullName>Developer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Metering</fullName>
    </customValue>
    <customValue>
        <fullName>Green Recovery</fullName>
        <isActive>false</isActive>
        <label>Green Recovery</label>
    </customValue>
    <description>STW Business Unit</description>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Fsm_ManageCrew.cls
/********************************************************************************************************
@Author      : Brajesh Kumar
@description : This class is used fetch manage crew members in Manage Crew Feature - LWC :FsmManageCrew
@description : Created as part of user story #SFL-886
@Test Class  : Fsm_ManageCrewTest
@Date        : 10-July-2025
********************************************************************************************************/
public with sharing class Fsm_ManageCrew {
    Static Id currentUserId = UserInfo.getUserId();// Get current user Id
    /********************************************************************************************************
    @Author      : Brajesh Kumar
    @description : Method to fetch ServiceResources based on their Business Unit and ResourceType.
    ********************************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<ServiceResource> getActiveResources() {
        // Find ServiceResource for current user
        List<ServiceResource> userResources = [
            SELECT Id, FSM_BusinessUnit__c
            FROM ServiceResource
            WHERE RelatedRecordId = :currentUserId AND
            IsActive = true AND
            FSM_BusinessUnit__c != null WITH SECURITY_ENFORCED];
        
        // If not found, return empty list
        if (userResources == null || userResources.isEmpty()) {
            return new List<ServiceResource>();
        }
        
        // Fetch all active ServiceResources with ResourceType 'T' and same business unit as user, EXCLUDING current user
        // is it possible to mark user as current user when returning the list
        List<ServiceResource> resources = [
            SELECT Id, Name, FSM_WorkCentreExternalId__c, FSL__GanttLabel__c
            FROM ServiceResource
            WHERE IsActive = true
            AND ResourceType = 'T'
            AND FSM_BusinessUnit__c = : userResources[0].FSM_BusinessUnit__c
            AND RelatedRecordId != :currentUserId WITH SECURITY_ENFORCED];
        
        return resources;
    }
     
    /********************************************************************************************************
    @Author      : Brajesh Kumar
    @description : This method retrieves the ID of the active ServiceResource record associated with the 
                   current user, if available, by querying based on the user's ID and active.
    ********************************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static Id getCurrentUserServiceResourceId() {
        // Declare a variable to hold a blank ID (will be returned if no matching resource is found)
        ID blankID;
        // Query the ServiceResource object to find active resources related to the current user
        List<ServiceResource> resources = [
            SELECT Id
            FROM ServiceResource
            WHERE RelatedRecordId = :currentUserId AND 
            IsActive = true WITH SECURITY_ENFORCED];
        
        // If no matching ServiceResource is found, return the blank ID else Return the ID of the first matching ServiceResource
        if (resources == null || resources.isEmpty()) {
            return blankID;
        }else{
            return resources[0].Id;
        }
    }
}