force-app/main/default/objects/FSM_DataCaptureFormInfra__c/FSM_DataCaptureFormInfra__c.object-meta.xml
<CustomObject>
    <description>Data capture form structure for Infra BU only, SFI-35 and SFS-1950</description>
    <label>Infra Data Capture Form 1</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Data Capture Form Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 1</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_Status__c.field-meta.xml
<CustomField>
    <fullName>FSM_Status__c</fullName>
    <description>Created as part of SFS-1950,  SFS-2982</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_WorkCentre__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkCentre__c</fullName>
    <description>SFS-2983</description>
    <formula>FSM_WorkOrder__r.ServiceTerritory.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work centre</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_WorkStep__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SFS-3778</description>
    <label>Work Step</label>
    <referenceTo>WorkStep</referenceTo>
    <relationshipName>FSM_DataCaptureFormInfras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/FSM_DCFConfigurationWorkStep__mdt.object-meta.xml
<CustomObject>
    <description>Created as a part of SFS-1298.

Metadata holds the configurations necessary for auto-creating work steps in Field Service Lightning (FSL). When a work order (WO) is created, these configurations are matched against several criteria, including Service Territory, Standard Text Key, Minimum Crew Size, Suitability, and Business Units. If the criteria match, the corresponding metadata records are used to generate the work steps for the WO.

Note: A Standard Text Key value of * indicates that the metadata record should be considered for any standard text key on the WO.

Updated for SFS-1298</description>
    <label>DCF Configuration - Work Step</label>
    <pluralLabel>DCF Configuration - Work Steps</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_AlternativeFormsGroup__c.field-meta.xml
<CustomField>
    <fullName>FSM_AlternativeFormsGroup__c</fullName>
    <description>Any one of the forms under this group requires completion.</description>
    <inlineHelpText>Any one of the forms under this group requires completion.</inlineHelpText>
    <label>Alternative Form&apos;s Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sewerage</fullName>
                <default>true</default>
                <label>Sewerage</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <description>Business Unit</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waste Infra</fullName>
                <default>true</default>
                <label>Waste Infra</label>
            </value>
            <value>
                <fullName>Waste Non Infra</fullName>
            </value>
            <value>
                <fullName>Water Infra</fullName>
            </value>
            <value>
                <fullName>Water Non Infra</fullName>
            </value>
            <value>
                <fullName>Bio Resource</fullName>
            </value>
            <value>
                <fullName>Developer Services</fullName>
            </value>
            <value>
                <fullName>Metering</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_DCFformName__c.field-meta.xml
<CustomField>
    <fullName>FSM_DCFformName__c</fullName>
    <description>This field stores API Names of the flows used for every Form. Created as a part of SFS-1298.</description>
    <label>DCF Form Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_IsMandatory__c.field-meta.xml
<CustomField>
    <fullName>FSM_IsMandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Field is used for checking if the E-Form created is Mandatory to complete or not. Created as a part of SFS-1298.</description>
    <label>Mandatory On Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_MandatoryOnSuspend__c.field-meta.xml
<CustomField>
    <fullName>FSM_MandatoryOnSuspend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory on Suspend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_MaxInstance__c.field-meta.xml
<CustomField>
    <fullName>FSM_MaxInstance__c</fullName>
    <description>SFS-6573. Maximum number of completed forms permitted Work Step. When DCF flow is launched it first checks for completed forms against this number.</description>
    <inlineHelpText>Maximum number of completed forms permitted under a Work Step.</inlineHelpText>
    <label>Max Instance</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_NoEngonOP__c.field-meta.xml
<CustomField>
    <fullName>FSM_NoEngonOP__c</fullName>
    <description>Created as part of SFS-4894.This field is used for storing Config details of minimum crew size in work order for eform creation. If this number reaches the minimum crew size on the job, (along with Standard Text Key, Work Centre, Suitability, Business Unit etc) DCF becomes mandatory. Updated as part of SFS-6568.</description>
    <inlineHelpText>If this number reaches the min crew size on job, (along with other criteria below) DCF becomes mandatory.</inlineHelpText>
    <label>Minimum Number Of Engineers</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_StTextKy__c.field-meta.xml
<CustomField>
    <fullName>FSM_StTextKy__c</fullName>
    <description>This Field is used for storing configuration details of Standard Text Key in Work Order for E-Forms Creation. Created as a part of SFS-1298.</description>
    <label>StTextKy</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_Suitability__c.field-meta.xml
<CustomField>
    <fullName>FSM_Suitability__c</fullName>
    <description>This Field is used for storing configuration details of Suitability for E-Forms Creation. Created as a part of SFS-1298.</description>
    <label>Suitability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <default>true</default>
                <label>E</label>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>*</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_WorkCentre__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkCentre__c</fullName>
    <description>This Field is used for storing configuration details of Service Territory in Work Order for E-Forms Creation. Created as a part of SFS-1298.</description>
    <label>Work Centre</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_DCFConfigurationWorkStep__mdt/fields/FSM_WorkStepName__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkStepName__c</fullName>
    <description>Created for SFS-4072.</description>
    <label>Work Step Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_ErrorLog__c/FSM_ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Created as part of #SFS-32</description>
    <label>FSM Error Log</label>
    <nameField>
        <displayFormat>Err-{000000}</displayFormat>
        <label>FSM Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSM Error Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/FSM_InfraDataCaptureForm2__c.object-meta.xml
<CustomObject>
    <description>Created as a part of SFS-3958</description>
    <label>Infra Data Capture Form 2</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Infra Data Capture Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 2</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Status__c.field-meta.xml
<CustomField>
    <fullName>FSM_Status__c</fullName>
    <description>Created as a part of SFS-3958</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_WorkStep__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as a part of SFS-3958</description>
    <label>Work Step</label>
    <referenceTo>WorkStep</referenceTo>
    <relationshipLabel>FSM_InfraDataCaptureForm2</relationshipLabel>
    <relationshipName>FSM_InfraDataCaptureForm2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <description>SFS-110</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waste Infra</fullName>
            </value>
            <value>
                <fullName>Water Infra</fullName>
            </value>
            <value>
                <fullName>Water Non Infra</fullName>
            </value>
            <value>
                <fullName>Waste Non Infra</fullName>
            </value>
            <value>
                <fullName>Bio Resource</fullName>
            </value>
            <value>
                <fullName>Developer Services</fullName>
            </value>
            <value>
                <fullName>Metering</fullName>
            </value>
            <value>
                <fullName>Green Recovery</fullName>
            </value>
            <value>
                <fullName>WasteNon Infra</fullName>
                <isActive>false</isActive>
                <label>WasteNon Infra</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_Suitability__c.field-meta.xml
<CustomField>
    <fullName>FSM_Suitability__c</fullName>
    <description>Created as a part of SFS-1298.(E = Excavation ,C = Covers ,R = Reinstatement ,D = Defect)
Updated as part of SFI-1616</description>
    <label>Suitability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>Excavation</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cover</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Reinstatement</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Defective Reinstatement Repair</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No notice required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkStep/fields/FSM_AlternativeFormsGroup__c.field-meta.xml
<CustomField>
    <fullName>FSM_AlternativeFormsGroup__c</fullName>
    <description>Created as part of SFS-6569. Any one of the forms under this group requires completion. Also referenced in FSM_DCFConfigurationWorkStep metadata.</description>
    <inlineHelpText>Any one of the forms under this group requires completion.</inlineHelpText>
    <label>Alternative Form&apos;s Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sewerage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkStep/fields/FSM_MandatoryOnSuspend__c.field-meta.xml
<CustomField>
    <fullName>FSM_MandatoryOnSuspend__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this DCF is mandatory for suspension. SFS-6571</description>
    <inlineHelpText>If checked, this DCF is mandatory for suspension.</inlineHelpText>
    <label>Mandatory On Suspend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkStep/fields/FSM_MaxInstance__c.field-meta.xml
<CustomField>
    <fullName>FSM_MaxInstance__c</fullName>
    <description>Created as part of SFS-6573. Maximum number of completed forms permitted Work Step. When DCF flow is launched it first checks for completed forms against this number.</description>
    <inlineHelpText>Maximum number of completed forms permitted under this workstep.</inlineHelpText>
    <label>Max Instance</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Waste Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Waste Non Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Water Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Water Non Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Bio Resource</fullName>
    </customValue>
    <customValue>
        <fullName>Developer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Metering</fullName>
    </customValue>
    <customValue>
        <fullName>Green Recovery</fullName>
        <isActive>false</isActive>
        <label>Green Recovery</label>
    </customValue>
    <description>STW Business Unit</description>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSM_InvocableDcfConfiguration.cls
/*===========================================================================================================================
@Author      : Leena B
@Description : This Class is used to get DCF Forms for WorkStep in WorkOrder Based on Configurations stored in MetaData.
@Description : Created as part of user story #SFS-1298
@Test Class  : FSM_InvocableDcfConfiguration_Test
@Date        : 3rd August 2023
@Modified By : Leena B , #SFS-4475, #SFS-4476
==============================================================================================================================*/
public with sharing class FSM_InvocableDcfConfiguration {
    // List to store all records of configurationWorkSteps
    static List<FSM_DCFConfigurationWorkStep__mdt> configurationWorkSteps = new List<FSM_DCFConfigurationWorkStep__mdt>();

    @InvocableMethod(Label='FetchDcfConfiguration')
    public static List<List<FSM_DCFConfigurationWorkStep__mdt>> getFormNames(List<InputParams> conditions) {
        system.debug('params --> ' + conditions);

        List<List<FSM_DCFConfigurationWorkStep__mdt>> formsList = new List<List<FSM_DCFConfigurationWorkStep__mdt>>();
        Map<Id, List<FSM_DCFConfigurationWorkStep__mdt>> woDCFMap = new Map<Id, List<FSM_DCFConfigurationWorkStep__mdt>>();

        try {
            // Group input conditions by business unit for optimized processing
            Map<String, List<InputParams>> buToInputs = new Map<String, List<InputParams>>();
            for (InputParams param : conditions) {
                if (!buToInputs.containsKey(param.businessUnit)) {
                    buToInputs.put(param.businessUnit, new List<InputParams>());
                }
                buToInputs.get(param.businessUnit).add(param);
            }
           //Fetch all unique Business Units from input and query corresponding metadata records
            Set<String> allBusinessUnits = getBusinessUnits(conditions);
            configurationWorkSteps = [
                SELECT Id, DeveloperName, FSM_BusinessUnit__c, FSM_DCFformName__c,
                       FSM_IsMandatory__c, FSM_MandatoryOnSuspend__c, FSM_MaxInstance__c, FSM_NoEngonOP__c,
                       FSM_StTextKy__c, FSM_Suitability__c, MasterLabel, FSM_WorkCentre__c, FSM_WorkStepName__c,
                       FSM_AlternativeFormsGroup__c
                FROM FSM_DCFConfigurationWorkStep__mdt
                WHERE FSM_BusinessUnit__c IN :allBusinessUnits
                WITH SECURITY_ENFORCED
                ORDER BY MasterLabel ASC
            ];
           //Iterate through each business unit group and match metadata records
            for (String businessUnit : buToInputs.keySet()) {
                List<InputParams> relatedInputs = buToInputs.get(businessUnit);
                for (FSM_DCFConfigurationWorkStep__mdt mdt : configurationWorkSteps) {
                    if (mdt.FSM_BusinessUnit__c != null && mdt.FSM_BusinessUnit__c != businessUnit && mdt.FSM_BusinessUnit__c != '*') {
                        continue;
                    }

                    for (InputParams inpt : relatedInputs) {
                        Boolean check1, check2, check3, check4;
                        String workStepName = mdt.FSM_WorkStepName__c;
                      //Match Work Centre with support for wildcards
                        check1 = ((mdt.FSM_WorkCentre__c == '*') ||
                            (mdt.FSM_WorkCentre__c != NULL && mdt.FSM_WorkCentre__c.startswith('*') && mdt.FSM_WorkCentre__c.endsWith('*') && inpt.serviceTerritory.contains(mdt.FSM_WorkCentre__c.Substring(1, mdt.FSM_WorkCentre__c.length() - 1))) ||
                            (mdt.FSM_WorkCentre__c != NULL && mdt.FSM_WorkCentre__c.startswith('*') && inpt.serviceTerritory.endsWith(mdt.FSM_WorkCentre__c.Substring(1))) ||
                            (mdt.FSM_WorkCentre__c != NULL && mdt.FSM_WorkCentre__c.endsWith('*') && inpt.serviceTerritory.startsWith(mdt.FSM_WorkCentre__c.Substring(0, mdt.FSM_WorkCentre__c.length() - 1))));
                      //Match Standard Text Key with support wildcards 
                        check2 = ((mdt.FSM_StTextKy__c == '*') ||
                            (mdt.FSM_StTextKy__c != NULL && mdt.FSM_StTextKy__c.startswith('*') && mdt.FSM_StTextKy__c.endsWith('*') && inpt.standardTextKey.contains(mdt.FSM_StTextKy__c.Substring(1, mdt.FSM_StTextKy__c.length() - 1))) ||
                            (mdt.FSM_StTextKy__c != NULL && mdt.FSM_StTextKy__c.startswith('*') && inpt.standardTextKey.endsWith(mdt.FSM_StTextKy__c.Substring(1))) ||
                            (mdt.FSM_StTextKy__c != NULL && mdt.FSM_StTextKy__c.endsWith('*') && inpt.standardTextKey.startsWith(mdt.FSM_StTextKy__c.Substring(0, mdt.FSM_StTextKy__c.length() - 1))) ||
                            (mdt.FSM_StTextKy__c != NULL && mdt.FSM_StTextKy__c == inpt.standardTextKey));
                      //Match Suitability 
                        check3 = (mdt.FSM_Suitability__c == '*' || (mdt.FSM_Suitability__c != NULL && mdt.FSM_Suitability__c == inpt.suitability) || (mdt.FSM_Suitability__c == NULL && String.isBlank(inpt.suitability)));
                        //Match conditionally based on business unit type
                        Set<String> nonInfraBU = new Set<String>{'Waste Non Infra', 'Water Non Infra', 'Bio Resource'};
                        if (nonInfraBU.contains(inpt.businessUnit)) {
                            check4 = ((mdt.FSM_BusinessUnit__c == '*' || (mdt.FSM_BusinessUnit__c != NULL && mdt.FSM_BusinessUnit__c == inpt.businessUnit)) &&
                                (String.isBlank(mdt.FSM_NoEngonOP__c) ||
                                (String.isNotBlank(mdt.FSM_NoEngonOP__c) && mdt.FSM_NoEngonOP__c.contains('*')) ||
                                (String.isNotBlank(mdt.FSM_NoEngonOP__c) && inpt.minimumCrewSize != null && inpt.minimumCrewSize >= Integer.valueOf(mdt.FSM_NoEngonOP__c))));
                        } else {
                            check4 = (String.isBlank(mdt.FSM_BusinessUnit__c) ||
                                String.isBlank(mdt.FSM_NoEngonOP__c) ||
                                (String.isNotBlank(mdt.FSM_NoEngonOP__c) && mdt.FSM_NoEngonOP__c.contains('*')) ||
                                (String.isNotBlank(mdt.FSM_NoEngonOP__c) && inpt.minimumCrewSize != null && inpt.minimumCrewSize >= Integer.valueOf(mdt.FSM_NoEngonOP__c)));
                        }
                      //If all check pass, add to the map for that Work Order
                        if (check1 && check2 && check3 && check4) {
                            if (!woDCFMap.containsKey(inpt.workorderId)) {
                                woDCFMap.put(inpt.workorderId, new List<FSM_DCFConfigurationWorkStep__mdt>());
                            }
                            woDCFMap.get(inpt.workorderId).add(mdt);
                        }
                    }
                }
            }
            //If no records found, return null
            if (woDCFMap.isEmpty()) {
                return null;
            }
            //Remove duplicates per Work Order based on work step name
            woDCFMap = dedupeDCFConfigMap(woDCFMap);

            for (InputParams request : conditions) {
                List<FSM_DCFConfigurationWorkStep__mdt> formNames = woDCFMap.containsKey(request.workorderId) ? woDCFMap.get(request.workorderId) : new List<FSM_DCFConfigurationWorkStep__mdt>();
                formsList.add(formNames);
            }
          
            return formsList;

        } catch (Exception ex) {
            FSM_ErrorLog__c testerrorlog = new FSM_Utility.ErrorLogCreator()
                .setClassName('FSM_InvocableDcfConfiguration')
                .setErrorMessage(ex.getMessage())
                .setLineNumber(String.valueOf(ex.getLineNumber()))
                .setMethodName('getFormNames')
                .setStackTrace(ex.getStackTraceString())
                .create();
            return null;
        }
    }
/********************************************************************************************************
@Author      : Hareesh Mohan
@Description : Returns the business units from flow variables, which will be used to query custom metadata configuration for worksteps.
@Description : Created as part of user story #SFS-6572
@Date        : 22nd July 2024
********************************************************************************************************/ 
    private static Set<String> getBusinessUnits(List<InputParams> flowInputs) {
        Set<String> businessUnits = new Set<String>();
        for (InputParams input : flowInputs) {
            businessUnits.add(input.businessUnit);
        }
        businessUnits.add(null);
        businessUnits.add('*');
        return businessUnits;
    }
/********************************************************************************************************
@Author      : Hareesh Mohan
@Description : Returns unique sets of worksteps for a workorder. Priority is given to the Workstep with Is_Mandatory = TRUE.
@Description : Created as part of user story #SFS-6572
@Date        : 22nd July 2024
********************************************************************************************************/
    private static Map<Id, List<FSM_DCFConfigurationWorkStep__mdt>> dedupeDCFConfigMap(Map<Id, List<FSM_DCFConfigurationWorkStep__mdt>> woToDCFConfigMap) {
        for (Id workOrderId : woToDCFConfigMap.keySet()) {
            Map<String, FSM_DCFConfigurationWorkStep__mdt> uniqueWorkSteps = new Map<String, FSM_DCFConfigurationWorkStep__mdt>();
            for (FSM_DCFConfigurationWorkStep__mdt workStep : woToDCFConfigMap.get(workOrderId)) {
                String workStepName = workStep.FSM_WorkStepName__c;
                if (!uniqueWorkSteps.containsKey(workStepName) || (workStep.FSM_IsMandatory__c == true && uniqueWorkSteps.get(workStepName).FSM_IsMandatory__c == false)) {
                    uniqueWorkSteps.put(workStepName, workStep);
                }
            }
            woToDCFConfigMap.put(workOrderId, new List<FSM_DCFConfigurationWorkStep__mdt>(uniqueWorkSteps.values()));
        }
        return woToDCFConfigMap;
    }
/********************************************************************************************************
@Author      : Hareesh Mohan
@Description : Returns if the workstep has exhausted the maximum number of DCF records under it.
@Description : Created as part of user story #SFS-6573
@Date        : 12th Aug 2024
********************************************************************************************************/
    @AuraEnabled(cacheable = true)
    public static Boolean hasDCFLimitReached(String workstepId) {
        Boolean hasLimitReached = false;
        List<FSM_DataCaptureFormInfra__c> completedWorksteps = [
            SELECT Id, FSM_WorkStep__r.FSM_MaxInstance__c
            FROM FSM_DataCaptureFormInfra__c
            WHERE FSM_WorkStep__c = :workstepId
            AND FSM_Status__c = 'Completed'
            AND FSM_WorkStep__c != null
            AND FSM_WorkStep__r.FSM_MaxInstance__c != null
        ];
        if (!completedWorksteps.isEmpty() && completedWorksteps.size() >= Integer.valueOf(completedWorksteps[0].FSM_WorkStep__r.FSM_MaxInstance__c)) {
            hasLimitReached = true;
        }
        if (!hasLimitReached) {
            List<FSM_InfraDataCaptureForm2__c> completedDCF2Worksteps = [
                SELECT Id, FSM_WorkStep__r.FSM_MaxInstance__c
                FROM FSM_InfraDataCaptureForm2__c
                WHERE FSM_WorkStep__c = :workstepId
                AND FSM_Status__c = 'Completed'
                AND FSM_WorkStep__c != null
                AND FSM_WorkStep__r.FSM_MaxInstance__c != null
            ];
            if (!completedDCF2Worksteps.isEmpty() && completedDCF2Worksteps.size() >= Integer.valueOf(completedDCF2Worksteps[0].FSM_WorkStep__r.FSM_MaxInstance__c)) {
                hasLimitReached = true;
            }
        }
        return hasLimitReached;
    }
/********************************************************************************************************
@Author      : Leena B
@Description : This is invocable Variables getting called from flows.
@Description : Created as part of user story #SFS-1298
@Date        : 3rd August 2023
********************************************************************************************************/ 
    public class InputParams {
        @InvocableVariable public String serviceTerritory;
        @InvocableVariable public String standardTextKey;
        @InvocableVariable public Integer minimumCrewSize;
        @InvocableVariable public String suitability;
        @InvocableVariable public String workorderId;
        @InvocableVariable public String businessUnit;
    }
}