force-app/main/default/objects/FSM_DataCaptureFormInfra__c/FSM_DataCaptureFormInfra__c.object-meta.xml
<CustomObject>
    <description>Data capture form structure for Infra BU only, SFI-35 and SFS-1950</description>
    <label>Infra Data Capture Form 1</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Data Capture Form Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 1</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_Generate_PDF__c.field-meta.xml
<CustomField>
    <fullName>FSM_Generate_PDF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate PDF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_WorkPlanTemplateMapping__mdt/FSM_WorkPlanTemplateMapping__mdt.object-meta.xml
<CustomObject>
    <description>To store the work plan template Id, SFS-33</description>
    <label>Work Plan Template Mapping</label>
    <pluralLabel>Work Plan Template Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSM_WorkPlanTemplateMapping__mdt/fields/FSM_RecordTypeDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>FSM_RecordTypeDeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>SFS-33</description>
    <label>Record Type Developer Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FSM_WorkPlanTemplateMapping__mdt/fields/FSM_WorkPlanTemplateName__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkPlanTemplateName__c</fullName>
    <description>SFS-33</description>
    <label>Work Plan Template Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSM_DCFInfratriggerTest.cls
/********************************************************************************************************
@Author      : Aishwarya Bhosale
@Description : This class is created to cover FSM_DCFInfraTriggerHelper, FSM_DCFInfraTriggerHandler, FSM_DCFInfraTrigger
@Description : Created as part of user story #SFS-3841
@Date        : 15-Dec-2023
********************************************************************************************************/
@isTest
public class FSM_DCFInfratriggerTest {
     @testsetup
    static void testSetup(){
      FSM_WorkPlanTemplateMapping__mdt woMdt = [Select MasterLabel,FSM_RecordTypeDeveloperName__c,FSM_WorkPlanTemplateName__c from FSM_WorkPlanTemplateMapping__mdt limit 1];
        
        WorkPlanTemplate woTemp = new FSM_TestDataFactory.WorkPlanTemplateCreator().setName(woMdt.FSM_WorkPlanTemplateName__c).setIsActive(true).create();
         
        WorkStepTemplate woStep = new FSM_TestDataFactory.WorkStepTemplateCreator().setName('Test workStep').setIsActive(true).create();
        
        WorkPlanTemplateEntry woEntry = new FSM_TestDataFactory.WorkPlanTemplateEntryCreator().setWorkPlanTemplateId(woTemp.Id).setWorkStepTemplateId(woStep.Id).create();
         Account acc=new FSM_TestDataFactory.AccountCreator().setName('test acc').create();
        Contact con=new FSM_TestDataFactory.ContactCreator().setFirstName('test').setLastName('testsurname').setAccount(acc.id).setEmail('no-reply@defaultemail.com').create();
        new FSM_TestDataFactory.CaseCreator().setStatus('New').setOrigin('Web').setContactName('Jon Hall').setContactEmail('jon.hall@gmail.com').create();        
        
        WorkOrder wo = new FSM_TestDataFactory.WorkOrderCreator().setExternalId('testId').setStatus('New').setBusinessUnit('Waste Infra').create();
        DateTime earliestdte = datetime.newInstance(2023, 11, 15, 12, 30, 0);
		 DateTime duedate = datetime.newInstance(2023, 11, 15, 13, 30, 0);
        boolean pdfgenerate=false;
        //Id recTypeId = Schema.SObjectType.ServiceAppointment.getRecordTypeInfosByDeveloperName().get(FSM_Constants.RECORDTYPE_WASTEINFRA).getRecordTypeId();
        id rectype=Schema.SObjectType.ServiceAppointment.getRecordTypeInfosByDeveloperName().get(FSM_Constants.RECORDTYPE_WASTEINFRA).getRecordTypeId();
          id fwrrectype=Schema.SObjectType.FSM_DataCaptureFormInfra__c.getRecordTypeInfosByDeveloperName().get(FSM_Constants.RECORDTYPE_INFRAFOLLOWONWORKREQUEST).getRecordTypeId();
        ServiceAppointment sv= new FSM_TestDataFactory.ServiceAppointmentCreator().setRecordType(rectype).setParentRecordId(wo.id).setStatus('New').setEarliestStartTime(earliestdte).setDueDate(duedate).create();
    FSM_DataCaptureFormInfra__c dcf=new FSM_TestDataFactory.DataCaptureFormInfraCreator().setWorkorder(wo.id).setGeneratepdf(pdfgenerate).setRecordTypeId(fwrrectype).create();
        ContentVersion cv1 = new FSM_TestDataFactory.ContentVersionCreator().setPathOnClient('Site1.jpeg').setTitle('Site1').setVersionData(Blob.valueOf( 'Testing content version')).setRelatedrecordId(dcf.id).create();
    ContentVersion cv2 = new FSM_TestDataFactory.ContentVersionCreator().setPathOnClient('Site2.jpeg').setTitle('Site2').setVersionData(Blob.valueOf( 'Testing content version')).setRelatedrecordId(dcf.id).create();
         ContentVersion cv3 = new FSM_TestDataFactory.ContentVersionCreator().setPathOnClient('sketch.jpeg').setTitle('sketch.jpeg').setVersionData(Blob.valueOf( 'Testing content version')).setRelatedrecordId(dcf.id).create();
    ContentVersion cv4 = new FSM_TestDataFactory.ContentVersionCreator().setPathOnClient('Banner.jpeg').setTitle('Banner.jpeg').setVersionData(Blob.valueOf( 'Testing content version')).setRelatedrecordId(dcf.id).create();
   
    }
    
    @isTest
    static void testgeneratepdf(){
 		Test.startTest();
        FSM_DataCaptureFormInfra__c dcfrec=[Select id,FSM_Generate_PDF__c from FSM_DataCaptureFormInfra__c LIMIT 1];
       	dcfrec.FSM_Generate_PDF__c=true;
        update dcfrec;
        Test.stopTest();        
    }

}