force-app/main/default/objects/FSM_DataCaptureFormInfra__c/FSM_DataCaptureFormInfra__c.object-meta.xml
<CustomObject>
    <description>Data capture form structure for Infra BU only, SFI-35 and SFS-1950</description>
    <label>Infra Data Capture Form 1</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Data Capture Form Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 1</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_Generate_PDF__c.field-meta.xml
<CustomField>
    <fullName>FSM_Generate_PDF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate PDF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as part of SFS-1950</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>FSM_DataCaptureFormInfras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/recordTypes/Infra_Follow_On_Work_Request.recordType-meta.xml
<RecordType>
    <fullName>Infra_Follow_On_Work_Request</fullName>
    <active>true</active>
    <description>SFS-1317</description>
    <label>Infra Follow On Work Request</label>
</RecordType>

force-app/main/default/classes/FSM_DCFInfraTriggerHelper.cls
/********************************************************************************************************
@Author      : Aishwarya Bhosale
@Description : This class is used to call vf page for pdf creation of dcf infra form.
@Description : Created as part of user story #SFS-3841
@Description : Invoked from FSM_DCFInfraTriggerHandler class
@Test Class  : FSM_DCFInfratriggerTest
@Date        : 15-Dec-2023
********************************************************************************************************/
public with sharing class FSM_DCFInfraTriggerHelper {
    public void generatePdf(Map<Id,sObject> newMap,Map<Id,sObject> oldMap){
         Map<Id, FSM_DataCaptureFormInfra__c> allNewDCF=(Map<Id, FSM_DataCaptureFormInfra__c>)newMap; //collecting all updated Data capture form infra records
        Map<Id, FSM_DataCaptureFormInfra__c> allOldDCF=(Map<Id, FSM_DataCaptureFormInfra__c>)oldMap; //collecting all updated Data capture form infra records old value
        List<FSM_DataCaptureFormInfra__c>dcfinfraUpdtList=new List<FSM_DataCaptureFormInfra__c>();
        for(FSM_DataCaptureFormInfra__c cmp : allNewDCF.values()) {
            if((cmp.FSM_Generate_PDF__c!=allOldDCF.get(cmp.Id).FSM_Generate_PDF__c) && (allOldDCF.get(cmp.Id).FSM_Generate_PDF__c==false))
               {	
                   system.debug('data capture form id'+cmp);
                    String woRecordId = [Select Id,FSM_WorkOrder__c from FSM_DataCaptureFormInfra__c where id=:cmp.Id AND RecordType.DeveloperName = 'Infra_Follow_On_Work_Request' Limit 1].FSM_WorkOrder__c;
                    ServiceAppointment sa = [Select Id from ServiceAppointment where ParentRecordId=:woRecordId order by createdDate desc Limit 1];
                   try{
                       
                       FSM_sketchCls.pdfCreation(sa.Id,cmp.Id);
                     
                      }catch(Exception e){
                       system.debug('error'+e);
                   }
               }else{
                   system.debug('do nothing');
               }
 
    }
     
}
    
}