force-app/main/default/objects/FSM_DataCaptureFormInfra__c/FSM_DataCaptureFormInfra__c.object-meta.xml
<CustomObject>
    <description>Data capture form structure for Infra BU only, SFI-35 and SFS-1950</description>
    <label>Infra Data Capture Form 1</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Data Capture Form Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 1</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_Medium__c.field-meta.xml
<CustomField>
    <fullName>FSM_Medium__c</fullName>
    <defaultValue>&apos;MOBI&apos;</defaultValue>
    <description>SFI-1233, Default value is set to MOBI</description>
    <label>Medium</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_NoOfEformsOfSameType__c.field-meta.xml
<CustomField>
    <fullName>FSM_NoOfEformsOfSameType__c</fullName>
    <description>sfi-1230</description>
    <label>No of EForms of same type</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>FSM_ServiceResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as part of SFS-1950, SFS-2982</description>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipName>FSM_DataCaptureFormInfras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_ServiceTerritory__c.field-meta.xml
<CustomField>
    <fullName>FSM_ServiceTerritory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created As part of SFI-35 for Record sharing based on Territory and for future purpose as well.</description>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipName>Data_Capture_Form_Infras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as part of SFS-1950</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>FSM_DataCaptureFormInfras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/recordTypes/FSM_ValveManagement.recordType-meta.xml
<RecordType>
    <fullName>FSM_ValveManagement</fullName>
    <active>true</active>
    <description>SFS-1325</description>
    <label>Network Management Form</label>
</RecordType>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/recordTypes/Infra_Follow_On_Work_Request.recordType-meta.xml
<RecordType>
    <fullName>Infra_Follow_On_Work_Request</fullName>
    <active>true</active>
    <description>SFS-1317</description>
    <label>Infra Follow On Work Request</label>
</RecordType>

force-app/main/default/objects/FSM_DataCaptureFormNonInfra__c/FSM_DataCaptureFormNonInfra__c.object-meta.xml
<CustomObject>
    <description>Data capture form structure for Non-Infra BU only, SFI-35</description>
    <label>Data Capture Form Non Infra</label>
    <nameField>
        <displayFormat>DCFNONINF-{000000}</displayFormat>
        <label>Data Capture Form Non Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Capture Form Non Infras</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DataCaptureFormNonInfra__c/fields/FSM_DCFHierarchyLevel__c.field-meta.xml
<CustomField>
    <fullName>FSM_DCFHierarchyLevel__c</fullName>
    <defaultValue>1</defaultValue>
    <description>SFI-2041</description>
    <label>DCF Hierarchy Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormNonInfra__c/fields/FSM_Medium__c.field-meta.xml
<CustomField>
    <fullName>FSM_Medium__c</fullName>
    <defaultValue>&apos;MOBI&apos;</defaultValue>
    <description>SFI-1801</description>
    <label>Medium</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormNonInfra__c/fields/FSM_NoOfEformsOfSameType__c.field-meta.xml
<CustomField>
    <fullName>FSM_NoOfEformsOfSameType__c</fullName>
    <description>SFI-1801</description>
    <label>No of EForms of same type</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormNonInfra__c/fields/FSM_ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>FSM_ServiceResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look-up to Service resource SFI-35</description>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Data Capture Form Non Infras</relationshipLabel>
    <relationshipName>Data_Capture_Form_Non_Infras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormNonInfra__c/fields/FSM_ServiceTerritory__c.field-meta.xml
<CustomField>
    <fullName>FSM_ServiceTerritory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as part of SFI-35 for record sharing based on territory and for future use as well</description>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Data Capture Form Non Infras</relationshipLabel>
    <relationshipName>Data_Capture_Form_Non_Infras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormNonInfra__c/fields/FSM_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Work Order Lookup SFI-35</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Data Capture Form Non Infras</relationshipLabel>
    <relationshipName>Data_Capture_Form_Non_Infras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormNonInfra__c/recordTypes/FSM_ValveManagement.recordType-meta.xml
<RecordType>
    <fullName>FSM_ValveManagement</fullName>
    <active>true</active>
    <label>Valve Management</label>
</RecordType>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/FSM_DCFLineItemInfra__c.object-meta.xml
<CustomObject>
    <description>Created as part of SFS-1950</description>
    <label>Infra Data Capture Line Item 1</label>
    <nameField>
        <displayFormat>DCFLI-{0000}</displayFormat>
        <label>Data Capture Form Line Item Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Line Item 1</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/fields/FSM_DataCaptureFormInfra__c.field-meta.xml
<CustomField>
    <fullName>FSM_DataCaptureFormInfra__c</fullName>
    <description>Created as part of SFS-1950</description>
    <label>Data Capture Form Infra</label>
    <referenceTo>FSM_DataCaptureFormInfra__c</referenceTo>
    <relationshipName>FSM_DataCaptureFormLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/fields/FSM_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as part of SFS-1950</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>FSM_DataCaptureFormLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/recordTypes/FSM_ValveManagement.recordType-meta.xml
<RecordType>
    <fullName>FSM_ValveManagement</fullName>
    <active>true</active>
    <label>Valve Management</label>
</RecordType>

force-app/main/default/objects/FSM_DCFLineItemNonInfra__c/FSM_DCFLineItemNonInfra__c.object-meta.xml
<CustomObject>
    <description>Created as part of SFS-35</description>
    <label>Data Capture Form Line Item Non Infra</label>
    <nameField>
        <displayFormat>DCFLI-{0000}</displayFormat>
        <label>Data Capture Form Line Item Non Infra Nu</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Capture Form Line Item Non Infras</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DCFLineItemNonInfra__c/fields/FSM_DataCaptureFormNonInfra__c.field-meta.xml
<CustomField>
    <fullName>FSM_DataCaptureFormNonInfra__c</fullName>
    <description>SFI-35</description>
    <label>Data Capture Form Non Infra</label>
    <referenceTo>FSM_DataCaptureFormNonInfra__c</referenceTo>
    <relationshipLabel>Data Capture Form Line Item Non Infras</relationshipLabel>
    <relationshipName>FSM_DataCaptureFormLineItemNonInfras</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemNonInfra__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SFI-35</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Data Capture Form Line Item Non Infras</relationshipLabel>
    <relationshipName>FSM_DataCaptureFormLineItemNonInfras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemNonInfra__c/recordTypes/FSM_ValveManagement.recordType-meta.xml
<RecordType>
    <fullName>FSM_ValveManagement</fullName>
    <active>true</active>
    <description>SFI-35</description>
    <label>Valve Management</label>
</RecordType>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/FSM_InfraDataCaptureForm2__c.object-meta.xml
<CustomObject>
    <description>Created as a part of SFS-3958</description>
    <label>Infra Data Capture Form 2</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Infra Data Capture Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 2</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Medium__c.field-meta.xml
<CustomField>
    <fullName>FSM_Medium__c</fullName>
    <defaultValue>&quot;MOBI&quot;</defaultValue>
    <description>SFI-1238, Default value is set to MOBI</description>
    <label>Medium</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>FSM_ServiceResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as a part of SFS-3958</description>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>FSM_InfraDataCaptureForm2</relationshipLabel>
    <relationshipName>FSM_InfraDataCaptureForm2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_ServiceTerritory__c.field-meta.xml
<CustomField>
    <fullName>FSM_ServiceTerritory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as a part of SFS-3958</description>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>FSM_InfraDataCaptureForm2</relationshipLabel>
    <relationshipName>FSM_InfraDataCaptureForm2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as a part of SFS-3958</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Infra Data Capture Form 2</relationshipLabel>
    <relationshipName>FSM_InfraDataCaptureForm2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/recordTypes/FSM_SewerageFurtherWorkRequestSCM.recordType-meta.xml
<RecordType>
    <fullName>FSM_SewerageFurtherWorkRequestSCM</fullName>
    <active>true</active>
    <description>SFS-3010</description>
    <label>Sewerage-Further Work Request (SCM)</label>
</RecordType>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/recordTypes/FSM_SewerageJobFeedback.recordType-meta.xml
<RecordType>
    <fullName>FSM_SewerageJobFeedback</fullName>
    <active>true</active>
    <label>Sewerage-Job Feedback</label>
</RecordType>

force-app/main/default/objects/FSM_InfraDataCaptureLineItem2__c/FSM_InfraDataCaptureLineItem2__c.object-meta.xml
<CustomObject>
    <description>Created as a part of SFS-3958</description>
    <label>Infra Data Capture Line Item 2</label>
    <nameField>
        <label>Infra Data Capture Line Item 2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Infra Data Capture Line Item 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_InfraDataCaptureLineItem2__c/fields/FSM_InfraDataCaptureForm2__c.field-meta.xml
<CustomField>
    <fullName>FSM_InfraDataCaptureForm2__c</fullName>
    <description>Created as part of SFI-1204</description>
    <label>Infra Data Capture Form 2</label>
    <referenceTo>FSM_InfraDataCaptureForm2__c</referenceTo>
    <relationshipLabel>FSM_InfraDataCaptureLineItem2</relationshipLabel>
    <relationshipName>FSM_InfraDataCaptureLineItem2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureLineItem2__c/fields/FSM_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>FSM_WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Infra Data Capture Line Item 2 (Work Order)</relationshipLabel>
    <relationshipName>FSM_InfraDataCaptureLineItem2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_SendDCFUpdates__e/FSM_SendDCFUpdates__e.object-meta.xml
<CustomObject>
    <description>Data Capture Form Platform Event to send DCF to 3rd party system, User Story SFI-35</description>
    <label>Send DCF Update</label>
    <pluralLabel>Send DCF Updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSM_SendDCFUpdates__e/fields/FSM_DCFLineItemsPayload__c.field-meta.xml
<CustomField>
    <fullName>FSM_DCFLineItemsPayload__c</fullName>
    <description>SFI-35</description>
    <label>DCF Line Items Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FSM_SendDCFUpdates__e/fields/FSM_DCFPayload1__c.field-meta.xml
<CustomField>
    <fullName>FSM_DCFPayload1__c</fullName>
    <description>SFI-35</description>
    <label>DCF Payload 1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FSM_SendDCFUpdates__e/fields/FSM_DCFPayload2__c.field-meta.xml
<CustomField>
    <fullName>FSM_DCFPayload2__c</fullName>
    <description>SFi-35</description>
    <label>DCF Payload 2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FSM_SendDCFUpdates__e/fields/FSM_DCFPayload3__c.field-meta.xml
<CustomField>
    <fullName>FSM_DCFPayload3__c</fullName>
    <description>SFI-35</description>
    <label>DCF Payload 3</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FSM_SendDCFUpdates__e/fields/FSM_DCFPayload4__c.field-meta.xml
<CustomField>
    <fullName>FSM_DCFPayload4__c</fullName>
    <description>SFI-35</description>
    <label>DCF Payload 4</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FSM_SendDCFUpdates__e/fields/FSM_DCFPayload5__c.field-meta.xml
<CustomField>
    <fullName>FSM_DCFPayload5__c</fullName>
    <description>SFI-35</description>
    <label>DCF Payload 5</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FSM_SendDCFUpdates__e/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <description>SFI-35</description>
    <label>Workorder SAP external Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <description>External ID</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FSM_Constants.cls
/********************************************************************************************************
@Author      : Srikanth Palla
@description : Created to declare contacts varibales used in differnet classes
********************************************************************************************************/
public with sharing class FSM_Constants {
    
    public static final integer RESPONSE_200=200;
    public static final integer RESPONSE_400=400;
    public static final string RES_SUCCESS='SUCCESS';
    public static final string NO_POLYGON='No Polygon Found';
    public static final string RES_ERROR='ERROR';
    public static final string SLOT_TYPE_2HOUR='2 hour';
    public static final string FSM_APPOINTMENT_SERVICE_NAME='CreateCustomerAppointmentWOSA'; //Added as part of SFI-261, By Srikanth Palla
    public static final string FSM_GIS_SERVICE_NAME='GIS LATLONG Conversion';
    public static final String RECORDTYPE_DEVELOPERSERVICES = 'FSM_DeveloperServices'; // [Added by Arnob Dey #SFS-318]
    public static final String RECORDTYPE_WASTENONINFRA='FSM_WasteNonInfra';//SFS-3028
    public static final String RECORDTYPE_INFRAFOLLOWONWORKREQUEST = 'Infra_Follow_On_Work_Request'; // [Added by Aishwarya Bhosale #SFS-1005]
    public static final String RECORDTYPE_SEWERAGEFURTHERWORKREQUEST ='FSM_SewerageFurtherWorkRequestSCM';//  [Added by Brajesh Kumar #SFS-5399]
    public static final String RECORDTYPE_METERING = 'FSM_Metering'; // [Added by Arnob Dey #SFS-1298]
    public static final String RECORDTYPE_WASTEINFRA = 'FSM_WasteInfra'; // [Added by Aishwarya Dey #SFS-3050]
    Public Static Final String DCF_LINEITEM_PREFIX = 'LineItem_'; //To Add a prefix to Dcf Line item field api name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DEFAULT_NODE = 'DCF'; //To Add a prefix to Dcf Line item field api name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DCF_PAYLOAD_1 = 'FSM_DCFPayload1__c'; //DCF payload field name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DCF_PAYLOAD_2 = 'FSM_DCFPayload2__c'; //DCF payload field name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DCF_PAYLOAD_3 = 'FSM_DCFPayload3__c'; //DCF payload field name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DCF_PAYLOAD_4 = 'FSM_DCFPayload4__c'; //DCF payload field name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DCF_PAYLOAD_5 = 'FSM_DCFPayload5__c'; //DCF payload field name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DCF_PAYLOAD_LINE = 'FSM_DCFLineItemsPayload__c'; //DCF payload field name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String FIRSTBRACKETSTART_DOUBLEQUOTE = '{"'; //Symbol SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DOUBLEQUOTE_COLON = '":'; //Symbol SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String FIRSTBRACKETEND_FIRSTBRACKETEND = '}}'; //Symbol SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String FIRSTBRACKETSTART = '{'; //Symbol SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String FIRSTBRACKETEND = '}'; //Symbol SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String COMMA = ','; //Symbol SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DOT = '.'; //Symbol SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String BLANK = ''; //Symbol SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String THIRDBRACKATSTART = '['; //Symbol SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String THIRDBRACKATEND = ']'; //Symbol SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String CUSTOMSYMBOL1 = '"","'; //Symbol SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String CUSTOMSYMBOL2 = ',"'; //Symbol SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DCF_INFRA = 'FSM_DataCaptureFormInfra__c'; //DCF Infra object APi name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DCF_INFRA1 = 'FSM_InfraDataCaptureForm2__c'; //DCF Infra object APi name SFI-1204, 27th Dec 2023, Subir Maji
    Public Static Final String DCF_INFRA_LINE = 'FSM_DataCaptureFormLineItems__r'; //DCF Infra Line relation APi name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DCF_INFRA_LINE1 = 'FSM_InfraDataCaptureLineItem2__r'; //DCF Infra Line relation APi name SFI-1204, 27th Dec 2023, Subir Maji
    Public Static Final String DCF_NONINFRA_LINE = 'FSM_DataCaptureFormLineItemNonInfras__r'; //DCF Non Infra Line relation APi name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DCF_NONINFRA = 'FSM_DataCaptureFormNonInfra__c'; //DCF non Infra object APi name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DCF_BASEQUERY = 'SELECT id, FSM_DCFHierarchyLevel__c, FSM_NoOfEformsOfSameType__c, FSM_Medium__c, RecordType.developerName, FSM_WorkOrder__c, FSM_ServiceResource__c, FSM_ServiceTerritory__c, FSM_WorkOrder__r.FSM_ExternalId__c, FSM_WorkOrder__r.FSM_OrderNumber__c ,FSM_WorkOrder__r.FSM_OperationNumber__c , FSM_WorkOrder__r.FSM_NotificationNumber__c,FSM_WorkOrder__r.RecordType.DeveloperName,FSM_ServiceResource__r.Name';//DCF object Query start SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String DCF_LINE_BASEQUERY = ', (SELECT id, FSM_LineItem__c ';//DCF Line object Query start SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String QUERYHELPER1 = ' FROM '; //DCF object Query SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String QUERYEND = ' WHERE ID IN : allId WITH SECURITY_ENFORCED'; //DCF object Query End SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String WORKORDER_R = 'FSM_WorkOrder__r'; //Work Order field api relation name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String SERVICERESOURCE_R = 'FSM_ServiceResource__r'; //Service resource field api relation name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String SERVICETERRITORY_R = 'FSM_ServiceTerritory__r'; //Service territory field api relation name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String WORKORDER_C = 'FSM_WorkOrder__c'; //Work Order field api name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String SERVICERESOURCE_C = 'FSM_ServiceResource__c'; //Service resource field api name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String SERVICETERRITORY_C = 'FSM_ServiceTerritory__c'; //Service territory field api name SFI-35, 7th Aug 2023, Subir Maji
    Public Static Final String RESPONSE_PAYLOAD_START = '{"attributes":{"type":"FSM_SendDCFUpdates__e"},"FSM_FormName__c":"'; //Response Payload Start SFI-35, 7th Aug 2023, Subir Maji
    public static final string  DCF_SCHEDULING_POLICY='Test Policy';//SFI-35 used in test class
    public static final string 	OH_BUSINESS_UNIT='Developer Services';
    public static final string 	BUSINESS_UNIT='Developer Services';
    public static final string 	OH_AM_PM='AM/Pm Operating Hours';
    public static final string 	DURATION='AMPM';
    public static final string 	RESOURCE_NAME='Testing Resource';
    public static final string 	WO_BUSINESS_UNIT='Waste Infra';
    public static final string 	FORMTYPE='FSM_ValveManagement';
    public static final string 	FORMTYPE_INFRA1='FSM_SewerageJobFeedback';//Added as part of SFI-1204
	public static final string  STATUS_COMPLETED='Completed';
    public static final string  STATUS_NEW='New';
    public static final string  GIS_ENDPOINT = 'callout:calloutGIS'; //Added As part of SFI-21
    public static final string  CUSTOMSYMBOL3 = '{"XCord":"'; //Added As part of SFI-21
    public static final string  CUSTOMSYMBOL4 = '","YCord" :"'; //Added As part of SFI-21
    public static final string  CUSTOMSYMBOL5 = '","LayerRefid":"'; //Added As part of SFI-21
    public static final string  CUSTOMSYMBOL6 = '"}'; //Added As part of SFI-21
    public static final string  CUSTOMSYMBOL7 = '""'; //Added As part of SFI-21
    public static final string  RESTMETHODPOST = 'POST'; //Added As part of SFI-21
    public static final string  HEADER1 = 'proxyPort'; //Added As part of SFI-21
    public static final string  HEADER2 = '443'; //Added As part of SFI-21
    public static final string  HEADER3 = 'Content-Type'; //Added As part of SFI-21
    public static final string  HEADER4 = 'application/json;charset=UTF-8'; //Added As part of SFI-21
    public static final string  NO_VALUE_GIS = 'None'; //Added As part of SFI-21
    public static final string PREFIX='[';//Added As part of SFI-1557
    public static final string SUFIX=']';//Added As part of SFI-1557
    public static final string FILEUPLOAD_SERVCIE='Send Upload Attachments';//Added As part of SFI-1213
    public static final string MAILJET_BCC_NAME='Customer';//Added As part of SFI-1821
    
    public static final string ORDER_BY=' Order By ';//added as part of SFI-2974 by Subir Maji 22nd Oct 24
    public static final string ORDER_BY_ASC=' ASC';//added as part of SFI-2974 by Subir Maji 22nd Oct 24
    public static final string ORDER_BY_DESC=' DESC';//added as part of SFI-2974 by Subir Maji 22nd Oct 24
}