force-app/main/default/objects/FSM_DataCaptureFormInfra__c/FSM_DataCaptureFormInfra__c.object-meta.xml
<CustomObject>
    <description>Data capture form structure for Infra BU only, SFI-35 and SFS-1950</description>
    <label>Infra Data Capture Form 1</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Data Capture Form Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 1</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_SiteNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_SiteNumber__c</fullName>
    <description>SFS-1318</description>
    <label>Site Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/recordTypes/FSM_ValveManagement.recordType-meta.xml
<RecordType>
    <fullName>FSM_ValveManagement</fullName>
    <active>true</active>
    <description>SFS-1325</description>
    <label>Network Management Form</label>
</RecordType>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/FSM_DCFLineItemInfra__c.object-meta.xml
<CustomObject>
    <description>Created as part of SFS-1950</description>
    <label>Infra Data Capture Line Item 1</label>
    <nameField>
        <displayFormat>DCFLI-{0000}</displayFormat>
        <label>Data Capture Form Line Item Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Line Item 1</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/fields/FSM_DataCaptureFormInfra__c.field-meta.xml
<CustomField>
    <fullName>FSM_DataCaptureFormInfra__c</fullName>
    <description>Created as part of SFS-1950</description>
    <label>Data Capture Form Infra</label>
    <referenceTo>FSM_DataCaptureFormInfra__c</referenceTo>
    <relationshipName>FSM_DataCaptureFormLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/fields/FSM_GridNo__c.field-meta.xml
<CustomField>
    <fullName>FSM_GridNo__c</fullName>
    <description>Created as part of SFI-2041</description>
    <label>Grid No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/fields/FSM_LineItem__c.field-meta.xml
<CustomField>
    <fullName>FSM_LineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line Item</label>
    <referenceTo>FSM_DCFLineItemInfra__c</referenceTo>
    <relationshipLabel>Infra Data Capture Line Item 1 (Line Item)</relationshipLabel>
    <relationshipName>Infra_Data_Capture_Line_Item_1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/fields/FSM_SiteNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_SiteNumber__c</fullName>
    <description>Created as a part of SFS-6563</description>
    <label>Site No.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/fields/FSM_ValveSeqNumber__c.field-meta.xml
<CustomField>
    <fullName>FSM_ValveSeqNumber__c</fullName>
    <description>SFS-4978</description>
    <label>Valve Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/recordTypes/FSM_GridRefForExcavation.recordType-meta.xml
<RecordType>
    <fullName>FSM_GridRefForExcavation</fullName>
    <active>true</active>
    <description>SFS-1318</description>
    <label>Grid Ref for Excavation</label>
</RecordType>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/recordTypes/FSM_ValveManagement.recordType-meta.xml
<RecordType>
    <fullName>FSM_ValveManagement</fullName>
    <active>true</active>
    <label>Valve Management</label>
</RecordType>

force-app/main/default/classes/FSM_DCFInfraLine1TriggerHelper.cls
/********************************************************************************************************
@Author      : Subir Maji
@Description : This Class is used to handle all DCF Infra Line 1 related triggers
@Description : Created as part of user story #SFI-2041
@description : Invoked from FSM_DCFInfraLine1Trigger
@Test Class  : FSM_DCFInfraLine1TriggerHelperTest
@Date        : 01-Aug-2024
********************************************************************************************************/
public with sharing class FSM_DCFInfraLine1TriggerHelper {
    /********************************************************************************************************
    @Author      : Subir Maji
    @description : This method is used to populate No of line item same type and populate Grid Number.
    @description : Invoked from FSM_DCFInfraLine1TriggerHandler class
    @param newList
    @Date        : 01-Aug-2024   Created as a part of SFI-2041
    ********************************************************************************************************/
    public static void populateNoOflineSameType(List<FSM_DCFLineItemInfra__c> newList){ 
        Set<String> allRecordTypeID = new Set<String>(); //To Collect all Record type Id
        Set<String> allParentRecordID = new Set<String>(); //To Collect all Parent DCF Record Id
        Map<ID, FSM_DCFLineItemInfra__c> allExistingLine; //Collect all existing DCF Line record
        Map<ID, FSM_DataCaptureFormInfra__c> allParentRecord; //Added as part of SFI-2974 by Subir Maji 22nd Oct 24 to for collecting all parent record
        MAP<String, Integer> noOfLineSameTypeMap = new MAP<String, Integer>(); //To Create a unique Key and count for each type DCF line
        String tempUnique; //Temporary variable for keeping the unique key
        Integer tempCount = 0; //Temporary variable to keep the count
        //Fetching Record Type Id for Grid type Line item
        ID infralineitemGridRecordTypeId = Schema.SObjectType.FSM_DCFLineItemInfra__c.getRecordTypeInfosByDeveloperName()
            .get('FSM_GridRefForExcavation').getRecordTypeId();
        //Added as part of SFI-2974 by Subir Maji 22nd Oct 24 to fetch Valve Record type ID for parent record
        ID infraValveRecordTypeId= Schema.SObjectType.FSM_DataCaptureFormInfra__c.getRecordTypeInfosByDeveloperName()
            .get('FSM_ValveManagement').getRecordTypeId();
        
        //Going through the list of records to collect record type id and DCF master record id
        for(FSM_DCFLineItemInfra__c infraLine1 : newList){
            allRecordTypeID.add(infraLine1.RecordTypeId);
            allParentRecordID.add(infraLine1.FSM_DataCaptureFormInfra__c);
        }
        
        allParentRecord = new Map<ID, FSM_DataCaptureFormInfra__c> ([Select Id, RecordTypeId 
                                                                     from FSM_DataCaptureFormInfra__c
                                                                    Where ID IN : allParentRecordID WITH SECURITY_ENFORCED]);
        
        //Query all existing line item record based on record type and DCF master record
        allExistingLine = New Map<ID, FSM_DCFLineItemInfra__c>([SELECT ID, RecordTypeId, FSM_DataCaptureFormInfra__c, FSM_LineItem__c,
                                                                FSM_NoOfLineItemsEformsOfSameType__c, FSM_GridNo__c
                                                                 FROM FSM_DCFLineItemInfra__c 
                                                                 WHERE FSM_DataCaptureFormInfra__c IN : allParentRecordID
                                                                 AND RecordTypeId IN : allRecordTypeID WITH SECURITY_ENFORCED]);
        
        //If existing line item record found then prepare teh map of unique key and count
        if(allExistingLine != null && !allExistingLine.isEmpty()){
            for(FSM_DCFLineItemInfra__c infraLine1 : allExistingLine.Values()){
                //For Number of line Item of same type
                tempUnique = String.Valueof(infraLine1.FSM_DataCaptureFormInfra__c) + String.Valueof(infraLine1.RecordTypeId);
                if(noOfLineSameTypeMap.containsKey(tempUnique)){
                    tempCount = noOfLineSameTypeMap.get(tempUnique) + 1;
                    noOfLineSameTypeMap.put(tempUnique,tempCount);
                }else{
                    noOfLineSameTypeMap.put(tempUnique,1);
                }
                
                //For Grid number
                if(infraLine1.RecordTypeId == infralineitemGridRecordTypeId && infraLine1.FSM_LineItem__c != null){
                    tempUnique = String.Valueof(infraLine1.FSM_LineItem__c) + String.Valueof(infraLine1.RecordTypeId);
                    if(noOfLineSameTypeMap.containsKey(tempUnique)){
                        tempCount = noOfLineSameTypeMap.get(tempUnique) + 1;
                        noOfLineSameTypeMap.put(tempUnique,tempCount);
                    }else{
                        noOfLineSameTypeMap.put(tempUnique,1);
                    }
                }
            }
        }
        
        //Go through all new record and populate the Grid number and number of line item same type
        for(FSM_DCFLineItemInfra__c infraLine1 : newList){
            //For Number of line Item of same type
            tempUnique = String.Valueof(infraLine1.FSM_DataCaptureFormInfra__c) + String.Valueof(infraLine1.RecordTypeId);
            if(infraLine1.FSM_NoOfLineItemsEformsOfSameType__c == null){
            if(noOfLineSameTypeMap.containsKey(tempUnique)){
                tempCount = noOfLineSameTypeMap.get(tempUnique) + 1;
                infraLine1.FSM_NoOfLineItemsEformsOfSameType__c = tempCount;
                noOfLineSameTypeMap.put(tempUnique,tempCount);
            }else{
                infraLine1.FSM_NoOfLineItemsEformsOfSameType__c = 1;
                noOfLineSameTypeMap.put(tempUnique,1);
            }
            }
            
            //For Grid number
            if(infraLine1.RecordTypeId == infralineitemGridRecordTypeId && infraLine1.FSM_LineItem__c != null){
                tempUnique = String.Valueof(infraLine1.FSM_LineItem__c) + String.Valueof(infraLine1.RecordTypeId);
                if(noOfLineSameTypeMap.containsKey(tempUnique)){
                    tempCount = noOfLineSameTypeMap.get(tempUnique) + 1;
                    infraLine1.FSM_GridNo__c = tempCount;
                    infraLine1.FSM_NoOfLineItemsEformsOfSameType__c = tempCount; //IF GridNumber populated then match no of line item with GridNumber, added as part of SFI-2974 by Subir Maji 22nd Oct 24
                    noOfLineSameTypeMap.put(tempUnique,tempCount);
                }else{
                    infraLine1.FSM_GridNo__c = 1;
                    infraLine1.FSM_NoOfLineItemsEformsOfSameType__c = 1;//IF GridNumber populated then match no of line item with GridNumber, added as part of SFI-2974 by Subir Maji 22nd Oct 24
                    noOfLineSameTypeMap.put(tempUnique,1);
                }
            }
            
            //IF SiteNumber populated then match no of line item with SiteNumber, added as part of SFI-2974 by Subir Maji 22nd Oct 24
            if(infraLine1.FSM_SiteNumber__c != null){
                 infraLine1.FSM_NoOfLineItemsEformsOfSameType__c = infraLine1.FSM_SiteNumber__c;
            }
            //IF ValveSeqNumber populated then match no of line item with ValveSeqNumber, added as part of SFI-2974 by Subir Maji 22nd Oct 24
            if(infraLine1.FSM_ValveSeqNumber__c != null){
                infraLine1.FSM_NoOfLineItemsEformsOfSameType__c = infraLine1.FSM_ValveSeqNumber__c;
            }else if(infraValveRecordTypeId == allParentRecord.get(infraLine1.FSM_DataCaptureFormInfra__c).RecordTypeId){ //If Parent record type is valve and line item don't have vanve seq number then make the field blank
                infraLine1.FSM_NoOfLineItemsEformsOfSameType__c = null;
            }
        }
    }
}