force-app/main/default/objects/FSM_BatchProcess__mdt/FSM_BatchProcess__mdt.object-meta.xml
<CustomObject>
    <description>created as part of story number SFS-3024</description>
    <label>Batch Process</label>
    <pluralLabel>Batch Process</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSM_BatchProcess__mdt/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>created as part of story number SFS-3024</description>
    <label>Process Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jobs completed outside SF</fullName>
                <default>true</default>
                <label>Jobs completed outside SF</label>
            </value>
            <value>
                <fullName>Shift Round Territories</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_BatchProcess__mdt/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>created as part of story number SFS-3024</description>
    <label>Service Territory</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FSM_ErrorLog__c/FSM_ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Created as part of #SFS-32</description>
    <label>FSM Error Log</label>
    <nameField>
        <displayFormat>Err-{000000}</displayFormat>
        <label>FSM Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSM Error Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceAppointment/fields/FSM_ReasonCategory__c.field-meta.xml
<CustomField>
    <fullName>FSM_ReasonCategory__c</fullName>
    <label>Reason Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>H&amp;S</fullName>
            </value>
            <value>
                <fullName>Plant/Equipment/Vehicle</fullName>
            </value>
            <value>
                <fullName>Preparation</fullName>
            </value>
            <value>
                <fullName>Asset Data</fullName>
            </value>
            <value>
                <fullName>Asset Care</fullName>
            </value>
            <value>
                <fullName>AUTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_RejectBundle__c.field-meta.xml
<CustomField>
    <fullName>FSM_RejectBundle__c</fullName>
    <description>Created for SF-5159</description>
    <formula>AND(NOT(ISBLANK(FSSK__FSK_Work_Order__r.FSM_JobSLAInHours__c)),
IF((FSSK__FSK_Work_Order__r.FSM_JobSLAInHours__c = 36 &amp;&amp; TODAY() &gt;=  DATEVALUE((DueDate + 1))), true,
IF((FSSK__FSK_Work_Order__r.FSM_JobSLAInHours__c = 37 &amp;&amp; TODAY() &gt;= DATEVALUE((DueDate + (120/24)))), true , 
IF((FSSK__FSK_Work_Order__r.FSM_JobSLAInHours__c = 38 &amp;&amp; TODAY() &gt;= DATEVALUE((DueDate + (274/24)))), true, 
IF((FSSK__FSK_Work_Order__r.FSM_JobSLAInHours__c = 39 &amp;&amp; TODAY() &gt;= DATEVALUE((DueDate + (672/24)))),true, false)))))</formula>
    <label>Reject Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_RejectReason__c.field-meta.xml
<CustomField>
    <fullName>FSM_RejectReason__c</fullName>
    <description>Updated as a part of 5924</description>
    <label>Reject Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FSM_ReasonCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ITES</fullName>
                <label>End of shift</label>
            </value>
            <value>
                <fullName>PLER</fullName>
                <label>Emergency/Reactive Work</label>
            </value>
            <value>
                <fullName>ITUA</fullName>
                <label>Unplanned absence</label>
            </value>
            <value>
                <fullName>ITTD</fullName>
                <label>Travel delays</label>
            </value>
            <value>
                <fullName>CUNH</fullName>
                <label>CUSTOMER Not at home</label>
            </value>
            <value>
                <fullName>PLRC</fullName>
                <label>Requested by Customer</label>
            </value>
            <value>
                <fullName>SINL</fullName>
                <label>No access-Customer/Land owner</label>
            </value>
            <value>
                <fullName>CUNR</fullName>
                <label>Customer site not ready</label>
            </value>
            <value>
                <fullName>OTAW</fullName>
                <label>Adverse weather conditions</label>
            </value>
            <value>
                <fullName>OTFT</fullName>
                <label>Incorrect Skills</label>
            </value>
            <value>
                <fullName>PLOR</fullName>
                <label>Obstruction removal required</label>
            </value>
            <value>
                <fullName>OTAS</fullName>
                <label>Dangerous situation</label>
            </value>
            <value>
                <fullName>HSED</fullName>
                <label>Engineering Difficulties</label>
            </value>
            <value>
                <fullName>HSAR</fullName>
                <label>Additional resource</label>
            </value>
            <value>
                <fullName>VEIN</fullName>
                <label>Incorrect</label>
            </value>
            <value>
                <fullName>JBFN</fullName>
                <label>Part unavailable</label>
            </value>
            <value>
                <fullName>JBTE</fullName>
                <label>Not available</label>
            </value>
            <value>
                <fullName>OTMS</fullName>
                <label>System error</label>
            </value>
            <value>
                <fullName>VEBR</fullName>
                <label>Breakdown</label>
            </value>
            <value>
                <fullName>PLFW</fullName>
                <label>Further visit/work required</label>
            </value>
            <value>
                <fullName>PRNW</fullName>
                <label>No work required</label>
            </value>
            <value>
                <fullName>SINA</fullName>
                <label>No access/Parking</label>
            </value>
            <value>
                <fullName>JBTM</fullName>
                <label>Traffic Mgnt not available</label>
            </value>
            <value>
                <fullName>PRNB</fullName>
                <label>Traffic Mgnt not booked</label>
            </value>
            <value>
                <fullName>JBDO</fullName>
                <label>Duplicate operation</label>
            </value>
            <value>
                <fullName>SIWC</fullName>
                <label>Work conflict</label>
            </value>
            <value>
                <fullName>PLPD</fullName>
                <label>Permission to dig required</label>
            </value>
            <value>
                <fullName>PRTI</fullName>
                <label>Traffic Management Incorrect</label>
            </value>
            <value>
                <fullName>PRTC</fullName>
                <label>Time constraints (Day/Time)</label>
            </value>
            <value>
                <fullName>PRSR</fullName>
                <label>Same Day Rein needed</label>
            </value>
            <value>
                <fullName>AUTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FSM_AutoRejectJobBatch.cls
/********************************************************************************************************
@Author      : Nishant Kumar
@description : This class contains actual logic of a batch job for auto-reject service appointment
@description : Created as part of user story #SFS-7456
@description : SAs generated for dummy users should be forcefully rejected 24 hours after the due date of the bundle SA.
@Date        : 17-September-2024
@modified Date: 01/10/2024 
@Last Modified By : Brajesh Kumar
********************************************************************************************************/
public class FSM_AutoRejectJobBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    private String jobRunQuery;
    public static final Integer BATCH_SIZE = Integer.valueOf(System.Label.FSM_AutoRejectBathSize); //To have the Batch size
    Set<Id> territoryIds = new Set<Id>();
    
    
    /**
* @description parameterised constructor 
*/ 
    public FSM_AutoRejectJobBatch(String jobRunQuery){
        this.jobRunQuery = jobRunQuery; 
    }
    
    
    /*** @description start**/
    public Database.QueryLocator start(Database.BatchableContext bc) {
         List<FSM_BatchProcess__mdt> batchProcesses = [SELECT Process_Name__c,Service_Territory__c FROM FSM_BatchProcess__mdt WHERE Process_Name__c = 'Shift Round Territories'];
            Set<String> territoryNames = new Set<String>();
            for (FSM_BatchProcess__mdt batchProcess : batchProcesses) {
                territoryNames.add(batchProcess.Service_Territory__c);
            }
            List<ServiceTerritory> territories = [SELECT Id FROM ServiceTerritory WHERE Name IN :territoryNames];
            Set<Id> territoryIds = new Set<Id>();
            for (ServiceTerritory territory : territories) {
                territoryIds.add(territory.Id);
            }    
        if(jobRunQuery == NULL){  
               
            jobRunQuery = 'SELECT Id FROM ServiceAppointment WHERE Status = \'New\' AND IsBundleMember = TRUE AND FSM_RejectBundle__c = TRUE AND ServiceTerritoryId IN :territoryIds';
        }   
        
        System.debug('territoryIds----> '+territoryIds);
        return Database.getQueryLocator(jobRunQuery);
    }
    
    /*** @description execute**/    
    public void execute(Database.BatchableContext bc, List<ServiceAppointment> scope) {
        List<ServiceAppointment> appointmentsToUpdate = new List<ServiceAppointment>();
        for(ServiceAppointment varSa : scope) {
            ServiceAppointment sa = new ServiceAppointment();
            sa.Id = varSa.Id;
            sa.Status = 'Rejected';
            sa.FSM_ReasonCategory__c = 'AUTO';
            sa.FSM_RejectReason__c = 'AUTO';
            appointmentsToUpdate.add(sa);
        }
        // Update Service Appointments 
        if(appointmentsToUpdate.size() > 0) {
            try {
                Database.SaveResult[] updateResult = Database.update(appointmentsToUpdate,false);
                for (Integer i = 0; i < updateResult.size(); i++) {
                    if (!updateResult[i].isSuccess()) {
                        //Error ecountered              
                        for(Database.Error error : updateResult[i].getErrors()){
                            //Handle error                           
                            FSM_ErrorLog__c errorLog = new FSM_Utility.ErrorLogCreator().setClassName('FSM_AutoRejectJobBatch').setErrorMessage(error.getMessage()+' Failed record id: '+updateResult[i].getId()).setMethodName('execute').setType('Field Service').create();                                                       
                        }
                    }
                }
            } 
            //If there is an exception, log it in the error log object
            catch (Exception e) {FSM_ErrorLog__c errorLog = new FSM_Utility.ErrorLogCreator().setClassName('FSM_AutoRejectJobBatch').setErrorMessage(e.getMessage()).setLineNumber(String.ValueOF(e.getLineNumber())).setMethodName('execute').setStackTrace(e.getStackTraceString()).setType('Field Service').create();e.setMessage('Error occurred while trying to reject service appointment'); } 
        }
    }
    /*** @description finish**/
    public void finish(Database.BatchableContext bc) {
        // finish
    }
}