force-app/main/default/objects/FSL__Scheduling_Policy__c/FSL__Scheduling_Policy__c.object-meta.xml
<CustomObject>
    <label>Scheduling Policy</label>
    <nameField>
        <label>Scheduling Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduling Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/FSM_DataCaptureFormInfra__c.object-meta.xml
<CustomObject>
    <description>Data capture form structure for Infra BU only, SFI-35 and SFS-1950</description>
    <label>Infra Data Capture Form 1</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Data Capture Form Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 1</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DataCaptureFormInfra__c/fields/FSM_Status__c.field-meta.xml
<CustomField>
    <fullName>FSM_Status__c</fullName>
    <description>Created as part of SFS-1950,  SFS-2982</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_DataCaptureFormNonInfra__c/FSM_DataCaptureFormNonInfra__c.object-meta.xml
<CustomObject>
    <description>Data capture form structure for Non-Infra BU only, SFI-35</description>
    <label>Data Capture Form Non Infra</label>
    <nameField>
        <displayFormat>DCFNONINF-{000000}</displayFormat>
        <label>Data Capture Form Non Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Capture Form Non Infras</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DataCaptureFormNonInfra__c/fields/FSM_Status__c.field-meta.xml
<CustomField>
    <fullName>FSM_Status__c</fullName>
    <description>SFI-35</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>IN progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/FSM_DCFLineItemInfra__c.object-meta.xml
<CustomObject>
    <description>Created as part of SFS-1950</description>
    <label>Infra Data Capture Line Item 1</label>
    <nameField>
        <displayFormat>DCFLI-{0000}</displayFormat>
        <label>Data Capture Form Line Item Infra Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Line Item 1</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/fields/FSM_DataCaptureFormInfra__c.field-meta.xml
<CustomField>
    <fullName>FSM_DataCaptureFormInfra__c</fullName>
    <description>Created as part of SFS-1950</description>
    <label>Data Capture Form Infra</label>
    <referenceTo>FSM_DataCaptureFormInfra__c</referenceTo>
    <relationshipName>FSM_DataCaptureFormLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/fields/FSM_LineItem__c.field-meta.xml
<CustomField>
    <fullName>FSM_LineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line Item</label>
    <referenceTo>FSM_DCFLineItemInfra__c</referenceTo>
    <relationshipLabel>Infra Data Capture Line Item 1 (Line Item)</relationshipLabel>
    <relationshipName>Infra_Data_Capture_Line_Item_1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemInfra__c/fields/FSM_Status__c.field-meta.xml
<CustomField>
    <fullName>FSM_Status__c</fullName>
    <description>SFS-2983</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemNonInfra__c/FSM_DCFLineItemNonInfra__c.object-meta.xml
<CustomObject>
    <description>Created as part of SFS-35</description>
    <label>Data Capture Form Line Item Non Infra</label>
    <nameField>
        <displayFormat>DCFLI-{0000}</displayFormat>
        <label>Data Capture Form Line Item Non Infra Nu</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Capture Form Line Item Non Infras</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_DCFLineItemNonInfra__c/fields/FSM_DataCaptureFormNonInfra__c.field-meta.xml
<CustomField>
    <fullName>FSM_DataCaptureFormNonInfra__c</fullName>
    <description>SFI-35</description>
    <label>Data Capture Form Non Infra</label>
    <referenceTo>FSM_DataCaptureFormNonInfra__c</referenceTo>
    <relationshipLabel>Data Capture Form Line Item Non Infras</relationshipLabel>
    <relationshipName>FSM_DataCaptureFormLineItemNonInfras</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FSM_DCFLineItemNonInfra__c/fields/FSM_LineItem__c.field-meta.xml
<CustomField>
    <fullName>FSM_LineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SFI-2041</description>
    <label>Line Item</label>
    <referenceTo>FSM_DCFLineItemNonInfra__c</referenceTo>
    <relationshipLabel>Data Capture Form Line Item Non Infras</relationshipLabel>
    <relationshipName>Data_Capture_Form_Line_Item_Non_Infras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/FSM_InfraDataCaptureForm2__c.object-meta.xml
<CustomObject>
    <description>Created as a part of SFS-3958</description>
    <label>Infra Data Capture Form 2</label>
    <nameField>
        <displayFormat>DCFINFRA-{000000}</displayFormat>
        <label>Infra Data Capture Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infra Data Capture Form 2</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_InfraDataCaptureForm2__c/fields/FSM_Status__c.field-meta.xml
<CustomField>
    <fullName>FSM_Status__c</fullName>
    <description>Created as a part of SFS-3958</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_IntegrationLog__c/FSM_IntegrationLog__c.object-meta.xml
<CustomObject>
    <description>Created as part of #SFS-32</description>
    <label>FSM Integration Log</label>
    <nameField>
        <displayFormat>Int-{000000}</displayFormat>
        <label>FSM Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSM Integration Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/FSM_DCFJsonGeneratorTest.cls
/********************************************************************************************************
@Author 	 : Manish Jagnani
@Description : This class is used to test FSM_DCFJsonGenerator.
@description : Created as part of user story #SFI-35
@Main Class  : FSM_DCFJsonGenerator
@Date        : 7th-August-2023
********************************************************************************************************/
@istest(SeeAllData = False)
public class FSM_DCFJsonGeneratorTest {
    static Integer numberOfRecordsToCreate = 1;
    
    //This method is for test Data set-up in bulk SFI-35 
    @TestSetup
    static void makeData(){
        
        FSL__Scheduling_Policy__c schedulingPolicy = new FSM_TestDataFactory.SchedulingPolicyCreator().setName(FSM_Constants.DCF_SCHEDULING_POLICY).create();
        
        User newUser = new FSM_TestDataFactory.CretaeUser().create();
        
        OperatingHours op = new FSM_TestDataFactory.OperatingHoursCreator().setName(FSM_Constants.OH_AM_PM).setSlotType(FSM_Constants.DURATION)
                             .setBusinessUnit(FSM_Constants.BUSINESS_UNIT).create();
        
        ServiceResource sr = new FSM_TestDataFactory.ServiceResourceCreator().setName(FSM_Constants.RESOURCE_NAME).setIsActive(true)
                             .setRelatedRecordId(newUser.Id).setExternalId('1234').setBusinessUnit(FSM_Constants.WO_BUSINESS_UNIT).create();
        
        ServiceTerritory st = new FSM_TestDataFactory.ServiceTerritoryCreator().setName('Testing Territory').setIsActive(true)
                             .setExtenalId('888999').setOpreratingHours(op.Id).setSchedulingPolicy(schedulingPolicy.Id).setTerritoryLevel(5).create();
        
        WorkOrder wo = new FSM_TestDataFactory.WorkOrderCreator().setExternalId('testId').setStatus(FSM_Constants.STATUS_NEW).setServiceTerritory(st.Id)
                       .setBusinessUnit('Waste Infra').setOpenDate(DateTime.Now()).setSlaDate(DateTime.Now()).create();
        
        //Create Account
        Account acc = new FSM_TestDataFactory.AccountCreator().setName('Test Account').create();
        //Create Contact
        //Contact con = 
        new FSM_TestDataFactory.ContactCreator().setFirstName('FSM').setLastName('Salesforce Default Contact For Email').setAccount(acc.ID)
            			.setEmail('no-reply@defaultemail.com').create();
        
        //Infra Variables set-up
        List<FSM_DataCaptureFormInfra__c> allDCFInfra = new List<FSM_DataCaptureFormInfra__c>();
        List<FSM_DCFLineItemInfra__c> allDCFInfraline = new List<FSM_DCFLineItemInfra__c>();
        List<FSM_InfraDataCaptureForm2__c> allDCFInfra1 = new List<FSM_InfraDataCaptureForm2__c>();//Added for SFI-1204
        FSM_DataCaptureFormInfra__c testrecordInfra;
        FSM_DCFLineItemInfra__c testrecordInfraLine;
        FSM_DCFLineItemInfra__c testrecordInfraLineFirstRec;
        FSM_InfraDataCaptureForm2__c testrecordInfra1;//Added for SFI-1204
        
        // Non Infra Variables set-up 
        List<FSM_DataCaptureFormNonInfra__c> allDCFNonInfra = new List<FSM_DataCaptureFormNonInfra__c>();
        List<FSM_DCFLineItemNonInfra__c> allDCFNonInfraline = new List<FSM_DCFLineItemNonInfra__c>();
        FSM_DataCaptureFormNonInfra__c testrecordNonInfra;
        FSM_DCFLineItemNonInfra__c testrecordNonInfraLine;
        
        //Fetching Record Type Id 
        ID infraRecordTypeID = Schema.SObjectType.FSM_DataCaptureFormInfra__c.getRecordTypeInfosByDeveloperName()
            .get(FSM_Constants.FORMTYPE).getRecordTypeId();
        
        //Fetching Record Type Id for Infra 2 object SFI-1204
        ID infraRecordTypeID1 = Schema.SObjectType.FSM_InfraDataCaptureForm2__c.getRecordTypeInfosByDeveloperName()
            .get(FSM_Constants.FORMTYPE_INFRA1).getRecordTypeId();
        
        //Looping over bulk infra record creation
        for(Integer i = 0;i<numberOfRecordsToCreate;i++){
            testrecordInfra = new FSM_TestDataFactory.DataCaptureFormInfraCreator().setWorkorder(wo.Id).setStatus(FSM_Constants.STATUS_NEW).setTerritory(st.Id).setResourceId(sr.Id)
                .setRecordTypeId(infraRecordTypeID).setComment('test').setTime(18, 30, 2, 20).setGridReference('250001').setDateTime(System.today()).setMedium('MOBI').returnWithoutCreate();
                allDCFInfra.add(testrecordInfra);
        }
        Insert allDCFInfra;
         
        //Looping over bulk infra 1 record creation SFI-1204
        for(Integer i = 0;i<numberOfRecordsToCreate;i++){
            testrecordInfra1 = new FSM_TestDataFactory.DataCaptureFormInfra1Creator().setWorkorder(wo.Id).setStatus(FSM_Constants.STATUS_NEW).setTerritory(st.Id).setResourceId(sr.Id)
                .setRecordTypeId(infraRecordTypeID1).setSWRTask('2').setSewerStatus('Strategic').setSewerType('Foul').setMedium('MOBI').setSiteName('SiteInfra2').returnWithoutCreate();
                allDCFInfra1.add(testrecordInfra1);
        }
        Insert allDCFInfra1;
        
        //Fetching Record Type Id 
        ID infralineitemRecordTypeId = Schema.SObjectType.FSM_DCFLineItemInfra__c.getRecordTypeInfosByDeveloperName()
            .get(FSM_Constants.FORMTYPE).getRecordTypeId();
        
        //Looping over bulk infra line-item record creation, this part is Updated as part of SFI-2041 by Subir Maji 23rd July 2024
        for(Integer i = 0;i<4;i++){
            testrecordInfraLine = new FSM_TestDataFactory.DataCaptureFormLineItemInfraCreator().setWorkorder(wo.Id).setRecordTypeId(infralineitemRecordTypeId).setUid(2992)
                .setGridRefX(250001).setJobNumber(189).setExternalId('1221').setInfraParentId(allDCFInfra[0].ID).setCATSerial('1234').setGennySerial('453.01').returnWithoutCreate();
            if(i==0){
                Insert testrecordInfraLine;
                testrecordInfraLineFirstRec = testrecordInfraLine;
            }else{
                if(i>0 && i<3){
                    testrecordInfraLine.FSM_LineItem__c = testrecordInfraLineFirstRec.id;
                }
                allDCFInfraline.add(testrecordInfraLine);
            }
        }
        
        Insert allDCFInfraline;
        
        //Fetching Record Type Id 
        ID nonInfraRecordTypeId = Schema.SObjectType.FSM_DataCaptureFormNonInfra__c.getRecordTypeInfosByDeveloperName()
            .get(FSM_Constants.FORMTYPE).getRecordTypeId();
        
        //Looping over bulk infra record creation
        for(Integer i = 0;i<numberOfRecordsToCreate;i++){
            testrecordNonInfra = new FSM_TestDataFactory.DataCaptureFormNonInfraCreator().setWorkorder(wo.Id).setServiceResource(sr.Id)
                .setStatus(FSM_Constants.STATUS_NEW).setServiceTerritory(st.Id).setRecordTypeId(NonInfraRecordTypeId).returnWithoutCreate();
                allDCFNonInfra.add(testrecordNonInfra);
        }
        Insert allDCFNonInfra;
        
        //Fetching Record Type Id 
        ID nonInfraLineItemRecordTypeId = Schema.SObjectType.FSM_DCFLineItemNonInfra__c.getRecordTypeInfosByDeveloperName()
         	.get(FSM_Constants.FORMTYPE).getRecordTypeId();
        
        //Looping over bulk non infra line-item record creation
        for(Integer i = 0;i<numberOfRecordsToCreate;i++){
            testrecordNonInfraLine = new FSM_TestDataFactory.DataCaptureFormLineItemNonInfraCreator().setWorkorder(wo.Id).setRecordTypeId(nonInfraLineItemRecordTypeId)
                .setNonInfraParent(allDCFNonInfra[i].ID).returnWithoutCreate();
                allDCFNonInfraline.add(testrecordNonInfraLine);
        }
        Insert allDCFNonInfraline;
    }
    
	/********************************************************************************************************
    @Author      : Manish jagnani
    @Description : method to test log creation for Data capture infra 
    @description : Created as part of user story #SFI-35
    @Date        : 31-July-2023
	********************************************************************************************************/
    @istest
    static void testBulkSuccessPlatformEventCreationInfra(){
        List<FSM_DataCaptureFormInfra__c> allInfraRec = [Select ID, FSM_Status__c from FSM_DataCaptureFormInfra__c];
      
        test.startTest();
        for(FSM_DataCaptureFormInfra__c all : allInfraRec){
            all.FSM_Status__c = FSM_Constants.STATUS_COMPLETED;
        }
        
        Update allInfraRec;
      
        test.stopTest();
        
        //Log creation record fetch
        List<FSM_IntegrationLog__c> allLog = [Select ID from FSM_IntegrationLog__c];
        System.assertEquals(allLog != null, true, 'Integration Log Created');   
    }
    
    /********************************************************************************************************
    @Author      : Subir Maji
    @Description : method to test log creation for Data capture infra 1 
    @description : Created as part of user story #SFI-1204
    @Date        : 28-Dec-2023
	********************************************************************************************************/
    @istest
    static void testBulkSuccessPlatformEventCreationInfra1(){
        List<FSM_InfraDataCaptureForm2__c> allInfraRec = [Select ID, FSM_Status__c from FSM_InfraDataCaptureForm2__c];
		
        test.startTest();
        for(FSM_InfraDataCaptureForm2__c all : allInfraRec){
            all.FSM_Status__c = FSM_Constants.STATUS_COMPLETED;
        }
        Update allInfraRec;
        test.stopTest();
        
        //Log creation record fetch
        List<FSM_IntegrationLog__c> allLog = [Select ID from FSM_IntegrationLog__c];
        
        System.assertEquals(allLog != null, true, 'Integration Log Created');
    }
    
	/********************************************************************************************************
    @Author      : Manish jagnani
    @Description : method to test log creation for Data capture Non infra 
    @description : Created as part of user story #SFI-35
    @Date        : 31-July-2023
	********************************************************************************************************/
    @istest
    static void testBulkSuccessPlatformEventCreationNonInfra(){
        List<FSM_DataCaptureFormNonInfra__c> allNonInfraRec = [Select ID, FSM_Status__c from FSM_DataCaptureFormNonInfra__c];
        
        test.startTest();
        for(FSM_DataCaptureFormNonInfra__c all : allNonInfraRec){
            all.FSM_Status__c = FSM_Constants.STATUS_COMPLETED;
        }
        Update allNonInfraRec;
        test.stopTest();
        
        //Log creation record fetch
        List<FSM_IntegrationLog__c> allLog = [Select ID from FSM_IntegrationLog__c];
        
        System.assertEquals(allLog != null, true, 'Integration Log Created');
    }

}