force-app/main/default/objects/FSL__Scheduling_Policy__c/FSL__Scheduling_Policy__c.object-meta.xml
<CustomObject>
    <label>Scheduling Policy</label>
    <nameField>
        <label>Scheduling Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduling Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FSL__Scheduling_Policy__c/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <description>STW Business area</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSL__Work_Rule__c/FSL__Work_Rule__c.object-meta.xml
<CustomObject>
    <label>Work Rule</label>
    <nameField>
        <label>Work Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Rules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSL__Work_Rule__c/fields/FSL__Match_Constant_Boolean_Value__c.field-meta.xml
<CustomField>
    <fullName>FSL__Match_Constant_Boolean_Value__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Value is True</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSL__Work_Rule__c/fields/FSL__Resource_Property__c.field-meta.xml
<CustomField>
    <fullName>FSL__Resource_Property__c</fullName>
    <inlineHelpText>A numeric field on the service resource to count against.</inlineHelpText>
    <label>Resource Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IsActive</fullName>
            </value>
            <value>
                <fullName>IsCapacityBased</fullName>
            </value>
            <value>
                <fullName>FSM_CustomerAppointmentCapacity__c</fullName>
            </value>
            <value>
                <fullName>FSM_SeniorTechnicalSupervisor__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSM_TMAPermit__c/FSM_TMAPermit__c.object-meta.xml
<CustomObject>
    <description>Created as part of user story #SFS-32</description>
    <label>TMA</label>
    <nameField>
        <displayFormat>TMAPER-{000000}</displayFormat>
        <label>TMA Permit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FSM_TMAPermitNoticePeriods__c/FSM_TMAPermitNoticePeriods__c.object-meta.xml
<CustomObject>
    <label>TMA Permit Notice Period</label>
    <nameField>
        <displayFormat>NP-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMA Permit Notice Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceAppointment/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <description>SFS-155</description>
    <formula>TEXT(FSSK__FSK_Work_Order__r.FSM_BusinessUnit__c)</formula>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSSK__FSK_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>FSSK__FSK_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>FSK_Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <description>SFS-110</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/FSM_NumberOfDaysToDispatch__c.field-meta.xml
<CustomField>
    <fullName>FSM_NumberOfDaysToDispatch__c</fullName>
    <description>Created as part of user story #SFS-814</description>
    <label>Number of Days to Dispatch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/FSM_NumberOfSAToDispatch__c.field-meta.xml
<CustomField>
    <fullName>FSM_NumberOfSAToDispatch__c</fullName>
    <description>Created as part of user story #SFS-814</description>
    <label>Number of Appointments to Dispatch</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FSM_NumberOfDaysToDispatch__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waste Infra</fullName>
            </value>
            <value>
                <fullName>Water Infra</fullName>
            </value>
            <value>
                <fullName>Water Non Infra</fullName>
            </value>
            <value>
                <fullName>Waste Non Infra</fullName>
            </value>
            <value>
                <fullName>Bio Resource</fullName>
            </value>
            <value>
                <fullName>Developer Services</fullName>
            </value>
            <value>
                <fullName>Metering</fullName>
            </value>
            <value>
                <fullName>Green Recovery</fullName>
            </value>
            <value>
                <fullName>WasteNon Infra</fullName>
                <isActive>false</isActive>
                <label>WasteNon Infra</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_TMAPermit__c.field-meta.xml
<CustomField>
    <fullName>FSM_TMAPermit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TMA Permit</label>
    <referenceTo>FSM_TMAPermit__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Waste Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Waste Non Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Water Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Water Non Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Bio Resource</fullName>
    </customValue>
    <customValue>
        <fullName>Developer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Metering</fullName>
    </customValue>
    <customValue>
        <fullName>Green Recovery</fullName>
        <isActive>false</isActive>
        <label>Green Recovery</label>
    </customValue>
    <description>STW Business Unit</description>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSM_updatenoticedateTest.cls
/****************************************************************************************************************************
@Author : Aishwarya Bhosale
@Date   : 10th August 2023
@Description : This class is used to test if Notice date on permit is calculated correctly
@Description : Created as part of user story #SFS-1833
@Main Class : FSM_updatenoticedate  
@LastModified: 22-11-2024 Aishwarya Bhosale
==============================================================================================================================
*/
@IsTest
public class FSM_updatenoticedateTest {
    /*--------------------------------------------------------------
@Author      : Aishwarya Bhosale
@Description : This method is used to create test data setup.
-----------------------------------------------------------------*/
    @TestSetup
    static void testDataSetup(){
         FSL.GlobalAPIS.addStatusTransition('New', 'Scheduled');
        FSL.GlobalAPIS.addStatusTransition('Scheduled', 'Dispatched');
        User u=new FSM_TestDataFactory.CretaeUser().create();
         Double latitudeValue = 52.58;
        Double longitudeValue = -2.13; 
         //Get WO record type
            Id recTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName()
            .get(FSM_Constants.RECORDTYPE_WASTENONINFRA).getRecordTypeId();
          Date currentDate = Date.today();
        WorkOrder wo=new WorkOrder();
           // Create work rule
        FSL__Work_Rule__c wr = new FSL__Work_Rule__c(Name='Active Resources',FSL__Resource_Property__c='IsActive',FSL__Match_Constant_Boolean_Value__c=true);
        insert wr;
        
        // Create scheduling policy
        FSL__Scheduling_Policy__c testPolicy = new FSL__Scheduling_Policy__c(Name = 'Waste Non Infra Soft Boundaries', FSM_BusinessUnit__c = 'Waste Non Infra');
        insert testPolicy;
        
        // Create scheduling policy work rule
        FSL__Scheduling_Policy_Work_Rule__c spwr = new FSL__Scheduling_Policy_Work_Rule__c(FSL__Scheduling_Policy__c=testPolicy.Id, FSL__Work_Rule__c=wr.Id);
        insert spwr;
                
        // Create OperatingHours
        OperatingHours testOpHrs = new FSM_TestDataFactory.OperatingHoursCreator().setName('Test Base Calendar').setTimeZone('Europe/London').setSlotType(FSM_Constants.DURATION).create();
                
        // Create ServiceTerritory where FSM_NumberOfDaysToDispatch__c != 1 & FSM_NumberOfSAToDispatch__c = 'Full' --- Scenario 1
        ServiceTerritory testTerritory = new FSM_TestDataFactory.ServiceTerritoryCreator().setName('1302WD4M4 Insp South One (Edgbaston)')
            .setOpreratingHours(testOpHrs.Id).setAutoSchedulingPolicy(testPolicy.Id).setWorkingSubAreaRequired(true)
            .setNumberOfDaysToDispatch('5').setNumberOfSAToDispatch('Full').setIsActive(true).setBusinessUnit('Waste Non Infra').create();

        
        //create tma permit
        FSM_TMAPermit__c tmaminor=new FSM_TestDataFactory.TMAPermitCreator().setHighwayAuthority('0011').setWorksCategory('03').setTMAtype('PRMT').create(); 
        FSM_TMAPermit__c tmamajor =new FSM_TestDataFactory.TMAPermitCreator().setHighwayAuthority('0011').setWorksCategory('01').setTMAtype('PRMT').create(); 
            // Create a test WorkOrder data
        for(Integer i=0;i<2;i++){
            wo = new FSM_TestDataFactory.WorkOrderCreator().setRecordType(recTypeId).setTma(tmaminor.id).setBusinessUnit('Waste Non Infra').setServiceTerritory(testTerritory.Id).setSuitability('E').setNoticeState('NTBS').create(); 
             //Create Service Appointment
             new FSM_TestDataFactory.ServiceAppointmentCreator().setParentRecordId(wo.Id).setStatus('NEW').setLongitude(longitudeValue).setLatitude(latitudeValue).setServiceTerritory(testTerritory.Id)
                .setEarliestStartTime(DateTime.Now().AddDays(-2)).setDueDate(DateTime.Now().AddDays(18)).create();
        }
      
         //create tma noticeperiod records
         FSM_TMAPermitNoticePeriods__c tmanoticeperiod = new FSM_TestDataFactory.TMAPermitNoticePeriodCreator().setHighwayAuthority('0011').setWorksCategory('03').setNoticePeriod(4).create(); 
         FSM_TMAPermitNoticePeriods__c tmanoticeperiod1 =   new FSM_TestDataFactory.TMAPermitNoticePeriodCreator().setHighwayAuthority('0011').setWorksCategory('01').setNoticePeriod(11).create(); 
         FSM_TMAPermitNoticePeriods__c tmanoticeperiod2 = new FSM_TestDataFactory.TMAPermitNoticePeriodCreator().setHighwayAuthority('0012').setWorksCategory('03').setNoticePeriod(4).create(); 
         FSM_TMAPermitNoticePeriods__c tmanoticeperiod3 =   new FSM_TestDataFactory.TMAPermitNoticePeriodCreator().setHighwayAuthority('0012').setWorksCategory('01').setNoticePeriod(11).create(); 
            
        
    }
    @IsTest
    static void testcalnoticedate(){  
    
            test.startTest();
            List<FSM_updatenoticedate.Serviceappoitments> serviceAppList = new List<FSM_updatenoticedate.Serviceappoitments>();
            List <ServiceAppointment> serviceappt=[Select id,SchedStartTime,SchedEndTime,FSSK__FSK_Work_Order__r.FSM_TMAPermit__c from ServiceAppointment];
            //  Datetime schedulestart = Datetime.newInstance(2024, 11, 02, 14, 30, 0);
              Date currentDate = Date.today();
            Datetime schedulestart =   Datetime.newInstance(currentDate.addDays(+1), Time.newInstance(14, 30, 0, 0));
            List <ServiceAppointment> serviceapptupdt=new List<ServiceAppointment>();
            Integer i=0;
            for(ServiceAppointment saupdt:serviceappt){
                saupdt.SchedStartTime=Datetime.newInstance(currentDate.addDays(i+1), Time.newInstance(14, 30, 0, 0));
                saupdt.SchedEndTime=Datetime.newInstance(currentDate.addDays(i+1), Time.newInstance(15, 30, 0, 0));
                saupdt.Status='Scheduled';
                i=i+1;
                serviceapptupdt.add(saupdt);
                
            }
            update serviceapptupdt;
            List <ServiceAppointment> updatedserviceappt=[Select id,SchedStartTime,SchedEndTime,FSSK__FSK_Work_Order__r.FSM_TMAPermit__c from ServiceAppointment];
            for(ServiceAppointment sappt:updatedserviceappt){
                FSM_updatenoticedate.Serviceappoitments sa=new FSM_updatenoticedate.Serviceappoitments();
				sa.schedulestart=  sappt.SchedStartTime;
                sa.noticeperiod=  4;
                sa.tmaid=sappt.FSSK__FSK_Work_Order__r.FSM_TMAPermit__c;
                sa.eventtype='0200';
                sa.serviceapptid=sappt.Id;
                serviceAppList.add(sa);
                
            }
           /* Date currentDate = Date.today();
            Datetime schedulestart =   Datetime.newInstance(currentDate.addDays(+1), Time.newInstance(14, 30, 0, 0));
            system.debug('date from test class'+schedulestart);
            Decimal period=3.00;
            FSM_updatenoticedate.Serviceappoitments sa1=new FSM_updatenoticedate.Serviceappoitments();
            sa1.noticeperiod=period;
            
            sa1.schedulestart=schedulestart;
            FSM_updatenoticedate.Noticedate finalnoticedate=new FSM_updatenoticedate.Noticedate();
            List<FSM_updatenoticedate.Noticedate> noticedtlst=new List<FSM_updatenoticedate.Noticedate>();
            noticedtlst=FSM_updatenoticedate.calculateNoticeDateonPermit(new List<FSM_updatenoticedate.Serviceappoitments> {sa});
            System.debug('noticedtlst--->' + noticedtlst);
            System.assert(noticedtlst.size()>0,'notice date calculated');*/
            FSM_updatenoticedate.calculateNoticeDateonPermit(serviceAppList);
            test.stopTest(); 
        
    }
    @isTest
     static void testcalnoticedateonunschedule(){  
       
            test.startTest();
                    List<FSM_updatenoticedate.Serviceappoitments> newserviceappt = new List<FSM_updatenoticedate.Serviceappoitments>();
            List <ServiceAppointment> serviceapptlist=[Select id,SchedStartTime,SchedEndTime,FSSK__FSK_Work_Order__r.FSM_TMAPermit__c from ServiceAppointment];
            Date currentDate = Date.today();
            Datetime schedulestart =   Datetime.newInstance(currentDate.addDays(+1), Time.newInstance(14, 30, 0, 0));
           
            for(ServiceAppointment sappt:serviceapptlist){
                FSM_updatenoticedate.Serviceappoitments sa=new FSM_updatenoticedate.Serviceappoitments();
				sa.schedulestart=  sappt.SchedStartTime;
                sa.noticeperiod=  4;
                sa.tmaid=sappt.FSSK__FSK_Work_Order__r.FSM_TMAPermit__c;
                sa.eventtype='0200';
                sa.serviceapptid=sappt.Id;
                newserviceappt.add(sa);
                
            }
              FSM_updatenoticedate.calculateNoticeDateonPermit(newserviceappt);
            test.stopTest(); 
       
}
    
    
}