force-app/main/default/objects/FSL__Scheduling_Policy__c/FSL__Scheduling_Policy__c.object-meta.xml
<CustomObject>
    <label>Scheduling Policy</label>
    <nameField>
        <label>Scheduling Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduling Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FSL__Scheduling_Policy__c/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <description>STW Business area</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSL__Scheduling_Policy__c/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OperatingHours/fields/FSM_SlotType__c.field-meta.xml
<CustomField>
    <fullName>FSM_SlotType__c</fullName>
    <label>Slot Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>CSAP</fullName>
            </value>
            <value>
                <fullName>2HRS</fullName>
            </value>
            <value>
                <fullName>AMPM</fullName>
            </value>
            <value>
                <fullName>MAPM</fullName>
            </value>
            <value>
                <fullName>M2HR</fullName>
            </value>
            <value>
                <fullName>2 hour</fullName>
                <isActive>false</isActive>
                <label>2 hour</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <isActive>false</isActive>
                <label>AM</label>
            </value>
            <value>
                <fullName>EVE</fullName>
                <isActive>false</isActive>
                <label>EVE</label>
            </value>
            <value>
                <fullName>PM</fullName>
                <isActive>false</isActive>
                <label>PM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResourcePreference/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <description>External ID</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <description>SFS-155</description>
    <formula>TEXT(FSSK__FSK_Work_Order__r.FSM_BusinessUnit__c)</formula>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_CustomerAppointment__c.field-meta.xml
<CustomField>
    <fullName>FSM_CustomerAppointment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFS-63</description>
    <label>Customer Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>SAP Order-Operation Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_IsTemporaryRecord__c.field-meta.xml
<CustomField>
    <fullName>FSM_IsTemporaryRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFI-1783, Background field, this records are created for appointment booking slots, and will de deleted automatically</description>
    <label>Is Temporary Record?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_StandardTextKey__c.field-meta.xml
<CustomField>
    <fullName>FSM_StandardTextKey__c</fullName>
    <formula>FSSK__FSK_Work_Order__r.FSM_StandardTextKey__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Standard Text Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSM_TaskType__c.field-meta.xml
<CustomField>
    <fullName>FSM_TaskType__c</fullName>
    <formula>FSSK__FSK_Work_Order__r.FSM_TaskType__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Task Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSSK__FSK_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>FSSK__FSK_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>FSK_Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <description>External ID</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <description>SFS-110</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <description>External ID</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/FSM_SchedulingPolicy__c.field-meta.xml
<CustomField>
    <fullName>FSM_SchedulingPolicy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created for SFS-107</description>
    <inlineHelpText>Customer based policy</inlineHelpText>
    <label>Appointment Booking Scheduling Policy</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.FSM_BusinessUnit__c</field>
            <operation>equals</operation>
            <valueField>FSL__Scheduling_Policy__c.FSM_BusinessUnit__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FSL__Scheduling_Policy__c</referenceTo>
    <relationshipLabel>Service Territories</relationshipLabel>
    <relationshipName>Service_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SkillRequirement/fields/FSM_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>FSM_ExternalId__c</fullName>
    <description>External ID</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>FSM_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_IsTemporaryRecord__c.field-meta.xml
<CustomField>
    <fullName>FSM_IsTemporaryRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of SFI-1786</description>
    <label>Is Temporary Record?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_StandardTextKey__c.field-meta.xml
<CustomField>
    <fullName>FSM_StandardTextKey__c</fullName>
    <label>Standard Text Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSM_TaskType__c.field-meta.xml
<CustomField>
    <fullName>FSM_TaskType__c</fullName>
    <description>Updated as part of SFI-1136</description>
    <label>Task Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Waste Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Waste Non Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Water Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Water Non Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Bio Resource</fullName>
    </customValue>
    <customValue>
        <fullName>Developer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Metering</fullName>
    </customValue>
    <customValue>
        <fullName>Green Recovery</fullName>
        <isActive>false</isActive>
        <label>Green Recovery</label>
    </customValue>
    <description>STW Business Unit</description>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSM_AppointmentBookingHelper.cls
/**----------------------------------------------------
* @description :  To get avilable appointment booking slots               
* @group      :  Capgemini
* Test Class  :  FSM_AppointmentBookingTest
* ver    Date                Author             Modification
1.0    23th June 2023       Srikanth           Created-SFI-31
2.0    11th June 2024       Srikanth           Updated-SFI-2213
--------------------------------------------------*/
public with sharing class FSM_AppointmentBookingHelper{
    
    private static String randomExternalId = FSM_Utility.generateRandomNumber(); //To generate random External ID for Work order
    //Below variables added by Subir Maji 16th July 2024 as part of SFI-2479
    private static List<Skill> listSkill = new List<Skill>(); //To query existing skill records in SF
    private static List<ServiceResource> listSR = new List<ServiceResource>(); //To query existing Service resource records in SF
    public static ServiceTerritory st ; //To query existing Service territory records in SF
    public static OperatingHours oh; //To query existing Operating Hours records in SF
    
    /**
    * @description checkForDataIssues Check if any data is missing in payload or missing in SF side then throw error
    * @param requestBody
    * @date Added by Subir Maji 16th July 2024 as part of SFI-2479 
    */
    public static void checkForDataIssues(FSM_CreateCustomerAppointmentWOSA.FSM_AppointmentRequest requestData){
        List<String> extIDNotPresent = new List<String>(); //To Collect all the ID which is not present in SF
        List<String> extIDPresent = new List<String>(); //To Collect all the ID which is present in SF
        List<String> allErrors = new List<String>(); //To create a single error message
        Boolean isErrorPresent = false; //for throwing exception at teh end just once
        
        //Check for service territory is present or not
        if(String.isBlank(requestData.serviceTerritoryId)){
            isErrorPresent = true;
            allErrors.add(system.label.FSM_ServTerBlankErrINT11);
        }else{
            List<ServiceTerritory> allTerritory = [Select id,FSM_ExternalId__c,OperatingHoursId,FSM_SchedulingPolicy__c,
                                                   OperatingHours.TimeZone 
                                                   from ServiceTerritory 
                                                   where FSM_ExternalId__c=:requestData.serviceTerritoryId WITH SECURITY_ENFORCED limit 1];
            
            if(allTerritory == null || allTerritory.isEmpty()){
                isErrorPresent = true;
                allErrors.add(requestData.serviceTerritoryId + system.label.FSM_ServTerNotFoundErrINT11);
            }else{
                st = allTerritory[0];
            }
        }
        
        //Check for Slot type or operating hours is present or not
        if(String.isBlank(requestData.SlotType)){
            isErrorPresent = true;
            allErrors.add(system.label.FSM_SlotTypeErrINT11);
        }else{
            List<OperatingHours> allOperatingHour = [select id,Name, FSM_SlotType__c, FSM_BusinessUnit__c  
                                                     from OperatingHours 
                                                     where FSM_SlotType__c=:requestData.slotType 
                                                     AND FSM_BusinessUnit__c=:requestData.businessArea WITH SECURITY_ENFORCED LIMIT 1];
            
            if(allOperatingHour == null || allOperatingHour.isEmpty()){
                isErrorPresent = true;
                allErrors.add(system.label.FSM_SlotTypeNotFoundErrINT11);
            }else{
                oh = allOperatingHour[0];
            }
        }
        
        //Check if Service Resource are available in SF or not, if not present then throw error
        //Updated by Subir Maji as part of SFI-2585 6th Aug 24
        if(requestData.preferredResource != null && requestData.preferredResource.size() > 0){
            listSR = [select id,FSM_ExternalId__c 
                      from ServiceResource 
                      where FSM_ExternalId__c In :requestData.preferredResource WITH SECURITY_ENFORCED];
            
            if(listSR == null || listSR.isEmpty()){
                isErrorPresent = true;
                allErrors.add(system.label.FSM_ServResNotFoundErrINT11);
            }else if(requestData.preferredResource.size() != listSR.size()){
                for(ServiceResource sr : listSR){
                    extIDPresent.add(sr.FSM_ExternalId__c);
                }
                for(String sr : requestData.preferredResource){
                    if(!extIDPresent.contains(sr)){
                        extIDNotPresent.add(sr);
                    }
                }
                isErrorPresent = true;
                allErrors.add(extIDNotPresent +system.label.FSM_TheseServResNotFoundErrINT11);
            }
        }
        
        //Check if Skills are available in SF or not, if not present then throw error
        //Updated by Subir Maji as part of SFI-2585 6th Aug 24
        if(requestData.requiredSkills != null && requestData.requiredSkills.size() > 0){
            listSkill = [select id,MasterLabel 
                         from skill 
                         where MasterLabel In :requestData.requiredSkills WITH SECURITY_ENFORCED];
            
            if(listSkill == null || listSkill.isEmpty()){
                isErrorPresent = true;
                allErrors.add(system.label.FSM_SkillsNotFoundErrINT11);
            }else if(requestData.requiredSkills.size() != listSkill.size()){
                extIDNotPresent = new List<String>();
                extIDPresent = new List<String>();
                for(Skill sk : listSkill){
                    extIDPresent.add(sk.MasterLabel);
                }
                for(String sk : requestData.requiredSkills){
                    if(!extIDPresent.contains(sk)){
                        extIDNotPresent.add(sk);
                    }
                }
                isErrorPresent = true;
                allErrors.add(extIDNotPresent +system.label.FSM_TheseSkillsNotFoundErrINT11);
            }
        }
        
        //Check for Mandatory field value is present or not
		//Added as part of SFI-2566 by Subir Maji 30th July 24
		if(String.isBlank(requestData.longitude) || String.isBlank(requestData.latitude) || String.isBlank(requestData.earlyStart) || String.isBlank(requestData.dueDate) || String.isBlank(requestData.postcode) || 
          String.isBlank(requestData.duration) || String.isBlank(requestData.businessArea) || String.isBlank(requestData.durationType)){
            isErrorPresent = true;
            allErrors.add(system.label.FSM_MandatoryFieldErrINT11);
        }
        //If any data issue found throw exception
        if(isErrorPresent){
            throw new Fieldscheckexception(JSON.serialize(allErrors));
        }
    }
    
    /**
    * @description getOperatingHours to get OperatingHours
    * @return Id
    */
    public static Id getDefaultSchedulingPolicyID(){
        FSL__Scheduling_Policy__c schPol = [select id  
                                             from FSL__Scheduling_Policy__c 
                                             where Name=: System.Label.FSM_DefaultSchedulingPolicy WITH SECURITY_ENFORCED Limit 1 ];
        return schPol.Id;
    }
    
    /**
    * @description createWorkOrder to create WorkOrder 
    * @param requestData
    * @param st
    * @return WorkOrder
    */
    public static WorkOrder createWorkOrder(FSM_CreateCustomerAppointmentWOSA.FSM_AppointmentRequest requestData,ServiceTerritory st){
        WorkOrder wo=new WorkOrder();
        
        wo.FSM_ExternalId__c= randomExternalId;
        wo.StartDate=DateTime.valueOf(requestData.earlyStart.replace('T',' ')); //Updated as part of SFI-2566 by Subir Maji 30th July 24       
        wo.EndDate=DateTime.valueOf(requestData.dueDate.replace('T',' ')); //Updated as part of SFI-2566 by Subir Maji 30th July 24
        wo.Duration=Decimal.valueof(requestData.duration); //Updated as part of SFI-2566 by Subir Maji 30th July 24
        wo.Priority=requestData.priority;
        wo.FSM_StandardTextKey__c=requestData.standardTextKey;
        wo.ServiceTerritoryId=st.Id;
        wo.FSM_TaskType__c=requestData.taskType; 
        wo.PostalCode=requestData.postcode;
        wo.FSM_BusinessUnit__c=requestData.businessArea;
        wo.Longitude=Decimal.valueof(requestData.longitude); //Updated as part of SFI-2566 by Subir Maji 30th July 24
        wo.Latitude=Decimal.valueof(requestData.latitude); //Updated as part of SFI-2566 by Subir Maji 30th July 24
        wo.FSM_IsTemporaryRecord__c=true;
        wo.DurationType=requestData.DurationType;
        if(!String.isBlank(requestData.minimumCrewSize)){
            wo.MinimumCrewSize=Integer.valueOf(requestData.minimumCrewSize);
        }
        
        if(Schema.sObjectType.WorkOrder.isCreateable() && Schema.sObjectType.WorkOrder.isUpdateable()){
            upsert wo FSM_ExternalId__c;
        }
        if(requestData.preferredResource!=null){
            addPreferedResource(requestData.preferredResource , wo.Id);
        }
        if(requestData.requiredSkills!=null){
            addSkills(requestData.requiredSkills,wo.Id);
        }
        return wo;
    }
    
    /**
    * @description createServiceAppointment to create ServiceAppointment 
    * @param requestData
    * @param st
    * @param wo
    * @return WorkOrder
    */
    public static ServiceAppointment createServiceAppointment(FSM_CreateCustomerAppointmentWOSA.FSM_AppointmentRequest requestData,ServiceTerritory st,workOrder wo){
        ServiceAppointment sa=new ServiceAppointment();
        sa.FSM_ExternalId__c=randomExternalId;
        sa.EarliestStartTime=DateTime.valueOf(requestData.earlyStart.replace('T',' ')); //Updated as part of SFI-2566 by Subir Maji 30th July 24
        sa.DueDate=DateTime.valueOf(requestData.dueDate.replace('T',' ')); //Updated as part of SFI-2566 by Subir Maji 30th July 24
        sa.Duration=Decimal.valueOf(requestData.duration); //Updated as part of SFI-2566 by Subir Maji 30th July 24
        sa.ServiceTerritoryId=st.Id;
        sa.Longitude=Decimal.valueof(requestData.longitude); //Updated as part of SFI-2566 by Subir Maji 30th July 24
        sa.Latitude=Decimal.valueof(requestData.latitude); //Updated as part of SFI-2566 by Subir Maji 30th July 24
        sa.PostalCode=requestData.postcode;
        sa.FSM_CustomerAppointment__c=true;
        sa.FSSK__FSK_Work_Order__c=wo.Id;
        sa.ParentRecordId=wo.Id;
        sa.FSM_IsTemporaryRecord__c = true;
        sa.DurationType=requestData.DurationType;
        
        if(Schema.sObjectType.ServiceAppointment.isCreateable() && Schema.sObjectType.ResourcePreference.isUpdateable()){
            upsert sa FSM_ExternalId__c;
        }
        return sa;
    }
    
    /**
    * @description addPreferedResource to create Resource Preference 
    * @param preferedResource
    * @param workOrderId
    */
    private static void addPreferedResource(String[] preferedResource,Id workOrderId){
        if(preferedResource.size() == 0){
            return ;
        }
        List<ResourcePreference> listRP = new List<ResourcePreference>();
        ResourcePreference rp;
        
        for(ServiceResource sr : listSR){
            rp = new ResourcePreference();
            rp.RelatedRecordId = workOrderId;
            rp.ServiceResourceId = sr.id;
            listRP.add(rp);
        }
        if(listRP.size()>0 && Schema.sObjectType.ResourcePreference.isCreateable()){
            insert listRP;
        }
    }
    
    /**
    * @description addSkills to create Skills for teh job 
    * @param skills
    * @param workOrderId
    */
    private static void addSkills(String[] skills,Id workOrderId){
        if(skills.size() == 0){
            return ;
        }
        List<SkillRequirement> listSkillReq = new List<SkillRequirement>();
        SkillRequirement skillReq;
        
        for(skill sr : listSkill){
            skillReq = new SkillRequirement();
            skillReq.RelatedRecordId = workOrderId;
            skillReq.SkillId = sr.id;
            listSkillReq.add(skillReq);
        }
        
        if(listSkillReq.size()>0 && Schema.sObjectType.SkillRequirement.isCreateable()){
            insert listSkillReq;
        }
    }
    
    /**
    * @description FSM_AppointmentRequest
    * @param errMsg
    * @return ResponseWrapper1
    */
    public static ErrorResponseWrapper returnErrorResponse(String errMsg){
        ErrorResponseWrapper wrap=new ErrorResponseWrapper();
        wrap.status=FSM_Constants.RES_ERROR;
        wrap.StatusCode=FSM_Constants.RESPONSE_400;
        //Added below part by Subir Maji as part of SFI-2585 6th Aug 24
        if(!errMsg.startsWith('[')){
            errMsg = '["' + errMsg + '"]';
        }
        wrap.ErrorMessage=(List<String>)JSON.deserialize(errMsg, List<String>.class);//Updated by Subir Maji as part of SFI-2585 6th Aug 24
        return wrap;
    }
    
    /**
    * @description ErrorResponseWrapper for error response
    * @date Added by Subir Maji 16th July 2024 as part of SFI-2479
    */
    public class ErrorResponseWrapper{
        public string status;
        public Integer statusCode;
        public List<String> errorMessage; //Updated by Subir Maji as part of SFI-2585 6th Aug 24
    }
    
    /**
    * @description Fieldscheckexception to show exception messages
    */
    Public class Fieldscheckexception extends Exception{}    
}