force-app/main/default/objects/FSM_PlatformEventPicklistLwc__mdt/FSM_PlatformEventPicklistLwc__mdt.object-meta.xml
<CustomObject>
    <description>This Custom metadata used to display Platform event as picklist to subscribe the events SFI-1002</description>
    <label>Platform Event Picklist</label>
    <pluralLabel>Platform Event Picklists</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSM_PlatformEventPicklistLwc__mdt/fields/FSM_Active__c.field-meta.xml
<CustomField>
    <fullName>FSM_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Platform event picklist for platform event subscribe in lwc SFI-1002</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSM_PlatformEventPicklistLwc__mdt/fields/FSM_EventApiName__c.field-meta.xml
<CustomField>
    <fullName>FSM_EventApiName__c</fullName>
    <description>Platform event picklist for platform event subscribe in lwc SFI-1002</description>
    <label>Event Api Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSM_PlatformEventControllerPicklist.cls
/********************************************************************************************************
@Author      : Himanshu Dobriyal
@description : This AuraEnabled class is used to return list of Custom metadata referred in fSM_PlatformEventSubscribe_lwc Component.
@Description : Created as part of platform Event testing requirement SFI-1002.
@Test Class  : FSM_PlatformEventControllerPicklistTest
@Date        : 01-November-2023
********************************************************************************************************/
public with sharing class FSM_PlatformEventControllerPicklist {
/************************************************************************************************************************
@Author      : Himanshu Dobriyal
@description : This Method is used to return list of Custom metadata referred in fSM_PlatformEventSubscribe_lwc Component.
@return : List<FSM_PlatformEventPicklistLwc__mdt>
@Test Class  : FSM_PlatformEventControllerPicklistTest
@Date        : 01-November-2023
************************************************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<FSM_PlatformEventPicklistLwc__mdt> getCustomSettingPicklistValues() {
        List<FSM_PlatformEventPicklistLwc__mdt> picklistValues = new List<FSM_PlatformEventPicklistLwc__mdt>();
        picklistValues = [SELECT Label, FSM_EventApiName__c,FSM_Active__c FROM FSM_PlatformEventPicklistLwc__mdt where FSM_Active__c=true WITH SECURITY_ENFORCED];
        // Query on metadata to get the Platform event api name and label which are active to populate the picklistValues list.
        return picklistValues;
    }
/************************************************************************************************************************
@Author      : Himanshu Dobriyal
@description : This Method is used to return a boolean value referred in fSM_PlatformEventSubscribe_lwc Component.
@return : Boolean
@Test Class  : FSM_PlatformEventControllerPicklistTest
@Date        : 02-November-2023
************************************************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static Boolean isCurrentUserValidToSeeComponent() {
        string[] isAllowedProfileName = new string[]{'System Administrator','FSM System Administrator','Salesforce API Only System Integrations','FSM Integration'};
        User currentUser = [SELECT Id, Profile.Name FROM User WHERE Id = :UserInfo.getUserId() WITH SECURITY_ENFORCED limit 1];
            if(currentUser.Profile.Name!=null && isAllowedProfileName.contains(currentUser.Profile.Name)){
                return true;
               }
        return false;
    }
}